### ISSUE TITLE
SEGV when building with clang 5.0.1

### ISSUE THREAD

**Issue by ArturHarasimiuk** [intel/intel-graphics-compiler#10]
there is crash in libigdccl.so when built with clang 5.0.1 on ArchLinux.

```
#0  0x00007f0585cd2c62 in llvm::MemoryBuffer::getMemBufferRef() const () from .../compute-runtime/build/bin/libigdccl.so
#1  0x00007f05850cf8ca in TC::TranslateBuild (pInputArgs=pInputArgs@entry=0x7ffdcd9729d0, pOutputArgs=pOutputArgs@entry=0x7ffdcd9729a0, 
    inputDataFormatTemp=<optimized out>, IGCPlatform=..., profilingTimerResolution=<optimized out>)
    at .../compute-runtime/igc/IGC/AdaptorOCL/dllInterfaceCompute.cpp:729
#2  0x00007f0585174408 in IGC::IgcOclTranslationCtx<0ul>::Impl::Translate (this=<optimized out>, outVersion=<optimized out>, src=<optimized out>, 
    options=<optimized out>, internalOptions=<optimized out>, tracingOptions=<optimized out>, tracingOptionsCount=<optimized out>)
    at .../compute-runtime/igc/IGC/AdaptorOCL/ocl_igc_interface/impl/igc_ocl_translation_ctx_impl.h:173
#3  0x0000557a3d0ceb45 in OCLRT::OfflineCompiler::buildSourceCode() ()
#4  0x0000557a3d0d43d2 in OCLRT::OfflineCompiler::build() ()
#5  0x0000557a3d0cd66c in main ()
```

original issue: 
https://github.com/intel/compute-runtime/issues/23

**Comment by AnupamaChandrasekhar** [comment]
We do not support building the builtins with Clang 5.0, since the LLVM IR generated is not compatible with our compiler which is based on llvm 4.0.  Can you confirm my understanding that you tried to build the builtins using Clang5.0?

**Comment by ArturHarasimiuk** [comment]
clang 5.0.1-2. maybe we should detect clang version and fail early if version is incorrect ?

**Comment by paigeale** [comment]
Thank you for the suggestion Artur. I filed an internal issue and will get back to you when it is addressed.

**Comment by paigeale** [comment]
Hello Artur. I made a change when loading the built-ins that gives an error message and fails gracefully when there is an incompatible version or malformed bitcode. Please see https://github.com/intel/intel-graphics-compiler/commit/15bb1245d4d26f118ca549c6b19dc218e8fb39fa for the changes.

**Comment by ArturHarasimiuk** [comment]
thanks!
