### ISSUE TITLE
please document Linux other than Ubuntu

### ISSUE THREAD

**Issue by jeffhammond** [intel/intel-graphics-compiler#101]
https://github.com/intel/intel-graphics-compiler/tree/master/documentation only includes information for Ubuntu.  Please document the build on CentOS 7 for our customers that use RHEL 7.  Thanks.

**Comment by tomdeakin** [comment]
We need this too. Alternatively, please just ship RPMs for your drivers as well as DEBs.

**Comment by JacekDanecki** [comment]
You can use rpm packages from [copr repository](https://copr.fedorainfracloud.org/coprs/jdanecki/intel-opencl). They are created also for Centos 7.7 and work on RHEL 7. opencl-clang library is part of igc build and is included in intel-igc-opencl package.

**Comment by paigeale** [comment]
@jeffhammond,

Is pointing the customers to the copr repository good enough? An example of the .spec is located here https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/mageia-7-x86_64/01060291-intel-igc/igc.spec

**Comment by JacekDanecki** [comment]
You can find specs I'm using on copr in [this repo](https://github.com/JacekDanecki/neo-specs)

**Comment by jeffhammond** [comment]
Yeah, I think this is sufficient.
