### ISSUE TITLE
Building IGC using CMAKE

### ISSUE THREAD

**Issue by downor** [intel/intel-graphics-compiler#104]
I used the instruction at 
https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md

When I ran cmake ../igc/IGC first time, I see this error:

-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
[check-igc] LIT tests disabled. Missing igc_opt target.
-- Configuring done
CMake Error at /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/cmake/modules/AddLLVM.cmake:457 (add_library):
  Cannot find source file:

    SPIRVToOCL.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/cmake/modules/AddLLVM.cmake:628 (llvm_add_library)
  /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/projects/llvm-spirv/lib/SPIRV/CMakeLists.txt:6 (add_llvm_library)

CMake Error at /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/cmake/modules/AddLLVM.cmake:457 (add_library):
  No SOURCES given to target: LLVMSPIRVLib
Call Stack (most recent call first):
  /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/cmake/modules/AddLLVM.cmake:628 (llvm_add_library)
  /home/dongwonk/mnt/nvme-1024GB/neo-opensource/intel-graphics-compiler/workspace/build/llvm/src/projects/llvm-spirv/lib/SPIRV/CMakeLists.txt:6 (add_llvm_library)

Then tried again (cmake ../igc/IGC), it is configured correctly and I could run make afterwards.

Is this a known issue? Is there any easier way to build IGC?

**Comment by mprogram** [comment]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator is the authoritative source for https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/master/lib/SPIRVSPIRVToOCL.cpp

**Comment by downor** [comment]
Hi, I know the file is there but my question is more about the build procedure in the instruction. I see that it stops with that error first when I run cmake. Then it works again if I run the same cmake again.

**Comment by lwesiers** [comment]
Hello there,

Could you please share more information about your setup which are you using? 
(distro, code version, cmake version and etc.)

Also full logs from cmake call will be nice, the first execution with error and the second one without issue (you can send it to me via mail).
