### ISSUE TITLE
Build IGC with prebuilt LLVM

### ISSUE THREAD

**Issue by downor** [intel/intel-graphics-compiler#110]
Is there any detailed instruction of building IGC with prebuilt LLVM libs?
I actually tried it by myself as followed.

1. Downloaded clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz and copied everything in this tarball to under /usr
2. Cloned llvm-spirv and built it with default CMAKE configuration and install libLLVMSPIRVLib.a
3. Cloned opencl-clang and built it with default CMAKE configuration but here I get some error like,[  7%] Built target opencl.headers.target
[ 23%] Built target linux_resource_linker
[ 46%] Built target cl_headers
[ 53%] Built target CClangCompileOptions
[ 61%] Linking CXX shared library libopencl-clang.so

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/libLLVMSPIRVLib.a(SPIRVWriter.cpp.o): relocation R_X86_64_PC32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/opencl-clang.dir/build.make:339: libopencl-clang.so.8] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/opencl-clang.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Is there any advice on how to resolve this compilation problem?

**Comment by paigeale** [comment]
Hello @downor,

If you look at the travis.yml file you can see the build steps for Ubuntu 16.04. 
See builds here .... https://travis-ci.com/intel/intel-graphics-compiler

Follow the build steps in Travis yml but instead of downloading the 16.04 llvm packages use the llvm-toolchain-bionic-8 package.

Thanks,
Alex

**Comment by paigeale** [comment]
Forgot to include link to .yml file [https://github.com/intel/intel-graphics-compiler/blob/master/.travis.yml](url)

**Comment by paigeale** [comment]
Hello @downor,

Any success with building IGC with prebuilts?

**Comment by downor** [comment]
Yeah, it works. Thanks for your help!!
