### ISSUE TITLE
Build fails with llvm9/clang9

### ISSUE THREAD

**Issue by saininav** [intel/intel-graphics-compiler#111]
Followed given configuration at:
https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md#llvm9clang9

Error log:

 /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1155:12: error: use of undeclared identifier 'get'; did you mean 'std::get'?
|     return get<SPIRVFunction>(FunctionId);
|            ^~~
|            std::get
| /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/utility:147:5: note: 'std::get' declared here
|     get(std::pair<_Tp1, _Tp2>& __in) noexcept
|     ^
| In file included from /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/SPIRVUtil.cpp:77:
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1155:12: error: no matching function for call to 'get'
|     return get<SPIRVFunction>(FunctionId);
|            ^~~~~~~~~~~~~~~~~~
| /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/utility:147:5: note: candidate template ignored: invalid explicitly-specified argument for template parameter '_Int'
|     get(std::pair<_Tp1, _Tp2>& __in) noexcept
|     ^
| In file included from /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/SPIRVUtil.cpp:77:
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1157:3: error: use of undeclared identifier 'getDecoder'
|   _SPIRV_DEF_DEC4(Type, Id, FunctionId, Args)
|   ^
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVEntry.h:133:36: note: expanded from macro '_SPIRV_DEF_DEC4'
|     void decode(std::istream &I) { getDecoder(I) >> x >> y >> z >> u;}
|                                    ^
| In file included from /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/SPIRVUtil.cpp:77:
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1157:19: error: use of undeclared identifier 'Type'
|   _SPIRV_DEF_DEC4(Type, Id, FunctionId, Args)
|                   ^
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1157:25: error: unexpected type name 'Id': expected expression
|   _SPIRV_DEF_DEC4(Type, Id, FunctionId, Args)
|                         ^
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1157:41: error: use of undeclared identifier 'Args'
|   _SPIRV_DEF_DEC4(Type, Id, FunctionId, Args)
|                                         ^
| /data/saininav/work/workspace/poky/build-opencl/tmp/work/x86_64-linux/intel-graphics-compiler-native/1.0.10-r0/git/IGC/AdaptorOCL/SPIRV/libSPIRV/SPIRVInstruction.h:1174:25: error: only virtual member functions can be marked 'override'
|   void validate() const override;

**Comment by lwesiers** [comment]
Hello there,

I was able to build compiler with latest for all repos:
igc : 870c0163
llvm-patches : 9b0bb48
llvm-project : 5fc03679c9d
llvm-spirv : beaa885
opencl-clang : 6f8c329

Could you share your workspace setup (git hash and etc.) ?

**Comment by saininav** [comment]
I forgot one thing to mention that, I am building clang compiler (not with gcc).

I am using exact these git hash:


    https://github.com/intel/intel-graphics-compiler/commit/6c0df5ac943c94303912c91d55a7e1818fc265c7
    https://github.com/intel/llvm-patches/commit/3906cc086f675847ca99b08107d18e083803d53c
    https://github.com/llvm/llvm-project/commit/fa0bc006900f17df3c11a40a3eb69e6330433b0e
    https://github.com/intel/opencl-clang/commit/6f8c329bea44321aef1a1716dd206c1f7bed23cf
    https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/beaa8850f47d2b436917881c1de19f3427629b89

**Comment by lwesiers** [comment]
It should be fixed with this commit-id a332238b46e9fa9e06265d18eb877d095015e6fb
