### ISSUE TITLE
Possible issue regarding barriers 

### ISSUE THREAD

**Issue by jjfumero** [intel/intel-graphics-compiler#114]
_Note: issue moved from https://github.com/intel/compute-runtime/issues/221_ 

Since the last driver update from CentOS 7, I detected a problem regarding reductions in OpenCL. I suspect the problem is related to the barrier implementation. 

I will try to describe the problem, but I could not create a simple test-case to show this since I generate parallel reductions from an SSA-IR (GraalIR) to OpenCL [1]. Just for completeness, this is the OpenCL kernel I am running: [link](https://gist.github.com/jjfumero/fd5fa1e9112fad7e674fa27df97b3968).

My goal here is to ask if you have detected/changed something related to the barriers implementation? It is a bug in the OpenCL driver? is there any work-around? 

#### Some details:
By using the following Intel Graphics Driver:

```bash
  Name:					Intel(R) Gen9 HD Graphics NEO
  Vendor:					 Intel(R) Corporation
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 19.34.13959
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.1 NEO 
```

give me wrong results (not all the time though) when computing reductions in OpenCL. Since the result is not deterministic, I think the problem is related to the barriers. **However, this kernel used to work properly using an older driver version:**

```bash
  Name:					Intel(R) Gen9 HD Graphics NEO
  Vendor:					 Intel(R) Corporation
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 19.23.13131
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.1 NEO 
```

#### Links

[1] https://github.com/beehive-lab/TornadoVM

**Comment by paigeale** [comment]
Hello Juan,

We will take a look at this internally and get back to you shortly. Thank you for you patience. 

-Alex

**Comment by paigeale** [comment]
Hey Juan,

Did some investigation and can confirm that it is not a compiler issue. I compared the outputted binaries from the reduction.cl kernel and they are the same between the two drivers you sent me. So no differences in the barrier implementation. Appears your problem may be a driver issue after all
