### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/intel-graphics-compiler#117]
Stream is opened
https://github.com/intel/intel-graphics-compiler/blob/d28eec1fb211ede77d80a97b775b0eb2befbdd36/visa/BuildCISAIRImpl.cpp#L694

Opened file never closed
https://github.com/intel/intel-graphics-compiler/blob/d28eec1fb211ede77d80a97b775b0eb2befbdd36/visa/BuildCISAIRImpl.cpp#L701

**Comment by lwesiers** [comment]
Thanks for catching this! The fix is on the way to github.
