### ISSUE TITLE
Outdated steps in build instructions

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/intel-graphics-compiler#12]
Hi,

I would like to notice you that one step in build instructions is outdated:
```
$ cp -a OpenCL-Headers/opencl22 opencl_headers
```

Accroding to KhronosGroup/OpenCL-Headers@de26592167b9fdea503885e40e8755393c56523d `opencl22` directory is gone

**Comment by pguo-igc** [comment]
Thank you for catching it.  We will update the build instructions in README.md soon.
