### ISSUE TITLE
Clang builds in TravisCI still use GCC

### ISSUE THREAD

**Issue by jbeich** [intel/intel-graphics-compiler#121]
From 9a53f2f [build log](https://api.travis-ci.org/v3/job/639606618/log.txt):
```
$ export LLVM_VER=9
$ export BUILD_TYPE=Release
$ export COMPILER=clang
[...]
$ cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_FIND_DEBUG_MODE=ON -DIGC_PREFERRED_LLVM_VERSION=${LLVM_VER} -DCCLANG_FROM_SYSTEM=TRUE ../IGC
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
[...]
```

**Comment by dvrogozh** [comment]
Shouldn't compiler be specified in either of 2 ways?
* CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, CMAKE_ASM_COMPILER
* CC, CXX, ASM

Do these ways work?

**Comment by jbeich** [comment]
> - CC, CXX, ASM

AS, not ASM. Besides, Clang doesn't have a standalone assembler.

> Do these ways work?

Yep but I'm not familar with TravisCI (no FreeBSD support -> not interested) or how various Linux distributions name Clang executable (e.g., clang9, clang-9, clang-9.0, clang90)

**Comment by pszymich** [comment]
Hi @jbeich,

We stopped building on TravisCI some time ago, so I'm gonna close this one. Thanks.
