### ISSUE TITLE
IGC stopped compiling on Fedora 32

### ISSUE THREAD

**Issue by JacekDanecki** [intel/intel-graphics-compiler#130]
IGC stopped to compile on fedora:
 * 32: https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl-ci/fedora-32-x86_64/01330622-intel-igc/builder-live.log.gz
* rawhide: https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl-ci/fedora-rawhide-x86_64/01330622-intel-igc/builder-live.log.gz

IGC can be compiled with:
* gcc (GCC) 10.0.1 20200216 (Red Hat 10.0.1-0.8)

Fails with:
* gcc (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)

**Comment by lwesiers** [comment]
Fixed with a58dd6de4c29595a0f93cff167b487d777e4559e
