### ISSUE TITLE
disassembler for GEN

### ISSUE THREAD

**Issue by wangliwei-intel** [intel/intel-graphics-compiler#134]
Hi,
I want to check the assembly code of my kernel,
Does IGC have a disassembler tool?
Thanks.

**Comment by pszymich** [comment]
Hello Liwei,

You can use configuration flags IGC_ShaderDumpEnable and IGC_ShaderDumpEnableAll to have IGC dump compilation passes including assembly code. You can learn more here: https://github.com/intel/intel-graphics-compiler/blob/master/documentation/configuration_flags.md

Does this help you?

**Comment by wangliwei-intel** [comment]
Hi, Pawel,
I tried, but I failed.

What I did:
cd igc/build
export IGC_ShaderDumpEnable=1
export IGC_ShaderDumpEnableAll=1
cmake ../igc/IGC/
make -j24
sudo make install

Then I compiled my apllication against NEO:
clang  -Wall -ggdb3 -o add_numbers add_numbers.c   -lOpenCL
./add_numbers

Everything went well, but I didn't get assembly output.
Did I do anything wrong?

B. R.
Liwei Wang

**Comment by pszymich** [comment]
Unless IGC_DumpToCurrentDir or IGC_DumpToCustomDir is defined in the environment IGC will produce dumps in the default, `/tmp/IntelIGC` directory. Did you check for the dumps there?

**Comment by wangliwei-intel** [comment]
Hi, Pawel,
Can you point me to the relevant code, so I can print some logs there?

B. R.
Liwei Wang

**Comment by pszymich** [comment]
Do you mean code that is responsible for producing and writing the shader dumps? Can you specify a little bit more what you have in mind?

Have you found the shader dumps in the `/tmp/IntelIGC` directory?

**Comment by wangliwei-intel** [comment]
> Do you mean code that is responsible for producing and writing the shader dumps? Can you specify a little bit more what you have in mind?
Yes, I do.
> Have you found the shader dumps in the `/tmp/IntelIGC` directory?
No, I haven't.

**Comment by pszymich** [comment]
Call to the function that dumps the disassembled kernel is at the 535th line in file `./visa/Common_ISA_framework.cpp`:
```cpp
writeIsaAsmFile(asmName.str(), sstr.str());
```

It's rather unexpected that producing shader dumps did not work for you. If you decide to try again make sure that:
- appropriate configuration flags are present in the environment (IGC_ShaderDumpEnable=1 and/or IGC_ShaderDumpEnableAll=1) at the time of running the application that uses IGC,
- `/tmp` directory or directory specified by IGC_DumpToCustomDir is accessible for write by the application.

**Comment by wangliwei-intel** [comment]
Hi, Pawel,
Really appreciate the patience you had to me, I'll check my environment carefully, thank you!

B. R.
Liwei Wang

**Comment by pszymich** [comment]
When you've had a chance to try those please let me know here if you have any following questions, otherwise we'll close the issue. Thank you.
