### ISSUE TITLE
Build fail: IGC hard-codes LLVM path to /usr/local although system LLVM is specified

### ISSUE THREAD

**Issue by eero-t** [intel/intel-graphics-compiler#137]
In few last releases IGC regressed to using hard-coded /usr/local LLVM path although system LLVM (v10) exists, its use had been specified and there's no other LLVM version or sources available.  Build fails as result.

This is (finally) fixed in Git head, but I think this bug could be kept open until you have a release with the fix so that others bumping into this issue find it easier: https://github.com/intel/intel-graphics-compiler/commit/6b74329f971

I would suggest using some container in CI with system LLVM to trivially prevent regressions like this.  It could also use read only repos and separate build root, to catch violations of other things distros care about.

**Comment by paigeale** [comment]
Latest Release igc-1.0.4053 has the fix
