### ISSUE TITLE
ocloc return 1 or 245

### ISSUE THREAD

**Issue by ywang30intel** [intel/intel-graphics-compiler#139]
I'm trying to build the spirv with ocloc. I have more than 6000 spirv kernels and about 10% were failed.
ocloc returns 1 or 245 error code and no any other messages were emitted.
I'm not sure if there any problems in the spriv IR code or something wrong in ocloc.
Is there any way to print more information/logs from the ocloc compile?
Thanks.
-Yang

**Comment by pszymich** [comment]
Hello,

The ocloc tool is maintained in the compute runtime repository, not in IGC.
Questions regarding its usage please direct here: [Intel(R) Graphics Compute Runtime](https://github.com/intel/compute-runtime).
