### ISSUE TITLE
Missing load regrouping optimization when pointer is modified

### ISSUE THREAD

**Issue by axeldavy** [intel/intel-graphics-compiler#14]
I have the following code
```
__kernel void compute_nearest_neighboors_naive(__global float * restrict dst,
                                               __global const SRC_TYPE * restrict src,
                                               int w,
                                               int h,
                                               int items_row,
                                               int items_img,
                                               int src_offset,
                                               int dst_offset)
{
    ...
    __global const SRC_TYPE * restrict src_shifted = src + src_offset + dz * items_img;
    ...
    #pragma unroll
    for (int i = 0; i < 8; i++) {
        float data = src_shifted[position+i];
        ....//something with data
    }
    ...
}
```

Ideally, the unrolling should cause into the send operations merging into two RGBA send operations.
Unfortunately with the above code, this doesn't happen: the unrolled code has 8 send operations.

However if data is loaded with the following line:
`float data = src[src_offset + dz * items_img + position+i];`

Then the optimization occurs and performance is much greater.

Expected behaviour: Both code should generate the optimization.

I can send code if requested, but I guess this issue should be reproducible with a small kernel and you may want to write such a kernel for your regression tests anyway.

I use release 18.26.10987

**Comment by paigeale** [comment]
Hello Axel. Could you please provide a reproducer. With this snippet of code we are seeing 8 reads in both instances.

**Comment by axeldavy** [comment]
Ok, I've just sent you a test by mail.

**Comment by paigeale** [comment]
Hi Axel. I am able to reproduce the issue that you have reported. I can see the loads are not being merged. I will notify you when we have a fix.

**Comment by axeldavy** [comment]
I see, thus it all comes down to the fact the pointers are 64 bits and the offsets 32 bits.

There is a more global issue about the mixing of the two unfortunately.
Among all three vendors, the following code is slower in a loop than the second:

```
__global float *src;
...
a = src[position];
```

```
__global float *src;
...
a = *((__global float *) ((__global uchar *)src + 4*position);
```
I suspect in the former case, position has to be promoted to int64 and then multiplied by 4, whereas in the second case 4*position is int32, which enables optimizations in loops (replacing multiplications with counters and additions).
I'm surprised there aren't more warnings about that in OpenCL guides.

In the case of this bug report though, even with 64 bits pointers vs 32bit ints, the loads should be merged.

**Comment by axeldavy** [comment]
I confirm this is fixed. Thanks !
