### ISSUE TITLE
Build failure for SPIRVDLL external project when not using make

### ISSUE THREAD

**Issue by maleadt** [intel/intel-graphics-compiler#145]
The `SPIRVDLL_EX` target is broken when not using `make`:

```
[1014/1017] Performing configure step for 'SPIRVDLL_EX'
Re-run cmake no build system arguments
-- The CXX compiler identification is GNU 8.1.0
-- Check for working CXX compiler: /opt/bin/c++
-- Check for working CXX compiler: /opt/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Linker detection: unknown
-- Found LLVM: 10.0.0
-- Found ccache: /usr/bin/ccache
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/srcdir/intel-graphics-compiler/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build
[1015/1017] Performing build step for 'SPIRVDLL_EX'
FAILED: IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-stamp/SPIRVDLL_EX-build 
cd /workspace/srcdir/intel-graphics-compiler/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build && /usr/bin/make SPIRVDLL && /usr/bin/cmake -E touch /workspace/srcdir/intel-graphics-compiler/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-stamp/SPIRVDLL_EX-build
make: *** No rule to make target 'SPIRVDLL'.  Stop.
ninja: build stopped: subcommand failed.
```

This is wrong: https://github.com/intel/intel-graphics-compiler/blob/92b475c5dddb9906f9125d42d80f1a5b81b74ea8/IGC/VectorCompiler/cmake/spirv.cmake#L82

Instead, it should probably use `CMAKE_MAKE_PROGRAM`.

**Comment by tgurr** [comment]
I run into the same error, I tried some things but I'm not an CMake expert, @maleadt do you have a patch incorporating your suggestion that I could try?

**Comment by tgurr** [comment]
@agrachiv Any details or commit id? According to git history spirv.cmake hasn't been touched for 2 months.

**Comment by agrachiv** [comment]
> @agrachiv Any details or commit id? According to git history spirv.cmake hasn't been touched for 2 months.

Here it is https://github.com/intel/intel-graphics-compiler/commit/6c16df3c52aa65396ca3c90bbc1d8607e4c8f847

**Comment by Bidski** [comment]
I get this error when using both `ninja` and `make` using release 1.0.5176 (along with system LLVM/Clang 10.0.1 and LLVM-SPIRV-Translator release 10.0.0)

**Comment by agrachiv** [comment]
Just successfully built igc, using ninja.

`[3337/3337] Completed 'SPIRVDLL_EX'`
