### ISSUE TITLE
Build failure for SPIRVDLL external project

### ISSUE THREAD

**Issue by tgurr** [intel/intel-graphics-compiler#149]
I didn't want to hijack https://github.com/intel/intel-graphics-compiler/issues/145 as I'm not sure if it's exactly the same problem I'm having, I've applied https://github.com/intel/intel-graphics-compiler/commit/6c16df3c52aa65396ca3c90bbc1d8607e4c8f847 which was mentioned in https://github.com/intel/intel-graphics-compiler/issues/145#issuecomment-693542465 but I still run into the error that SPIRVDLL can't be compiled, please see the two attached complete build log files, first one normal build and second one I tried switching to ninja.

```
[ 87%] Performing configure step for 'SPIRVDLL_EX'
cd /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build && /usr/x86_64-pc-linux-gnu/bin/cmake -DCMAKE_INSTALL_PREFIX=/var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/spirv-install -DLLVM_DIR=/usr/x86_64-pc-linux-gnu/lib/llvm/10/lib/cmake/llvm "-GUnix Makefiles" /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/llvm-spirv-vc
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Linker detection: unknown
-- Found LLVM: 10.0.1
-- Found ccache: /usr/bin/ccache
-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build
cd /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build && /usr/x86_64-pc-linux-gnu/bin/cmake -E touch /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-stamp/SPIRVDLL_EX-configure
[ 88%] Performing build step for 'SPIRVDLL_EX'
cd /var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build && /usr/bin/make SPIRVDLL
make[3]: Entering directory '/var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build'
make[3]: Leaving directory '/var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build/IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-build'
make[3]: *** No rule to make target 'SPIRVDLL'.  Stop.
make[2]: *** [IGC/VectorCompiler/CMakeFiles/SPIRVDLL_EX.dir/build.make:133: IGC/VectorCompiler/SPIRVDLL/src/SPIRVDLL_EX-stamp/SPIRVDLL_EX-build] Error 2
make[2]: Leaving directory '/var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/dev-util-intel-graphics-compiler-1.0.4944/work/build'
make[1]: *** [CMakeFiles/Makefile2:2060: IGC/VectorCompiler/CMakeFiles/SPIRVDLL_EX.dir/all] Error 2
make: *** [Makefile:174: all] Error 2
```

[intel-graphics-compiler-1.0.4944_make.log](https://github.com/intel/intel-graphics-compiler/files/5238184/intel-graphics-compiler-1.0.4944_make.log)
[intel-graphics-compiler-1.0.4944_ninja.log](https://github.com/intel/intel-graphics-compiler/files/5238186/intel-graphics-compiler-1.0.4944_ninja.log)

**Comment by tgurr** [comment]
Turned out that using an archive tarball of SPIRV-LLVM-Translator doesn't work. No idea why but since the whole build process seems to rely on a git repository also to do the additional patching I've migrated our build scripts to use git checkouts instead. When using a git repository instead of the archive tarball it (currently) seems to build fine.

**Comment by eero-t** [comment]
Is it trying to dig tags out of it / will your builds work also if you get your git clone with "--depth 1" git option?

And anyway, building things for tarballs should also work, so I think it would be better to keep this open until that is actually fixed...
