### ISSUE TITLE
Add way to control SIMD width

### ISSUE THREAD

**Issue by axeldavy** [intel/intel-graphics-compiler#15]
For some reasons, a few changes in my kernels can lead the compiler to pick a different choice for SIMD width (8, 16 or 32).

For some reason I don't explain, some of my kernels using shared memory and barriers perform very significantly better (several times faster) when the selected SIMD width is 8.

Thus I'd like a way to enforce the choice of SIMD width of 8. (Also ideally compiler would make better choices).

Maybe make `__attribute__((vec_type_hint(float8)))` trigger SIMD-8 for example ?

**Comment by paigeale** [comment]
Hello Axel,

To force SIMD-8 please use the following attribute...

**__attribute__((intel_reqd_sub_group_size(8)))**

This should work for either of the three simd widths

**Comment by paigeale** [comment]
Correction:
__attribute__((intel_reqd_sub_group_size(16)))

**Comment by paigeale** [comment]
Hello Axel,

For forcing SIMD-8 please use the following attribute....
**\_\_attribute\_\_((intel_reqd_sub_group_size(8)))**

This works on any of the three SIMD sizes.

**Comment by axeldavy** [comment]
It works indeed, thank you !
