### ISSUE TITLE
Recent rebase do not have this commit in the master branch 3e7c8e95b48a4eb6637077c52ff253a37b5ea085

### ISSUE THREAD

**Issue by syazaath** [intel/intel-graphics-compiler#153]
Hi, 

I bumped in to an issue while building Yocto BSP which used this commit on meta-intel branch. 
3e7c8e95b48a4eb6637077c52ff253a37b5ea085. 

$ git ls-remote https://github.com/intel/intel-graphics-compiler.git | grep 3e7c8e95b48a4eb6637077c52ff253a37b5ea085
3e7c8e95b48a4eb6637077c52ff253a37b5ea085        refs/tags/igc-1.0.5176

**Comment by syazaath** [comment]
Hi pszymich, 

I think the issue appeared after it being rebased recently. But it was fixed a few days after. 
So, the commit appeared on the tag, but not on the master branch. I think some changes happen and the whole master got rebase with a different commit entirely. 

It's all working now. :)

**Comment by pszymich** [comment]
Hello syazaath,
Great to hear that you got it working!

Closing the issue as the author has resolved it.
