### ISSUE TITLE
reproducibility on copy_image3d_to_buffer_stateless_Gen12LPlp and scheduler_Gen12LPlp

### ISSUE THREAD

**Issue by cheeyanglee** [intel/intel-graphics-compiler#161]
Facing reproducibility issue on copy_image3d_to_buffer_stateless_Gen12LPlp and scheduler_Gen12LPlp, while other build_ins can be reproduce, 

Attached diffoscope results [intel-compute-runtime-src.log](https://github.com/intel/compute-runtime/files/5128997/intel-compute-runtime-src.log)

**Comment by paigeale** [comment]
@cheeyanglee please reopen if issue persists on latest IGC
