### ISSUE TITLE
Disassembler Build Failed

### ISSUE THREAD

**Issue by phambinh** [intel/intel-graphics-compiler#167]
I am trying to build the disassembler, and it failed. Below are steps to reproduce:
cd intel-graphics-compiler/visa/iga
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
[ 29%] Built target GEDLibrary
[ 30%] Building CXX object IGALibrary/CMakeFiles/IGA_OLIB.dir/Backend/GED/Decoder.cpp.o
In file included from /nfs_home/bqpham/tools/intel-graphics-compiler/visa/iga/IGALibrary/Backend/GED/Decoder.cpp:34:0:
/nfs_home/bqpham/tools/intel-graphics-compiler/visa/iga/IGALibrary/Backend/GED/../../IR/Messages.hpp: In constructor ‘constexpr iga::VectorMessageArgs::VectorMessageArgs()’:
/nfs_home/bqpham/tools/intel-graphics-compiler/visa/iga/IGALibrary/Backend/GED/../../IR/Messages.hpp:454:41: error: uninitialized member ‘iga::VectorMessageArgs::<anonymous>’ in ‘constexpr’ constructor
         constexpr VectorMessageArgs() { }
                                         ^
gmake[2]: *** [IGALibrary/CMakeFiles/IGA_OLIB.dir/Backend/GED/Decoder.cpp.o] Error 1
gmake[1]: *** [IGALibrary/CMakeFiles/IGA_OLIB.dir/all] Error 2
gmake: *** [all] Error 2

I also tried with an older release: igc_release_2019-03-12, and it didn't have this problem.

**Comment by trbauer** [comment]
Hello. Sorry about the delay (I just got notified about this).

Can you include your compiler version so we can try an reproduce the issue?

**Comment by paigeale** [comment]
@phambinh would you be able to provide more information here? We are internally trying to reproduce this issue.

**Comment by phambinh** [comment]
Hi, I just tried to reproduce the error again but I couldn't. This is perhaps because our compilers had been upgraded since the time I reported the issue. Currently I am using gcc 11.1.0 and I don't remember what was the version before unfortunately. We can close this issue. Thanks!
