### ISSUE TITLE
Build from sources fails due C++17 register storage class specifier deprecation

### ISSUE THREAD

**Issue by kurapov-peter** [intel/intel-graphics-compiler#168]
Hi! I tried building from sources as described in https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md#build-from-sources and got an error: `ISO C++17 does not allow ‘register’ storage class specifier`

There're multiple keyword usage, ie.`register int number_to_move = yy_n_chars + 2;`
`#define register` - at least compiles for me with clang-10, ubuntu20 with no changes to the build steps described by the link.
Are there any specific compilation flags missing (I only set cmake build type)?

**Comment by pszymich** [comment]
Hello Peter,

I scanned through IGC sources with `^\s*register\s` regex and failed to find any occurrences that could cause problems. Neither can I find `register int number_to_move`, it seems that the keyword was removed already. Additionally the code you're referring to is in IGA, which builds with C++14 standard (as per CMakeLists.txt configuration).
We haven't recorded any issues recently with `register` keyword when verifying IGC internally.

Can you check if the problem still occurs with the latest IGC release? Please make sure you set up the build correctly, CMake should configure IGA to build with C++14 (`visa/iga/CMakeLists.txt:13:set (CMAKE_CXX_STANDARD 14)`).

**Comment by kurapov-peter** [comment]
Hi,

Those declarations were generated during the build (i.e. build/igc/IGC/visa/lex.CISA.cpp). The problem used to exist for igc-1.0.5964. Doesn't seem to be an issue for latest IGC.

Thanks,
Petr

**Comment by pszymich** [comment]
Hi Peter,

Thank you for the feedback!
Please don't hesitate to contact us if you have any more questions or issues.

***

Closing due to the issue being resolved.
