### ISSUE TITLE
NEO/Win10 performance regression from .6025 onward including today's .6194

### ISSUE THREAD

**Issue by allanmac** [intel/intel-graphics-compiler#17]
Every NEO/Win10 driver post .6025 exhibits the same regression (huge spillage).

As noted [here](https://software.intel.com/en-us/forums/opencl/topic/779490), .6025 works perfectly.

All kernels listed here are decorated with a reqd_subroup_size(8) and compiled with `ioc64`.

Let me know who I can send the kernels to.

![spillage](https://user-images.githubusercontent.com/144247/42647623-5c5815ee-85b9-11e8-999c-4f56e5305f10.png)

**Comment by paigeale** [comment]
Hello Allan,

Thank you for making us aware of this potential regression. Please send your kernels to my email (listed in my profile) with a detailed description on how to reproduce. Our compiler team will take a look and see if we can reproduce this behavior and provide a fix.

-Alex

**Comment by allanmac** [comment]
Thanks, sent!

**Comment by paigeale** [comment]
The commit attached (1451db9e994c6669fa3b0be06695498f19be9f9b) removes the spills you were seeing post .6025. Please verify and close.

**Comment by allanmac** [comment]
Thanks, I will confirm as soon as the next [compute runtime release](https://github.com/intel/compute-runtime/releases) appears.

**Comment by paigeale** [comment]
Hello Allan,
Could you please verify that the latest compute runtime release solved your spill issues. This issue is fairly old and I would like to close this issue if it is no longer relevant.
