### ISSUE TITLE
FTBFS: "vc-intrinsics/GenXIntrinsics" directory not found

### ISSUE THREAD

**Issue by thiagomacieira** [intel/intel-graphics-compiler#176]
IGC 1.0.7041

CMake args: `-G 'Unix Makefiles' -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SBINDIR=/usr/bin -DCMAKE_INSTALL_LIBDIR=/usr/lib64 -DLIB_INSTALL_DIR=/usr/lib64 -DLIB_SUFFIX=64 -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib ..`

Build output:
```
-- [VC] Using vc-intrinsics source from: /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.7041/IGC/VectorCompiler/../../../vc-intrinsics/GenXIntrinsics
CMake Error at IGC/VectorCompiler/CMakeLists.txt:107 (add_subdirectory):
  add_subdirectory given source
  "/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.7041/IGC/VectorCompiler/../../../vc-intrinsics/GenXIntrinsics"
  which is not an existing directory.
```

That directory is above the top source dir of the package, therefore nonsensical.

It seems to be a dependency on https://github.com/intel/vc-intrinsics, but that project has never made a release.

Please fix.

**Comment by thiagomacieira** [comment]
Probably same as #142

**Comment by ArchangeGabriel** [comment]
You need a checkout of vc-intrinsics using the expected commit indeed. See our [Arch Linux recipe](https://github.com/archlinux/svntogit-community/blob/packages/intel-graphics-compiler/trunk/PKGBUILD) for instance.

**Comment by thiagomacieira** [comment]
I've worked around like you did, but that's not proper solution. The vc-intrinsics package needs a tag and a proper dependency check in igc's build. If a system-wide install does not make sense, then the sources should be bundled together, either inside or in the release page like LLVM does.

The bug still applies: the build fails due to lack of information.

**Comment by ArchangeGabriel** [comment]
Well, you have already found #142 which also links to https://github.com/intel/vc-intrinsics/issues/36. I don’t see what can be added here…

**Comment by thiagomacieira** [comment]
Same as #142
