### ISSUE TITLE
FTBFS: "Cannot find SPIRVDLL sources"

### ISSUE THREAD

**Issue by thiagomacieira** [intel/intel-graphics-compiler#177]
Version: 1.0.7041

CMake args: `-G 'Unix Makefiles' -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SBINDIR=/usr/bin -DCMAKE_INSTALL_LIBDIR=/usr/lib64 -DLIB_INSTALL_DIR=/usr/lib64 -DLIB_SUFFIX=64 -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib .. -DIGC_OPTION__LLVM_PREFERRED_VERSION=11.1.0`

CMake output:
```
-- [VC] SPIRVDLL_SRC = 
-- [VC] SPIRV_SRC = 
-- [VC] Cannot find SPIRVDLL sources in /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.7041/IGC/VectorCompiler/../../../llvm-project/llvm/projects/llvm-spirv
CMake Error at IGC/VectorCompiler/cmake/spirv.cmake:152 (message):
  [VC] Cannot find SPIRVDLL sources in
  /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.7041/IGC/VectorCompiler/../../../llvm-spirv
Call Stack (most recent call first):
  IGC/VectorCompiler/CMakeLists.txt:109 (include)
```

SPIR-V translator is installed in the system.
```
$ ls -l /usr/lib64/libLLVMSPIRVLib.a 
-rw-r--r-- 1 root root 156281846 Apr 19 15:49 /usr/lib64/libLLVMSPIRVLib.a
$ ls -l /usr/include/LLVMSPIRVLib/
total 24
-rw-r--r-- 1 root root 1066 Apr 19 15:49 LLVMSPIRVExtensions.inc
-rw-r--r-- 1 root root 8860 Apr 19 15:49 LLVMSPIRVLib.h
-rw-r--r-- 1 root root 7393 Apr 19 15:49 LLVMSPIRVOpts.h
```

**Comment by thiagomacieira** [comment]
Probably same as #148

**Comment by ArchangeGabriel** [comment]
You need to pass `-DINSTALL_SPIRVDLL=0` if using system LLVMSPIRV.

**Comment by ArchangeGabriel** [comment]
(That is if you want to compile the version I indicated as being compatible with LLVM 11, for newer ones that should be `DIGC_OPTION__LLVM_FROM_SYSTEM=ON`).

**Comment by thiagomacieira** [comment]
Thanks, that option worked.

This bug or #148 still applies: the build fails with default options. Since LLVMSPIRV is installed system-wide, igc should detect it and use it without being prompted to.

**Comment by ArchangeGabriel** [comment]
Not something they (this upstream) care about. They have [their instructions](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md) and that is what is supported. I’m already glad they actually provide a way to use a system SPIRVLLVM.

Anyway, as you have seen this is already #148. ;)

**Comment by thiagomacieira** [comment]
Same as #148.
