### ISSUE TITLE
No policy on commit messages

### ISSUE THREAD

**Issue by tjaalton** [intel/intel-graphics-compiler#182]
Looks like the situation has not improved since I packaged this for Debian, so here goes:

- commit messages should have a short headline, and bulk explanation separated by an empty line.. instead we have unreadable blurbs that make git shortlog (like with log --abbrev-commit --abbrev=15 --pretty=oneline) useless
- commits are allowed without any actual explanation.. there are tons of commits with the message just 'Changes in code', 'Internal change' etc

please enforce basic rules to follow before allowing to merge commits that, quite frankly, make this project look less serious

**Comment by paigeale** [comment]
@tjaalton,

Thank you for this suggestion we are working internally on fixing these two points.

**Comment by paigeale** [comment]
Marking this as resolved since we cleaned up our commit messages to address the two points here.
