### ISSUE TITLE
Gentoo build - /usr/lib64/liblldELF.so: error adding symbols: file in wrong format 

### ISSUE THREAD

**Issue by CH3CN** [intel/intel-graphics-compiler#187]
I'm trying to build the latest release of intel-graphics-compiler (1.0.7862) on Gentoo but I am having some difficulties and I'm too inexperienced to figure this out. The ebuilds for intel-graphics-compiler and intel-neo in Gentoo are unmaintained so I've been working on my own local overlay. The last version of the igc I was able to build was 1.0.6083.

I made sure i have the appropriate commits for the dependencies (opencl-clang, SPIRV-LLVM-Translator, vc-intrinsics) and I have been able to get them to build, compile and install fine. igc fails at this point:

`[300/650] : && /usr/bin/x86_64-pc-linux-gnu-g++ -m32 -march=native -pipe -fno-exceptions -fdata-sections -ffunction-sections -fmessage-length=0 -march=corei7 -mstackrealign -fms-extensions -Wno-unused-parameter -Wno-missing-field-initializers -Wwrite-strings -Wno-long-long -Wswitch -Wno-sign-compare -Wno-unused-result -Wno-enum-compare -Wno-type-limits -Wno-ignored-qualifiers -Wno-shadow -Wformat -Wformat-security -Wno-extra -Wno-write-strings -finline -fno-strict-aliasing -msse -msse2 -msse3 -mssse3 -msse4 -msse4.1 -msse4.2 -Wno-unknown-pragmas -fPIC -finline-functions -funswitch-loops -Wno-maybe-uninitialized -lrt -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -g -Os -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections IGC/ElfPackager/CMakeFiles/elf_packager.dir/main.cpp.o IGC/ElfPackager/CMakeFiles/elf_packager.dir/__/AdaptorOCL/CLElfLib/ElfWriter.cpp.o IGC/ElfPackager/CMakeFiles/elf_packager.dir/__/AdaptorOCL/CLElfLib/ElfReader.cpp.o -o IGC/Gentoo/elf_packager  -Wl,-rpath,/usr/lib/llvm/10/lib  /usr/lib64/liblldELF.so  /usr/lib64/liblldCommon.so  /usr/lib/llvm/10/lib/libLLVM-10.so && cd /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/ElfPackager && /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/elf_packager -includeSizet -funcList /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-igc-1.0.7862/IGC/ElfPackager/function_bin.txt /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/bif//OCLBiFImpl.bc /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/bif//igdclbif.bin
FAILED: IGC/Gentoo/elf_packager 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -m32 -march=native -pipe -fno-exceptions -fdata-sections -ffunction-sections -fmessage-length=0 -march=corei7 -mstackrealign -fms-extensions -Wno-unused-parameter -Wno-missing-field-initializers -Wwrite-strings -Wno-long-long -Wswitch -Wno-sign-compare -Wno-unused-result -Wno-enum-compare -Wno-type-limits -Wno-ignored-qualifiers -Wno-shadow -Wformat -Wformat-security -Wno-extra -Wno-write-strings -finline -fno-strict-aliasing -msse -msse2 -msse3 -mssse3 -msse4 -msse4.1 -msse4.2 -Wno-unknown-pragmas -fPIC -finline-functions -funswitch-loops -Wno-maybe-uninitialized -lrt -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -g -Os -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections IGC/ElfPackager/CMakeFiles/elf_packager.dir/main.cpp.o IGC/ElfPackager/CMakeFiles/elf_packager.dir/__/AdaptorOCL/CLElfLib/ElfWriter.cpp.o IGC/ElfPackager/CMakeFiles/elf_packager.dir/__/AdaptorOCL/CLElfLib/ElfReader.cpp.o -o IGC/Gentoo/elf_packager  -Wl,-rpath,/usr/lib/llvm/10/lib  /usr/lib64/liblldELF.so  /usr/lib64/liblldCommon.so  /usr/lib/llvm/10/lib/libLLVM-10.so && cd /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/ElfPackager && /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/elf_packager -includeSizet -funcList /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-igc-1.0.7862/IGC/ElfPackager/function_bin.txt /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/bif//OCLBiFImpl.bc /var/tmp/portage/dev-util/intel-graphics-compiler-1.0.7862/work/intel-graphics-compiler-1.0.7862_build-abi_x86_32.x86/IGC/Gentoo/bif//igdclbif.bin
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/liblldELF.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status`

I'm thinking it's a 32-bit vs 64-bit file issue, and removing `/usr/lib64/liblldELF.so  /usr/lib64/liblldCommon.so` from the above section and running it from the command line compiles igdclbif.bin. Is this file supposed to be 32-bit?
`igdclbif.bin: ELF 64-bit LSB no file type, no machine, invalid version (SYSV)`

Can someone help me troubleshoot it?

**Comment by lwesiers** [comment]
Hello there,

I'm guessing that you are building here 32bit version of compiler?
intel-graphics-compiler-1.0.7862_build-abi_**_ x86_32_**.x86

Please try install 32bit version of lld libraries (if you don't have) and try fixed path for searching it by cmake parameter: **-DIGC_OPTION__LLDELF_LIB_DIR=/usr/lib32/**
 
and please let me know if this helps.

**Comment by CH3CN** [comment]
Hi Łukasz,

Thank you for responding. The ebuild I was using for Gentoo had the use flag set for abi_x86_32 in addition to 64. I am unable to build the 32 bit version of the lld libraries as [multilib support isn't available](https://wiki.gentoo.org/wiki/Project:LLVM/Multilib) for lld in Gentoo. So unsetting the abi_x86_32 use flag has enabled build and compilation without errors and OpenCL works fine according to the Intel OpenCL sample code I ran.

Thanks again for your help.
