### ISSUE TITLE
Intel Graphics Compiler Failed Build

### ISSUE THREAD

**Issue by gija92** [intel/intel-graphics-compiler#19]
Hello, 

I want to use the Intel Compute Runtime for OpenCL and now installing the dependencies gmmlib and the igc. GmmLib was successful but igc return errors while make [-j'nproc'], that ```llvm::SmallSet``` and ```llvm::AttributeSet``` are not declared but acutally can be found in the "workspace"-directory. 

![image](https://user-images.githubusercontent.com/41571607/43258436-1789dfc2-90d3-11e8-8c5e-5111d4475b21.png)

I'm following the constructions but don't know how to solve the problem.

For more Details:
I am using an Minnowboard Max with Intel Atom E3825 CPU and already installed LLVM/Clang 4.0. before I build the IGC

Hope some of you guys can help me

**Comment by astojano** [comment]
Hi,

Can you give more details of your system (OS, gcc version etc.)?

**Comment by gija92** [comment]
@astojano sure ^^
OS: Linux Ubuntu 16.04 (created with yocto project)
GCC: version 6.4.0
LLVM/Clang: 4.0
CPU: Intel Atom E3825 

Background: I want to set OpenCL driver for the Intel CPU and GPU for application which is based on OpenCL. Therfore the aim is to type command ```clinfo``` and see the CPU and GPU as OpenCL devices

Thanks

**Comment by astojano** [comment]
We'll try to reproduce and fix the problem, but for now we don't have your hardware so we focus on desktop PC.

Could you try to use previous version of GCC? We currently use GCC 5.4.0 on Ubuntu 16.04 in our CI system.

**Comment by gija92** [comment]
@astojano 
alright I will give it a try.
Thanks :)

**Comment by iwwu** [comment]
Does older version of GCC work for you?

I downloaded latest code, but couldn't reproduce the issue on my system with Ubuntu 18.04 LTS, gcc 7.3.0. Do you see SmallSet code in llvm_source?

**Comment by gija92** [comment]
@iwwu 
I'm trying to re-install GCC 6.4..0 but failed so I now build a new Image with yocto and try it again.
I'm using a Yocto-Image for the Minnowboard with GCC 6.4.0. 

Just to avoid misunderstandings. Am I right that I have to follow the steps directly on the minnowboard?
Or can I build the "workspace" in Ubuntu 16.04 (virtualbox). and create a binary  which I can afterwards run on the board?

**Comment by astojano** [comment]
Give a try to older version of GCC like 5.4.0.

If you build a binary in appropriate architecture on virtual machine the binary should works fine on board.

**Comment by gija92** [comment]
@astojano 
Thanks I will try it. :)

**Comment by paigeale** [comment]
@gija92 Did this suggestion work. Can this issue be closed?

**Comment by gija92** [comment]
No unfortunately not. I installed a new ubuntu version instead of using a yocto image.
