### ISSUE TITLE
Compilation failure on 1.0.8173 with LLVM12

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/intel-graphics-compiler#191]
While I’ve been able to fix most issues w.r.t to compiling with LLVM12, there is one remaining:
```
/build/intel-graphics-compiler/src/intel-graphics-compiler-igc-1.0.8173/IGC/VectorCompiler/lib/GenXCodeGen/GenXThreadPrivateMemory.cpp: In member function ‘void {anonymous}::StackAnalysis::visitAllocaInst(llvm::AllocaInst&)’:
/build/intel-graphics-compiler/src/intel-graphics-compiler-igc-1.0.8173/IGC/VectorCompiler/lib/GenXCodeGen/GenXThreadPrivateMemory.cpp:143:61: error: conversion from ‘Optional<llvm::TypeSize>’ to non-scalar type ‘Optional<long unsigned int>’ requested                    
  143 |   Optional<uint64_t> AllocaSize = AI.getAllocationSizeInBits(m_DL);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```

**Comment by jbeich** [comment]
Does level-zero work for you? At least [ze_peak](https://github.com/oneapi-src/level-zero-tests/tree/master/perf_tests/ze_peak) fails here e.g.,
```
$ git clone https://github.com/oneapi-src/level-zero-tests
$ cd level-zero-tests/perf_tests/ze_peak
$ c++ -o ze_peak src/*.cpp -O2 -pipe -lze_loader
$ (cd kernels; ../ze_peak)
Device :
 * name : Intel(R) HD Graphics 530 [0x1912]
 * vendorId : 8086
 * deviceId : 1912
 * subdeviceId : 0
 * isSubdevice : FALSE
 * UUID : 00000000-0000-0000-0000-191200008086
 * coreClockRate : 47e

No async copy engines detected, disabling blitter benchmark
Pass 'Dead Code Elimination' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
Segmentation fault
(lldb) bt
* thread #1, name = 'ze_peak', stop reason = signal SIGSEGV: invalid address (fault address: 0x48)
  * frame #0: 0x0000000806798048 libLLVM-12.so`llvm::PMTopLevelManager::schedulePass(llvm::Pass*) + 472
    frame #1: 0x000000080c6e9ac6 libigc.so.1`IGC::IGCPassManager::add(this=0x00007fffffff7ed8, P=<unavailable>) at LLVMUtils.cpp:110:18
    frame #2: 0x000000080c768b63 libigc.so.1`IGC::CommonOCLBasedPasses(pContext=0x00007fffffff85b8, BuiltinGenericModule=llvm::Module @ 0x0000000801841c00, BuiltinSizeModule=llvm::Module @ 0x0000000801843100) at UnifyIROCL.cpp:271:13
    frame #3: 0x000000080c769e6b libigc.so.1`IGC::UnifyIRSPIR(pContext=0x00007fffffff85b8, BuiltinGenericModule=nullptr, BuiltinSizeModule=nullptr) at UnifyIROCL.cpp:565:5
    frame #4: 0x000000080c73f74e libigc.so.1`TC::TranslateBuild(pInputArgs=0x00007fffffff9108, pOutputArgs=0x00007fffffff90c0, inputDataFormatTemp=TB_DATA_FORMAT_SPIR_V, IGCPlatform=0x0000000801841c00, profilingTimerResolution=2.85131521E-30) at dllInterfaceCompute.cpp:1168:13
    frame #5: 0x000000080c8300bf libigc.so.1`IGC::IgcOclTranslationCtx<0ul>::Impl::Translate(this=0x00000008018bf9b0, outVersion=1, src=0x00000008018c2be0, specConstantsIds=0x00000008018c2c40, specConstantsValues=<unavailable>, options=<unavailable>, internalOptions=0x00000008018c2c20, tracingOptions=0x0000000000000000, tracingOptionsCount=0, gtPinInput=0x0000000000000000) const at igc_ocl_translation_ctx_impl.h:282:27
    frame #6: 0x000000080c82f39b libigc.so.1`IGC::IgcOclTranslationCtx<3ul>::TranslateImpl(this=<unavailable>, outVersion=<unavailable>, src=<unavailable>, specConstantsIds=<unavailable>, specConstantsValues=<unavailable>, options=<unavailable>, internalOptions=0x00000008018c2c20, tracingOptions=0x0000000000000000, tracingOptionsCount=0, gtPinInput=0x0000000000000000) at igc_ocl_translation_ctx_impl.cpp:54:29
    frame #7: 0x000000080143d748 libze_intel_gpu.so.1`NEO::CompilerInterface::build(NEO::Device const&, NEO::TranslationInput const&, NEO::TranslationOutput&) + 2728
    frame #8: 0x0000000801354dce libze_intel_gpu.so.1`L0::ModuleTranslationUnit::buildFromSpirV(char const*, unsigned int, char const*, char const*, _ze_module_constants_t const*) + 2158
    frame #9: 0x0000000801356ae0 libze_intel_gpu.so.1`L0::ModuleImp::initialize(_ze_module_desc_t const*, NEO::Device*) + 176
    frame #10: 0x0000000801358988 libze_intel_gpu.so.1`L0::Module::create(L0::Device*, _ze_module_desc_t const*, L0::ModuleBuildLog*, L0::ModuleType) + 88
    frame #11: 0x000000080134217f libze_intel_gpu.so.1`L0::DeviceImp::createModule(_ze_module_desc_t const*, _ze_module_handle_t**, _ze_module_build_log_handle_t**, L0::ModuleType) + 63
    frame #12: 0x000000000021f004 ze_peak`L0Context::create_module(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >) + 180
    frame #13: 0x000000000020dadc ze_peak`ZePeak::ze_peak_global_bw(L0Context&) + 236
    frame #14: 0x0000000000224708 ze_peak`main + 264
    frame #15: 0x0000000000209d50 ze_peak`_start(ap=<unavailable>, cleanup=<unavailable>) at crt1_c.c:73:7
```

**Comment by jbeich** [comment]
Note, the above crash is with Arch patches for LLVM 12. Without patches level-zero in igc-1.0.8173 works fine using LLVM 11.

**Comment by tjaalton** [comment]
surely you had to revert 32944e60e97f634fe975b9407e1f1d6b6510f93b first?

this is getting ridiculous, I haven't been able to update i-g-c in Debian/Ubuntu since 1.0.5353.1 and we're about to move to LLVM 13 next month.. next step would be to drop the package (and compute runtime) as they're getting useless

**Comment by ztuowen** [comment]
I've finally got igc and compute-runtime to compile on ArchLinux w. LLVM 12.0.1.

I've used the following patches, in this order:

1. [llvm12-porting.patch](https://github.com/archlinux/svntogit-community/blob/packages/intel-graphics-compiler/trunk/llvm12-porting.patch) from arch testing. 
2. 8e1a461d3e6
3. 42963623ea53f4cd77fc3dc9ca4c099c5f10f456
4. fd480731ad77213fbfcd9677d03e8243acbb306c

The compute-runtime compiles w. the instructions from the old [PKGBUILD](https://archlinux.org/packages/community/x86_64/intel-compute-runtime/) w. 21.31.20514.

Not sure if everything is correct, but at least I'm able to run some of my code with it.

**Comment by eero-t** [comment]
> this is getting ridiculous, I haven't been able to update i-g-c in Debian/Ubuntu since 1.0.5353.1 and we're about to move to LLVM 13 next month.. next step would be to drop the package (and compute runtime) as they're getting useless

Latest IGC & compute-runtime releases (from 1-2 week ago) build fine with latest Ubuntu (21.04) default LLVM v11 / opencl-clang etc, so at least they can be updated for 21.04, for better HW support.

Latest IGC release lists LLVM v12 fixes, so maybe it compiles now with that too  (I have not tested that myself though)?

Looking at Debian build, it seems to disable VC, but my guess is that there's much less much testing for builds without it, so I think VC should probably be enabled for the new builds...

**Comment by eero-t** [comment]
> Looking at Debian build, it seems to disable VC, but my guess is that there's much less much testing for builds without it, so I think VC should probably be enabled for the new builds...

According to LLVM version support status page: https://github.com/intel/intel-graphics-compiler/projects

VC enabled build fails with LLVM v12, they work only with LLVM v11.

**Comment by tjaalton** [comment]
yeah I didn't bother to package vc-intrinsics at the time, but uploaded it now.. will take some time to get through the NEW queue

**Comment by pszymich** [comment]
Hello,

We are aware of the problems with building IGC with LLVM >= 11. The LLVM 11 update in IGC has taken longer than expected mainly because we have always planned to provide a high quality build by means of thorough testing. We have just switched to LLVM 11 in the production environment.

With that being said we recognize our current methods are too slow for timely adoption of new LLVM versions. We have already assumed a different approach for LLVM 12 onward. We plan on introducing multiple LLVM versions support with a high quality production version to go along for which we guarantee a certain level of conformance & performance, and several with full build support minimum.

For specific LLVM versions support progress please refer to the newly created trackers here, as @eero-t mentioned: https://github.com/intel/intel-graphics-compiler/projects.

The original problem that @ArchangeGabriel reported has been fixed in commit https://github.com/intel/intel-graphics-compiler/commit/f5385b3899705929f2fdf32b6ba57763f6067f26, so I'm going to close this issue.

Thank you!
