### ISSUE TITLE
Build failure of 1.0.8365 with LLVM 13 on current meta-clang and meta-intel layers' master branches

### ISSUE THREAD

**Issue by zboszor** [intel/intel-graphics-compiler#193]
See https://github.com/YoeDistro/meta-intel/issues/3

**Comment by pszymich** [comment]
Hi @zboszor,

Build problems described in YoeDistro/meta-intel#3 should be resolved with latest changes to IGC including 0d561cc954841e5eadc4c60398e8a8207c25110b.

I'm closing this for now, please reopen or create a new issue if you come across other build problems.

Thanks!
