### ISSUE TITLE
OpenCL compiler issues for Intel 11th gen CPU?

### ISSUE THREAD

**Issue by vm3tr1c1** [intel/intel-graphics-compiler#195]
- opencv 3.4.15
- centos 7.9, kernel 5.13.5-1 with i915.force_probe=4c8a
- gcc 7.3.1
- CPU: i5-11600
- intel-opencl-21.28.20343-1.el7.x86_64

At the runtime of an opencv application which use the ocl4dnn module, a lot of 'simd size' errors are generated, like these ones:

OpenCV(ocl4dnn): The OpenCL compiler chose a simd size (16) that does not equal the size (8) kernel source required.
                 Skip this kernel U_GEMM_LIKE_CONV_k3x3_cn3_g1_s2x2_d1x1_b1_in256x256_p1x1_num1_M32_activ1_eltwise0_FP32_5_1_8_32_SIMD8
OpenCV(ocl4dnn): The OpenCL compiler chose a simd size (32) that does not equal the size (16) kernel source required.
                 Skip this kernel IDLF_k3x3_cn3_g1_s2x2_d1x1_b1_in256x256_p1x1_num1_M32_activ1_eltwise0_FP32_2_7_3_1_SIMD16

If the CPU is replaced with an i5-10600, without changing anything else, the errors disappear and the GPU code runs without any issue at all.

**Comment by alalek** [comment]
Can confirm the similar behavior for i7-11700K on Win10 with 27.20.100.9127 driver.
Will try to prepare minimal reproducer for this problem.

**Comment by alalek** [comment]
Investigation shows that there is incorrect condition in OpenCV code.
We should not use `clGetKernelWorkGroupInfo(CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE)` check in such strict way. It is a hint and it should not block kernels execution.
"Unblocked" kernels work fine without regressions.

This issue can be closed (no problem in IGC compiler).

**Comment by vm3tr1c1** [comment]
@alalek 
I can confirm that the OpenCV patch resolves the problem. Thank you!
