### ISSUE TITLE
Intended debug flow for libigc failures?

### ISSUE THREAD

**Issue by kurapov-peter** [intel/intel-graphics-compiler#206]
Hi, I'm using llvm 12 (built from sources) and Khronos SPIRV translator to generate IR (opencl-like) and then SPIRV for compute-runtime build and run. The flow works just fine when I use release packages, yet I'm facing failures in libigc sometimes.
I used to build debug versions of igc, neo and loader to track issues down, but updating components versions to latest release tags (and switch to llvm 11) yields assertion failure when dlopening libigc (my app first openats ze_loader, libLLVM-12 and then tries to dlopen libigc in runtime):

```
IGC/llvm-deps/src/llvm/include/llvm/Support/CommandLine.h:851: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::FunctionPass* (*)(); DataType = llvm::FunctionPass* (*)()]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.
```
 
I tried passing -fvisibility=hidden to my application with no luck and I don't dlopen the first instance of llvm (12) to make symbols local, for example.

Anything I'm missing here? Or is there an intended way for debugging issues with arbitrary code generation? The build log provided by the driver didn't help.

**Comment by eero-t** [comment]
Everything in the whole stack needs to  be using same LLVM + LLVM-SPIRV-Translator + OpenCL-Clang version. Otherwise things break subtly or not so subtly (as I found out in another bug).

**Comment by mnaczk** [comment]
As @eero-t mentioned IGC needs the same LLVM in the whole stack. If you use a different version of LLVM for different components of IGC, we can not guarantee that this will work, and we also cannot guarantee gentle failing. (LLVM per version has no compatible API) 
Do you use the same LLVM version in the whole stack?

**Comment by mnaczk** [comment]
I am closing the issue due to the lack of response from the submitter. @kurapov-peter If the problem still exists please reopen the issue
