### ISSUE TITLE
Compiler crashing on my OpenCL kernel

### ISSUE THREAD

**Issue by sudden6** [intel/intel-graphics-compiler#207]
I'm trying to build the kernel [clqueens.cl.txt](https://github.com/intel/compute-runtime/files/7332972/clqueens.cl.txt), but the Intel OpenCL compiler causes a segmentation fault, see [backtrace.txt](https://github.com/intel/compute-runtime/files/7332962/backtrace.txt)

Release is from: https://github.com/intel/compute-runtime/blob/master/opencl/doc/DISTRIBUTIONS.md#opensuse-leap-153 version 1.0.8708-1.suse.lp153

The kernel should be valid OpenCL C 2.0 and 3.0, the AMD OpenCL compiler based LLVM seems to have no issue with it. In case you find it invalid, I'd expect the compiler to reject the kernel with an error message and not crash.

**Comment by haonanya** [comment]
@sudden6 , could you please provide branch name and commits of opencl-clang, SPIRV-LLVM-Translator and llvm you are using? Thanks very much.

**Comment by sudden6** [comment]
SPIRV-LLVM Translator commit: 4d43f68a30a510b4e7607351caab3df8e7426a6b

opencl-clang Tag: 10.0.0-2

I'm not sure what LLVM commit is used in the package. I'd be also happy to hear if my code compiles on the newest master branches.

**Comment by haonanya** [comment]
Hi, @sudden6. When try to build IGC from source or prebuild, there are some build errors. Could you please kindly offer more details about IGC build since I am not familiar with the env setting on opensuse? 
The backtrace show that libopencl-clang.so.11 is used. I'd like to know:
1. Which build(source, prebuild) mode are we using? When build mode is prebuild, use llvm-11.0.0 it seems that there are build error when generating opencl-clang.dir/options.cpp.o with missing clang/Basic/OpenCLOptions.h. When build mode is source,  OpenCL 3.0 feature macro patch is not applied successfully.
2. Which branch for SPIRV-LLVM is using?

**Comment by sudden6** [comment]
@haonanya I don't really now the exact build setup, since I just installed the package that's linked in DISTRIBUTIONS.md

If you can confirm that the kernel successfully compiles on some other platform or with latest master I'd be happy to close this issue and try that platform.

**Comment by haonanya** [comment]
Hi, @sudden6. I am using llvm11.0.1, latest opencl-clang 11branch and SPIRV llvm_release_110 source build. I got the similar crash information:
`
[haonanya@shliclel311 33566]$ ../ocl-clang-110/build/bin/clang++  -cc1 -emit-llvm -triple spir-unknown-unknown -finclude-default-header -cl-std=CL3.0 clqueens.cl  -cl-ext=+__opencl_c_device_enqueue
clang++: /export/users/haonanya/ocl-clang-110/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::BlockExpr; Y = const clang::Expr; typename llvm::cast_retty<X, Y*>::ret_type = const clang::BlockExpr*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ../ocl-clang-110/build/bin/clang++ -cc1 -emit-llvm -triple spir-unknown-unknown -finclude-default-header -cl-std=CL3.0 clqueens.cl -cl-ext=+__opencl_c_device_enqueue
1.      clqueens.cl:416:1: current parser token 'kernel'
2.      clqueens.cl:237:13: LLVM IR generation of declaration 'relaunch_kernel'
3.      clqueens.cl:237:13: Generating code for declaration 'relaunch_kernel'
4.      clqueens.cl:288:93: LLVM IR generation of compound statement ('{}')
 #0 0x0000000003837ed6 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /export/users/haonanya/ocl-clang-110/llvm/lib/Support/Unix/Signals.inc:564:22
 #1 0x0000000003837f69 PrintStackTraceSignalHandler(void*) /export/users/haonanya/ocl-clang-110/llvm/lib/Support/Unix/Signals.inc:625:1
 #2 0x0000000003835ffb llvm::sys::RunSignalHandlers() /export/users/haonanya/ocl-clang-110/llvm/lib/Support/Signals.cpp:68:20
 #3 0x0000000003837919 SignalHandler(int) /export/users/haonanya/ocl-clang-110/llvm/lib/Support/Unix/Signals.inc:406:1
 #4 0x00007f5388d8ed80 __restore_rt (/lib64/libpthread.so.0+0x12d80)
 #5 0x00007f538786f93f raise (/lib64/libc.so.6+0x3793f)
 #6 0x00007f5387859c95 abort (/lib64/libc.so.6+0x21c95)
 #7 0x00007f5387859b69 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21b69)
 #8 0x00007f5387867df6 (/lib64/libc.so.6+0x2fdf6)
 #9 0x0000000004007381 llvm::cast_retty<clang::BlockExpr, clang::Expr const*>::ret_type llvm::cast<clang::BlockExpr, clang::Expr const>(clang::Expr const*) /export/users/haonanya/ocl-clang-110/llvm/include/llvm/Support/Casting.h:269:3
#10 0x000000000411311b getBlockExpr(clang::Expr const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGOpenCLRuntime.cpp:140:1
#11 0x0000000004113363 clang::CodeGen::CGOpenCLRuntime::emitOpenCLEnqueuedBlock(clang::CodeGen::CodeGenFunction&, clang::Expr const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGOpenCLRuntime.cpp:166:40
#12 0x0000000003ec95b9 clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(clang::GlobalDecl, unsigned int, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGBuiltin.cpp:4184:46
#13 0x000000000403cdfa clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExpr.cpp:4760:42
#14 0x0000000004070a48 (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:581:34
#15 0x0000000004088c36 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) /export/users/haonanya/ocl-clang-110/build/tools/clang/include/clang/AST/StmtNodes.inc:813:1
#16 0x000000000406fcd0 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:412:57
#17 0x0000000004077fe6 (anonymous namespace)::ScalarExprEmitter::VisitCastExpr(clang::CastExpr*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:2106:17
#18 0x00000000040709b3 (anonymous namespace)::ScalarExprEmitter::VisitExplicitCastExpr(clang::ExplicitCastExpr*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:574:3
#19 0x000000000408a547 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::VisitCStyleCastExpr(clang::CStyleCastExpr*) /export/users/haonanya/ocl-clang-110/build/tools/clang/include/clang/AST/StmtNodes.inc:859:1
#20 0x0000000004088cc6 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) /export/users/haonanya/ocl-clang-110/build/tools/clang/include/clang/AST/StmtNodes.inc:859:1
#21 0x000000000406fcd0 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:412:57
#22 0x00000000040862b2 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:4701:35
#23 0x0000000004022d80 clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExpr.cpp:211:55
#24 0x0000000004022f3a clang::CodeGen::CodeGenFunction::EmitAnyExprToTemp(clang::Expr const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExpr.cpp:230:32
#25 0x0000000003fbd16e clang::CodeGen::CodeGenFunction::EmitCallArg(clang::CodeGen::CallArgList&, clang::Expr const*, clang::QualType) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGCall.cpp:3972:11
#26 0x0000000003fbc427 clang::CodeGen::CodeGenFunction::EmitCallArgs(clang::CodeGen::CallArgList&, llvm::ArrayRef<clang::QualType>, llvm::iterator_range<clang::Stmt::CastIterator<clang::Expr, clang::Expr const* const, clang::Stmt const* const> >, clang::CodeGen::CodeGenFunction::AbstractCallee, unsigned int, clang::CodeGen::CodeGenFunction::EvaluationOrder) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGCall.cpp:3819:5
#27 0x0000000003e45cee void clang::CodeGen::CodeGenFunction::EmitCallArgs<clang::FunctionProtoType>(clang::CodeGen::CallArgList&, clang::FunctionProtoType const*, llvm::iterator_range<clang::Stmt::CastIterator<clang::Expr, clang::Expr const* const, clang::Stmt const* const> >, clang::CodeGen::CodeGenFunction::AbstractCallee, unsigned int, clang::CodeGen::CodeGenFunction::EvaluationOrder) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenFunction.h:4594:17
#28 0x000000000403f2da clang::CodeGen::CodeGenFunction::EmitCall(clang::QualType, clang::CodeGen::CGCallee const&, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot, llvm::Value*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExpr.cpp:5149:15
#29 0x000000000403ce7a clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExpr.cpp:4767:68
#30 0x0000000004070a48 (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:581:34
#31 0x0000000004088c36 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) /export/users/haonanya/ocl-clang-110/build/tools/clang/include/clang/AST/StmtNodes.inc:813:1
#32 0x000000000406fcd0 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:412:57
#33 0x00000000040862b2 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGExprScalar.cpp:4701:35
#34 0x0000000003ffc175 clang::CodeGen::CodeGenFunction::EmitScalarInit(clang::Expr const*, clang::ValueDecl const*, clang::CodeGen::LValue, bool) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:752:40
#35 0x00000000040018a1 clang::CodeGen::CodeGenFunction::EmitExprAsInit(clang::Expr const*, clang::ValueDecl const*, clang::CodeGen::LValue, bool) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:1899:19
#36 0x0000000004001578 clang::CodeGen::CodeGenFunction::EmitAutoVarInit(clang::CodeGen::CodeGenFunction::AutoVarEmission const&) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:1860:26
#37 0x0000000003ffe83e clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(clang::VarDecl const&) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:1286:22
#38 0x0000000003ff9aa9 clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:200:27
#39 0x0000000003ff97d7 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) (.localalias.0) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGDecl.cpp:145:47
#40 0x0000000003c1fdc1 clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:1187:3
#41 0x0000000003c1c243 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:378:75
#42 0x0000000003c1b4ab clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:53:3
#43 0x0000000003c1c72e clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:418:3
#44 0x0000000003c1c41a clang::CodeGen::CodeGenFunction::EmitCompoundStmt(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:404:58
#45 0x0000000003c1c21c clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:377:72
#46 0x0000000003c1b4ab clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:53:3
#47 0x0000000003c1e965 clang::CodeGen::CodeGenFunction::EmitForStmt(clang::ForStmt const&, llvm::ArrayRef<clang::Attr const*>) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:955:37
#48 0x0000000003c1b7b0 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:146:75
#49 0x0000000003c1c72e clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CGStmt.cpp:418:3
#50 0x0000000003cae388 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenFunction.cpp:1147:36
#51 0x0000000003caef50 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenFunction.cpp:1312:21
#52 0x0000000003cd58c5 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenModule.cpp:4528:3
#53 0x0000000003cced15 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenModule.cpp:2890:47
#54 0x0000000003ccddd0 clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenModule.cpp:2643:5
#55 0x0000000003cd954a clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.localalias.1) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenModule.cpp:5342:37
#56 0x0000000004c3bcc6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/ModuleBuilder.cpp:169:7
#57 0x0000000004c35b69 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenAction.cpp:216:7
#58 0x000000000649a89c clang::ParseAST(clang::Sema&, bool, bool) /export/users/haonanya/ocl-clang-110/clang/lib/Parse/ParseAST.cpp:162:20
#59 0x000000000437a91d clang::ASTFrontendAction::ExecuteAction() /export/users/haonanya/ocl-clang-110/clang/lib/Frontend/FrontendAction.cpp:1057:11
#60 0x0000000004c33cb1 clang::CodeGenAction::ExecuteAction() /export/users/haonanya/ocl-clang-110/clang/lib/CodeGen/CodeGenAction.cpp:1185:1
#61 0x000000000437a285 clang::FrontendAction::Execute() /export/users/haonanya/ocl-clang-110/clang/lib/Frontend/FrontendAction.cpp:954:38
#62 0x00000000043138c8 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /export/users/haonanya/ocl-clang-110/clang/lib/Frontend/CompilerInstance.cpp:984:42
#63 0x00000000044f22e8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /export/users/haonanya/ocl-clang-110/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:278:38
#64 0x00000000021052da cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /export/users/haonanya/ocl-clang-110/clang/tools/driver/cc1_main.cpp:240:40
#65 0x00000000020fb31b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /export/users/haonanya/ocl-clang-110/clang/tools/driver/driver.cpp:330:20
#66 0x00000000020fba1c main /export/users/haonanya/ocl-clang-110/clang/tools/driver/driver.cpp:407:26
#67 0x00007f538785b813 __libc_start_main (/lib64/libc.so.6+0x23813)
#68 0x00000000020f9bae _start (../ocl-clang-110/build/bin/clang+++0x20f9bae)
Aborted (core dumped)
`
I will look into the issue, thanks.

**Comment by haonanya** [comment]
Small reproducer is attached.
[block.cl.txt](https://github.com/intel/intel-graphics-compiler/files/7947273/block.cl.txt)

**Comment by haonanya** [comment]
I file an issue https://github.com/llvm/llvm-project/issues/53436.

**Comment by sudden6** [comment]
@haonanya Thank you very much!
