### ISSUE TITLE
Blender hangs when compiling render kernels

### ISSUE THREAD

**Issue by kquote03** [intel/intel-graphics-compiler#208]
Console output:
```
Cycles: compiling OpenCL program split_shadow_blocked_dl...
Cycles: compiling OpenCL program split_shadow_blocked_ao...

```

**Comment by mnaczk** [comment]
Sorry for the late response. Could you please provide reproduction steps?

**Comment by mnaczk** [comment]
No response from the submitter. I'm closing the issue. If the problem persists please reopen the issue.
