### ISSUE TITLE
Avoid using glibc-specific strerror_r variant

### ISSUE THREAD

**Issue by rcombs** [intel/intel-graphics-compiler#213]
IGC currently calls `strerror_r` and expects it to return a `const char*`: https://github.com/intel/intel-graphics-compiler/blob/9307c016f1da25a4dd06b67ab329dd2179b17dfa/visa/iga/IGALibrary/system.cpp#L263

This is glibc-specific behavior. The POSIX behavior is for `strerror_r` to always write its output to the passed-in buffer, and to return an integer error code. This behavior is the only variant available in musl, the default on android bionic, and is available in glibc by defining the `_POSIX_C_SOURCE` macro to a value ≥ `200112L` while not setting `_GNU_SOURCE`.

Could IGC set `_POSIX_C_SOURCE` before including headers in `system.cpp` and switch to expecting the POSIX behavior for this, to improve portability?

**Comment by trbauer** [comment]
Excellent. (At a glace) I agree. We desire portability here.

**Comment by jbeich** [comment]
Obsolete after f2918eea84a4 ?

**Comment by rcombs** [comment]
f2918ee looks potentially incorrect to me; the glibc version of `strerror_r` doesn't necessarily write its output to the passed-in buffer (it may instead just return a static string).

**Comment by mnaczk** [comment]
A new commit with the fix proposition was merged with the repo. https://github.com/intel/intel-graphics-compiler/commit/7f14252fbe21324d0c777e6442f4b7d6d6718f4c @rcombs Could you please check if this solves the issue?

**Comment by rcombs** [comment]
Looking at the new code:
```
#if (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE
```
This checks the glibc behavior, but doesn't check that glibc is _in use_. You need to add a check for `__GLIBC__ `:
```
#if !defined(__GLIBC__) || ((_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE)
```
This way, other libc implementations will get the standard behavior regardless.

**Comment by jbeich** [comment]
7f14252fbe21 breaks build on FreeBSD:
```c++
visa/iga/IGALibrary/system.cpp:268:14: error: incompatible integer to pointer conversion assigning to 'char *' from 'int'
    errMsg = strerror_r(errCode, buf, sizeof(buf));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Checking `_POSIX_C_SOURCE`, `_XOPEN_SOURCE` or `_GNU_SOURCE` makes no sense as those are reserved for application code but IGC doesn't define them.
```diff
diff --git a/visa/iga/IGALibrary/system.cpp b/visa/iga/IGALibrary/system.cpp
index 192b64b55..7d2034999 100644
--- a/visa/iga/IGALibrary/system.cpp
+++ b/visa/iga/IGALibrary/system.cpp
@@ -260,13 +260,13 @@ std::string iga::FormatLastError(unsigned errCode)
         msg = errMsg;
 #else
 // The XSI-compliant version of strerror_r() is provided if:
-#if (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE
+#ifndef __GLIBC__
     // strerror_r return int for The XSI-compliant
     strerror_r(errCode, buf, sizeof(buf));
 #else
     // GNU-specific version is provided and strerror_r return char*
     errMsg = strerror_r(errCode, buf, sizeof(buf));
-#endif // (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE
+#endif
 #endif // _WIN32
     if (errMsg == nullptr || errMsg[0] == 0)
         return "???";
```

> Could IGC set `_POSIX_C_SOURCE` before including headers in system.cpp and switch to expecting the POSIX behavior for this, to improve portability?

It would break libc++ (`CXX=clang++` + `CXXFLAGS=-stdlib=libc++`):
```c++
In file included from visa/iga/IGALibrary/system.cpp:10:
In file included from visa/iga/IGALibrary/system.hpp:12:
In file included from /usr/include/c++/v1/ostream:139:
In file included from /usr/include/c++/v1/ios:214:
/usr/include/c++/v1/__locale:676:16: error: use of undeclared identifier 'isascii'
        return isascii(__c) ? (__tab_[static_cast<int>(__c)] & __m) !=0 : false;
               ^
/usr/include/c++/v1/__locale:683:22: error: use of undeclared identifier 'isascii'
            *__vec = isascii(*__low) ? __tab_[static_cast<int>(*__low)] : 0;
                     ^
/usr/include/c++/v1/__locale:691:17: error: use of undeclared identifier 'isascii'
            if (isascii(*__low) && (__tab_[static_cast<int>(*__low)] & __m))
                ^
/usr/include/c++/v1/__locale:700:19: error: use of undeclared identifier 'isascii'
            if (!(isascii(*__low) && (__tab_[static_cast<int>(*__low)] & __m)))
                  ^
4 errors generated.
```

Defining `_GNU_SOURCE` wouldn't help because it's not supported. On BSDs all features are exposed by default. Cheating standards is possible but the knob is different: `__BSD_VISIBLE` on DragonFly/FreeBSD/OpenBSD and `_NETBSD_SOURCE` on NetBSD. Easier to drop `_POSIX_C_SOURCE` while keeping `_GNU_SOURCE` to make GNU mimic BSD by exposing everything, including GNU version of `strerror_r`.

**Comment by mnaczk** [comment]
The next fix proposition was merged with the repo. https://github.com/intel/intel-graphics-compiler/commit/b1adbfe219b05fe5357353ee6f8e2b66e0675f20 @rcombs and @jbeich Could you please check if this solves the issue?

**Comment by jbeich** [comment]
Still fails on FreeBSD:
```c++
visa/iga/IGALibrary/system.cpp:267:18: error: incompatible integer to pointer conversion assigning to 'char *' from 'int'
        errMsg = strerror_r_return_value;
                 ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rcombs** [comment]
You need `if constexpr` to avoid that.

**Comment by mnaczk** [comment]
Thanks @rcombs for the suggestion, @jbeich Did commit https://github.com/intel/intel-graphics-compiler/commit/37590986a64f1a5dd14e93a5beb1dbb46049b9d1 fix the building crash on FreeBSD?

**Comment by jbeich** [comment]
No, `if constexpr` didn't help. `igc-1.0.11378-160-gec864ca53` still fails:
```c++
visa/iga/IGALibrary/system.cpp:267:18: error: incompatible integer to pointer conversion assigning to 'char *' from 'int'
        errMsg = strerror_r_return_value;
                 ^~~~~~~~~~~~~~~~~~~~~~~
```
```
$ c++ --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by mnaczk** [comment]
Next fix proposal https://github.com/intel/intel-graphics-compiler/commit/d5231d0dbb097ec8a1de070f60ce58afecf2f5bf @jbeich Did this commit fix build break on FreeBSD?
