### ISSUE TITLE
Update to llvm 7.0

### ISSUE THREAD

**Issue by marcthe12** [intel/intel-graphics-compiler#22]
With llvm 7.0 out, we should update to the latest version of llvm. I also recommend upstreaming all the patches. This could allow one day to use system clang espically on linux

**Comment by paigeale** [comment]
Hello Marc,

That is an excellent point. We are actually currently in the process of upgrading our compiler offline to using llvm 7.0. There is also an on going effort to remove/upstream the necessary patches. Our hopes are to target different Linux distributors in the future that require the latest llvm and clang. Stay tuned for these changes!

**Comment by chivakker** [comment]
Has this been completed?  It seems llvm patches are still needed according to README. Please resolve, don't close/reopen this ticket.
