### ISSUE TITLE
Building "compute-runtime" releases fails to ocloc errors with all IGC releases after "igc-1.0.9636"

### ISSUE THREAD

**Issue by eero-t** [intel/intel-graphics-compiler#224]
When trying to build latest compute-runtime "21.52.22081" release, after building:
* GMMlib: intel-gmmlib-22.0.1
* IGC: igc-1.0.9933, with:
  - SPIRV-Headers: sdk-1.2.198.0
  - SPIRV-LLVM-Translator: llvm_release_110
  - SPIRV-Tools: v2021.4
  - vc-intrinsics: HEAD
* Level-Zero: v1.7.4

I get following errors:
```
...
[338/2454] Building CXX object shared/source/CMakeFiles/neo_shared.dir/program/sync_buffer_handler.cpp.o
[339/2454] Generating ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-kernel-arg-info, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-kernel-arg-info, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-kernel-arg-info
FAILED: bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-kernel-arg-info bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-kernel-arg-info bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-kernel-arg-info 
cd /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files && LD_LIBRARY_PATH=/home/nobody/source/compute-runtime/build/bin /home/nobody/source/compute-runtime/build/bin/ocloc -file /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files/CopyBuffer_simd16.cl -device tgllp -64 -out_dir /home/nobody/source/compute-runtime/build/bin/Gen12LPlp/0/test_files/x64/ -revision_id 0 -options -cl-kernel-arg-info -options_name
: CommandLine Error: Option 'spirv-expand-step' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
[340/2454] Building CXX object shared/source/CMakeFiles/neo_shared.dir/os_interface/windows/os_environment_win.cpp.o
[341/2454] Generating ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-finite-math-only, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-finite-math-only, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-finite-math-only
FAILED: bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-finite-math-only bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-finite-math-only bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-finite-math-only 
cd /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files && LD_LIBRARY_PATH=/home/nobody/source/compute-runtime/build/bin /home/nobody/source/compute-runtime/build/bin/ocloc -file /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files/CopyBuffer_simd16.cl -device tgllp -64 -out_dir /home/nobody/source/compute-runtime/build/bin/Gen12LPlp/0/test_files/x64/ -revision_id 0 -options -cl-finite-math-only -options_name
: CommandLine Error: Option 'spirv-expand-step' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
[342/2454] Generating ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-fast-relaxed-math, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-fast-relaxed-math, ../../../bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-fast-relaxed-math
FAILED: bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.spv-cl-fast-relaxed-math bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.bin-cl-fast-relaxed-math bin/Gen12LPlp/0/test_files/x64/CopyBuffer_simd16_Gen12LPlp.gen-cl-fast-relaxed-math 
cd /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files && LD_LIBRARY_PATH=/home/nobody/source/compute-runtime/build/bin /home/nobody/source/compute-runtime/build/bin/ocloc -file /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files/CopyBuffer_simd16.cl -device tgllp -64 -out_dir /home/nobody/source/compute-runtime/build/bin/Gen12LPlp/0/test_files/x64/ -revision_id 0 -options -cl-fast-relaxed-math -options_name
: CommandLine Error: Option 'spirv-expand-step' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

Googling shows this to happen when components have been built against different LLVM versions.  However, above is built in a Ubuntu 21.04 container which has only (Ubuntu) LLVM v11 installed.

**Comment by eero-t** [comment]
Thanks for moving the ticket!   Same issue happens also with the new "compute-runtime" 22.01.22131 release.

**Comment by eero-t** [comment]
> Same issue happens also with the new "compute-runtime" 22.01.22131 release.

And with the new compute-runtime "22.04.22286" release.

**Comment by eero-t** [comment]
> Same issue happens also with the new "compute-runtime" 22.01.22131" and "22.04.22286" releases.

And new "igc-1.0.10183" IGC version.  Also, IGC fails building SPIRV-Tools "v2022.1" (for "v2021.4" it still works).

**Comment by eero-t** [comment]
> > Same issue happens also with the new "compute-runtime" 22.01.22131" and "22.04.22286" releases.
> 
> And new "igc-1.0.10183" IGC version.

And new "igc-1.0.10200" IGC release with new "22.07.22465" compute-runtime release.  This time on top of Ubuntu 20.10 i.e. LLVM 12 + GCC 11.

Like earlier, downgrading to IGC "igc-1.0.9636" fixes compute-runtime build.


> Also, IGC fails building SPIRV-Tools "v2022.1" (for "v2021.4" it still works).

SPIRV-Tools issue was Khronos having mismatched releases. Build works fine when using e.g. the new "sdk-1.3.204.0" tag for both SPIRV headers and tools projects.

**Comment by eero-t** [comment]
Same problem with the new "igc-1.0.10395" release (on top of Ubuntu 20.10 i.e. LLVM 12 + opencl-clang12 + GCC 11) when building "compute-runtime":
```
[345/2728] Generating ../../../bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.spv, ../../../bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.bin, ../../../bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.gen
FAILED: bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.spv bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.bin bin/Gen12LPlp/0/test_files/x64/kernel_num_args_Gen12LPlp.gen 
cd /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files && LD_LIBRARY_PATH=/home/nobody/source/compute-runtime/build/bin /home/nobody/source/compute-runtime/build/bin/ocloc -q -file /home/nobody/source/compute-runtime/opencl/test/unit_test/test_files/kernel_num_args.cl -device tgllp -64 -revision_id 0 -out_dir /home/nobody/source/compute-runtime/build/bin/Gen12LPlp/0/test_files/x64/
: CommandLine Error: Option 'spirv-expand-step' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

**Comment by eero-t** [comment]
@pszymich, could somebody take a look at this?

Same months old build regression happens also with the new "igc-1.0.10778" release and latest compute-runtime release "22.12.22749", on all Ubuntu releases with new enough LLVM / opencl-clang version:
* Ubuntu 21.04: LLVM 11 + opencl-clang11 + GCC 10.3
* Ubuntu 21.10: LLVM 12 + opencl-clang12 + GCC 11.2
* Ubuntu 22.04: LLVM 13 + opencl-clang13 + GCC 11.2

What makes this issue more critical now, is that the latest 2 "compute-runtime" releases cannot any more be built even with the older (Dec 22) IGC "igc-1.0.9636" release (which does not have this particular issue), as newer compute-runtime releases require IGC EU fusion support to build.  Additionally, IGC "igc-1.0.9636" fails compute-runtime build, if it's built with LLVM 13 (issue #204).

I.e. the latest IGC + compute-runtime combination that I can build _with_ system LLVM (which implies using also system opencl-clang):
* IGC: igc-1.0.9636 (2021-12-22)
* compute-runtime: 22.10.22597 (2022-02-28)
* Ubuntu 21.10 / LLVM 12

Using newer version of any of those, causes compute-runtime build to fail due to different IGC issues.

PS. I guess this bug (along with the external component usage issues that were fixed recently) explains why IGC and compute-runtime versions in forthcoming Ubuntu 22.04 LTS version are even older, from the last summer:
* https://packages.ubuntu.com/source/jammy/intel-graphics-compiler
* https://packages.ubuntu.com/source/jammy/intel-compute-runtime

PPS. This is really frustrating as I mainly want up to date L0 Sysman API support on 22.04 for Intel dGPUs from the compute-runtime (which does not need anything from IGC, except it not breaking compute-runtime build). Aargh!!!

**Comment by mnaczk** [comment]
Hi @eero-t 

Starting with the commit [3fde0acae81b48b5225e1760e1feb9ae44ccdbb2: remove spirvdll](https://github.com/intel/intel-graphics-compiler/commit/3fde0acae81b48b5225e1760e1feb9ae44ccdbb2)
The vector compiler starts using the Khronos LLVM-SPIRV translator, which is shared with the OpenCL clang. So the libLLVMSPIRVLib.so file used by OpenCL-clang and Vector Compiler must be the same.

In your CMake command line, I see an option
-DIGC_OPTION__SPIRV_TRANSLATOR_MODE=Source
This forces IGC to build the SPIRV_TRANSLATOR from the source, which causes a linking error in the Neo build.

Additionally, I found a bug in IGC CMakeLists.txt that even without -DIGC_OPTION__SPIRV_TRANSLATOR_MODE=Source SPIRV_TRANSLATOR will be built from source if on the same level as the IGC folder there is an llvm-spirv folder with SPIRV_TRANSLATOR source.
A fix should be available in the next IGC release.

If you want to build your own SPIRV_TRANSLATOR, you need to rebuild openCL-clang.

Please let me know if the above information is helpful.

**Comment by eero-t** [comment]
@mnaczk I tried using Ubuntu 21.10 spirv-llvm/-dev, spirv-tools and spirv-headers, but then IGC configuration failed to it not finding spirv-tools:
```
-- [SPIRV-Tools] : IGC_OPTION__SPIRV_TOOLS_MODE set to Prebuilds
-- [SPIRV-Tools] : IGC__OPTION_USE_PREINSTALLED_SPRIV_HEADERS set to OFF
-- [SPIRV-Tools] : Using default path /home/nobody/source/intel-graphics-compiler/IGC/../../SPIRV-Headers
-- [SPIRV-Tools] : Searching prebuilt SPIRV-Tools package
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake:98 (message):
  The imported target "SPIRV-Tools-shared" references the file
     "/usr/lib/x86_64-linux-gnu/libSPIRV-Tools-shared.so"
  but this file does not exist.
```
FYI: "spirv-tools" package file paths are following: https://packages.ubuntu.com/impish/amd64/spirv-tools/filelist

When I added sources back for SPIRV tools & headers, IGC config phase passed, but then its build failed to vc-intrinsics issues #239.

If build still fails after #239 is dealt with, I could try building both lllvm-spirv + opencl-clang...

(If latter nowadays can be done without also building llvm. Last time I tried it, long time ago, it did not work.)

PS: There's no mention of this LLVM<->SPIRV-LLVM<->OpenCL-Clang restriction in the build instructions, maybe something could be added there: https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md

**Comment by mnaczk** [comment]
@eero-t The error log point that issue is on resolving CMake files. /usr/lib/x86_64-linux-gnu/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake want libSPIRV-Tools-shared.so but it not exist in package https://packages.ubuntu.com/impish/amd64/spirv-tools/filelist. So the issue probably is not on the IGC side.

I mentioned in #239 that vc-intinsics should be checkout to a specific commit described in the IGC release note.

If building IGC with spirv-tool and spirv-headers from the source works fine then the current issue is resolved?

**Comment by eero-t** [comment]
> The error log point that issue is on resolving CMake files. /usr/lib/x86_64-linux-gnu/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake want libSPIRV-Tools-shared.so but it not exist in package https://packages.ubuntu.com/impish/amd64/spirv-tools/filelist. So the issue probably is not on the IGC side.

@tjaalton  Any comment on why Ubuntu "spirv-tools" package provides only static version of the tools library, and not the shared one required by IGC?


> I mentioned in #239 that vc-intinsics should be checkout to a specific commit described in the IGC release note.
> 
> If building IGC with spirv-tool and spirv-headers from the source works fine then the current issue is resolved?

@mnaczk Yes, indeed it works fine now. Thanks!

IMHO you could add some note (to Ubuntu build docs) about which all components need to either come from the system, or be _all_ built from sources, and for which components you do not support use of system versions, but I'll close this now.

**Comment by tjaalton** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/issues/3909
that pretty much sums it up, especially https://github.com/KhronosGroup/SPIRV-Tools/issues/3214 which was referenced in the Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980370
