### ISSUE TITLE
Update LLVM versions status in "projects"

### ISSUE THREAD

**Issue by eero-t** [intel/intel-graphics-compiler#225]
According to projects page, it has last been updated in September: https://github.com/intel/intel-graphics-compiler/projects

Since that, for example 3 of the 4 bugs referenced in those status pages, have been closed.

**Comment by pszymich** [comment]
Hi @eero-t,

The LLVM compatibility status pages were meant to follow the LLVM update status.
Some issues have been closed, but there's no need for them to move between categories. Eg. in [LLVM 12 status page](https://github.com/intel/intel-graphics-compiler/projects/2), issue #191 is resolved, but it's category is still "Build health". I may decide to archive those closed ones, but for now I see no need.

It's true that the LLVM update process has been slow recently. Alchemist and PVC support have taken precedence.
We expect to resume working on 12 and 13 update as soon as later this month. Thank you for patience.

Do you have any other suggestions for our projects page?

Thanks,
Pawel

**Comment by eero-t** [comment]
Next Ubuntu LTS (22.04) will be released in 3.5 months, and it's (currently) defaulting to LLVM v13: https://packages.ubuntu.com/jammy/llvm

So I had been hoping for more progress, and projects page just being out of date, but I completely understand HW support having more priority.

> We expect to resume working on 12 and 13 update as soon as later this month.

Thanks for the info!

Things going to new disto version would need to be released couple of month before the new distro version is released, to get into it => timing is getting a bit tight for fixing LLVM 13 support in IGC for 22.04 LTS.

PS. Things around the new SPIRV dependencies & clang-opencl may need also a bit more documentation & testing, considering distro's needs to split things to separate (dynamic library) package dependencies that are shared by multiple projects, instead them being compiled with their own private LLVM versions (and potentially conflicting with system LLVM version).

**Comment by eero-t** [comment]
The situation for upcoming Ubuntu 22.04 LTS is looking a bit odd.  IGC itself built against LLVM 12: https://packages.ubuntu.com/source/jammy/intel-graphics-compiler

But its opencl-clang dependency is built against LLVM 13: https://packages.ubuntu.com/source/jammy/intel-opencl-clang

Can that work?

**Comment by pszymich** [comment]
I'm not sure why such packages are available, but IGC cannot use opencl-clang built against different LLVM major release.

**Comment by eero-t** [comment]
By default packages are built against distro version default compiler version, unless package maintainer does something exceptional.  In 22.04 default LLVM is v13.  In IGC case, LLVM version needs to be explicitly state because support for other than single version is less good.

(E.g. Mesa project supports latest and one older version of LLVM.)

**Comment by pszymich** [comment]
We have run wide testing scope for LLVM 12. There are some regressions associated with the upgrade we will need to address before the switch. Our testing scope includes i.a. Khronos' OpenCL-CTS tests. ETA is hard to gauge unfortunately.

A question: would it benefit distro maintaners, if alongside regular releases there were IGC packages published built against LLVM 12 (even if not production ready)?

**Comment by eero-t** [comment]
> We have run wide testing scope for LLVM 12. There are some regressions associated with the upgrade we will need to address before the switch. Our testing scope includes i.a. Khronos' OpenCL-CTS tests. ETA is hard to gauge unfortunately.
> 
> A question: would it benefit distro maintainers, if alongside regular releases there were IGC packages published built against LLVM 12 (even if not production ready)?

Distro maintainers do builds using pre-built (pre-packaged) versions of LLVM and other dependencies.  Unless your own builds with newer LLVM versions are similar, I do not think distro maintainers would have much use for them as comparison points.  @tjaalton Any comments on this?

Such builds would make it easier for the community to provide wider testing for IGC versions based on those LLVM versions though, which seems like a good thing, _if_ you're prepared to handle additional bug reports from them.

You would need to think how to provide those versions, so that:
* it's (relatively) easy for users to test them,
* but not get them by accident,
* it's clear what are the known issues with them, so that:
  * people know whether they can actually use them
  * you do not get duplicate bug reports
* there's a matching compute-runtime (as IGC is normally used through that),
* and it's clear in your bug reports which version user used

Maybe use separate repo for them, and list them separately from the best-know-config version in the release notes, with some note about additional issues in them?  IMHO you should also ask users to add prefix like "[LLVM 12]" to any bug reports filed for them.

Instead of providing a repo, you could just have a link for CI run closest to given release (with zip of debs), like this: https://github.com/intel/intel-graphics-compiler/actions/runs/1883449664

But you would need also link to matching compute-runtime CI run.

**Comment by eero-t** [comment]
As there's work in progress to get LLVM 14 working: https://github.com/intel/intel-graphics-compiler/pull/242

Maybe an entry could be added to projects also for LLVM 14?

**Comment by pszymich** [comment]
Hi @eero-t, I've made some updates to the project page. Thank you for the suggestions!

**Comment by eero-t** [comment]
Ok, so LLVM 12 & 13 both work now, but will remain at Beta support, and 14 will be the next production supported version after 11 (once support for it lands).

Thanks for the update!  => closing.
