### ISSUE TITLE
Provide relevant tag / branch names for dependencies in release notes

### ISSUE THREAD

**Issue by eero-t** [intel/intel-graphics-compiler#231]
Please refer to most relevant tags in dependecies, similarly to how compute-runtime release notes do.

Motivation for this would be:
* Tags give some indication of whether the dependencies have:
  * Gone through more testing than some random commit
  * Are likely to have API changes
* Dependency versions can be compared against each other (without user needing to do extra detective work in git repos for each dependency):
  * Between IGC releases
  * Against dependencies distro versions

I assume that IGC releases could use e.g. these tags for its dependencies:
* vc-intrinsics: v0.1.0
* SPIRV-Headers: sdk-1.3.204.0  (or sdk-1.3.204.1 that points to same commit)
* SPIRV-Tools: sdk-1.3.204.0  (or sdk-1.3.204.1 that points to same commit)

And in opencl-clang and SPIRV-LLVMM-Translator cases, it could be mentioned from which branch the specified commits are taken.

**Comment by eero-t** [comment]
> Please note however, that opencl-clang and LLVM-SPIRV-Translator do not have a regular release cadence. In these cases we may need to continue providing commit ID.

Sure. For those, I was suggesting adding the branch name to the commit information.  While one can deduce that from the used LLVM version, IMHO it would still be nice to mention that IGC built with LLVM 11 uses commit "50bf6d7" from "ocl-open-110" branch, and LLVM-SPIRV-Translator commit "cf681c8" from "llvm_release_110" branch.

(I'm assuming you can easily automate such part of release notes generation.)

Users could then skip checking the branch name, when e.g. checking respective commit distance from branch heads:
```
opencl-clang$  git checkout ocl-open-110 && git pull && gitk 50bf6d7...ocl-open-110
LLVM-SPIRV-Translator$ git checkout llvm_release_110 && git pull && gitk cf681c8...llvm_release_110
```
(Answering e.g. question would using branch head  instead, provide some advantage, or could it cause issues.)

**Comment by pszymich** [comment]
Hi, we've updated the release notes in the latest release with requested changes: https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.10409

SPIRV-Tools/Headers will be changed to tags in some future release. We made the change to tags in our CI quite recently, so it needs some time to catch up with release cadence.

Thanks!

**Comment by eero-t** [comment]
> we've updated the release notes in the latest release with requested changes: https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.10409
> 
> SPIRV-Tools/Headers will be changed to tags in some future release. We made the change to tags in our CI quite recently, so it needs some time to catch up with release cadence.

The new release notes dependency table looks great, thanks!

**Comment by ArchangeGabriel** [comment]
@pszymich Thanks! I must say I am very satisfied with the work of your team here lately regarding use of external dependencies (and also grateful to @eero-t for pushing that forward).
