### ISSUE TITLE
(External) Protobuf dependency

### ISSUE THREAD

**Issue by tgurr** [intel/intel-graphics-compiler#233]
While building with metrics appears to be optional, it doesn't seem to be the case for compute-runtime-22.08.22549 where I get:

```
CMake Error at cmake/find_metrics.cmake:78 (include_directories):
  include_directories given empty-string as include directory.
Call Stack (most recent call first):
  CMakeLists.txt:369 (include)
```

So for the actual problem, igc can't find protobuf installed system-wide printing the following warning during build:

```
CMake Warning at IGC/cmake/igc_find_protobuf.cmake:25 (message):
  Cannot find Protoc program or library for Protobuf, please visit
  https://github.com/protocolbuffers/protobuf/releases and install - disable
  of IGC Metrics
Call Stack (most recent call first):
  IGC/CMakeLists.txt:1356 (include)
```
https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md doesn't even mention protobuf at all, neither as dependency to install nor as additional step to clone any external sources. So how is this supposed to work?

**Comment by lwesiers** [comment]
The issue here:
https://github.com/intel/compute-runtime/blob/5d80d509554921d6d953f7f9c290d6cff0d6ef90/cmake/find_metrics.cmake#L78
```
CMake Error at cmake/find_metrics.cmake:78 (include_directories):
  include_directories given empty-string as include directory.
Call Stack (most recent call first):
  CMakeLists.txt:369 (include)
```

Isn't related in any case with missing protobuf and IGCMetrics.

I suggest to contact folks from https://github.com/intel/compute-runtime, because this is not IGC issue.

**Comment by ArchangeGabriel** [comment]
Outside of the compute-runtime issue, there is still the fact that intel-graphics-compiler does not detect a system installed protobuf:
```
CMake Warning at IGC/cmake/igc_find_protobuf.cmake:25 (message):
  Cannot find Protoc program or library for Protobuf, please visit
  https://github.com/protocolbuffers/protobuf/releases and install - disable
  of IGC Metrics
Call Stack (most recent call first):
  IGC/CMakeLists.txt:1362 (include)
```

**Comment by lwesiers** [comment]
IGCMetrics and finding Protobuf  are still WIP - so any issues there are expected. Still, it shouldn't affect the functionality/buildability of the compiler at all.

**Comment by ArchangeGabriel** [comment]
Yes, just in case that wasn’t clear: I can build both IGC and Neo without trouble. I was just reporting that a system installed protobuf is indeed not detected.
