### ISSUE TITLE
 Typo: 'Enivronment'

### ISSUE THREAD

**Issue by tjaalton** [intel/intel-graphics-compiler#238]
git grep -c Enivronment
IGC/AdaptorOCL/OCL/KernelAnnotations.hpp:1
IGC/AdaptorOCL/OCL/sp/sp_g8.cpp:53
IGC/AdaptorOCL/OCL/sp/zebin_builder.cpp:31
IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:39
IGC/Compiler/CodeGenPublic.h:1
IGC/VectorCompiler/igcdeps/include/vc/igcdeps/cmc.h:1
IGC/VectorCompiler/igcdeps/src/cmc.cpp:4

surely it's meant to be 'Environment'?

**Comment by mnaczk** [comment]
Thanks, @tjaalton for your suggestion. Suggestion merged in [072bac565cfd0642d982948ace8a20b520227bd3](https://github.com/intel/intel-graphics-compiler/commit/072bac565cfd0642d982948ace8a20b520227bd3)

**Comment by pszymich** [comment]
Thanks @mnaczk, closing.
