### ISSUE TITLE
Changes in FindSPIRVLLVMTranslator.cmake fail build on Linux with external spirv-llvm-translator

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/intel-graphics-compiler#243]
These changes were introduced by https://github.com/intel/intel-graphics-compiler/commit/afd9fc8be5e507ccfd24d1e5b4da4d2e05c671ff.

It now seems to look for some debug version that we don’t have, at least on Arch Linux. Please either tell us how to achieve such a build or make this change Windows only (as this seems the reason for the change) or somehow accepting both configurations.

**Comment by ArchangeGabriel** [comment]
Hi, I indeed catched that commit since I was surprised people could build from git master y-day. ^^

I can thus confirm it perfectly works, both in master as well as on top of the current release.

I think this ticket should remain open until the commit is part of a release to avoid duplicate tickets from other users/packagers.

**Comment by eero-t** [comment]
There was "igc-1.0.11279" release few hours ago, but unfortunately that's from commit on 11th, while the fix went in on 13th.  So I guess it's in the next release.

**Comment by eero-t** [comment]
@ArchangeGabriel I think you can close this.  Fix is included to latest "igc-1.0.11378" release and it builds fine for me.
