### ISSUE TITLE
intel-igc-opencl_1.0.11279_amd64.deb package broken?

### ISSUE THREAD

**Issue by oscarbg** [intel/intel-graphics-compiler#244]
can reupload?
seems is broken..
I tried multiple downloads..

sudo dpkg -i intel-igc-opencl_1.0.11279_amd64.deb 
(Leyendo la base de datos ... 628037 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar intel-igc-opencl_1.0.11279_amd64.deb ...
Desempaquetando intel-igc-opencl (1.0.11279) ...
dpkg-deb (subproceso): decompressing archive 'intel-igc-opencl_1.0.11279_amd64.deb' (size=56027994) member 'data.tar': error interno de lectura de gzip `<fd:4>: invalid distance code'
dpkg-deb: error: el subproceso <descompresión> devolvió el código de salida de error 2
dpkg: error al procesar el archivo intel-igc-opencl_1.0.11279_amd64.deb (--install):
 no se pudieron copiar los datos extraídos de './usr/local/lib/libopencl-clang.so.11' a '/usr/local/lib/libopencl-clang.so.11.dpkg-new': fin de fichero o de flujo inesperado 
Se encontraron errores al procesar:
 intel-igc-opencl_1.0.11279_amd64.deb

**Comment by powderluv** [comment]
The sha256sum of the package also fails 

```1 anush@alderlake:~/github/neo$ sha256sum intel-igc-opencl_1.0.11279_amd64.deb
67b9608115995b4b91725d145e7f3f79dbdfb4f175d6a561da052a8ce1206c9c  intel-igc-opencl_1.0.11279_amd64.deb
anush@alderlake:~/github/neo$ sudo dpkg -i intel-igc-opencl_1.0.11279_amd64.deb 
(Reading database ... 257940 files and directories currently installed.)
Preparing to unpack intel-igc-opencl_1.0.11279_amd64.deb ...
Unpacking intel-igc-opencl (1.0.11279) ...
dpkg-deb (subprocess): decompressing archive 'intel-igc-opencl_1.0.11279_amd64.deb' (size=56027994) member 'data.tar': internal gzip read error: '<fd:4>: invalid distance code'
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive intel-igc-opencl_1.0.11279_amd64.deb (--install):
 cannot copy extracted data for './usr/local/lib/libopencl-clang.so.11' to '/usr/local/lib/libopencl-clang.so.11.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 intel-igc-opencl_1.0.11279_amd64.deb```

The expected SHA is ffa0ecd326dd00c951f3a904c93d21a8b0f72c6dd5d670dc671ef7b08ef7eb3d according to 

https://github.com/intel/compute-runtime/releases

**Comment by powderluv** [comment]
looks like the data.tar.gz in there is corrupt

```
@alderlake:~/github/neo/deb$ tar -xzf data.tar.gz 

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

in prior releases you see:
```
@alderlake:~/github/neo/deb1$ tar -xvzf data.tar.gz 
./usr/
./usr/local/
./usr/local/lib/
./usr/local/lib/libigdfcl.so
./usr/local/lib/libigdfcl.so.1
./usr/local/lib/libigdfcl.so.1.0.11222
./usr/local/lib/libopencl-clang.so
./usr/local/lib/libopencl-clang.so.11```

**Comment by pszymich** [comment]
Hi, the package has been reuploaded. Thanks for spotting the error!
