### ISSUE TITLE
Please make search for opencl-c.h configurable

### ISSUE THREAD

**Issue by ConiKost** [intel/intel-graphics-compiler#249]
With the latest changes in https://github.com/intel/intel-graphics-compiler/commit/12c99343388eba6e6275856b25e0fa8978585dfb I have some troubles about including ```opencl-c.h```. The build system always assumes, that ```opencl-c.h``` always is one directory upper from executable, when using a system prebuild compiler. This does not apply at least for Gentoo.

```CLANG_EXE_PARENT_DIR``` is being found to ```/usr/lib/llvm/13/bin/clang-13```, while ```opencl-c.h``` is in ```/usr/lib/clang/13.0.1/include/opencl-c.h```.

If I do manually patch the cmake file to use a different path, it works for me. Can we please have a configure option to override path to search for ```opencl-c.h```? Thank you!

**Comment by mnaczk** [comment]
We are currently working on a more modern Cmake approach to combining OpenCL-clang and IGC projects. We currently do not want to add another configuration flag. Work on the update is underway when there will be progress on the issue of opencl-c.h, I will let you know in this issue.

**Comment by ConiKost** [comment]
Thanks!

**Comment by ConiKost** [comment]
@mnaczk any news?

**Comment by mnaczk** [comment]
In commit https://github.com/intel/intel-graphics-compiler/commit/93cac18a11de1a6ad67c291d841c34d4e3f6db25 I added IGC_OPTION__OPENCL_HEADER_PATH. By this option, you can specify the location of opencl-c.h. 
Does it solve your issue? If so, please close the issue.

**Comment by ConiKost** [comment]
I will give a try. Thank you!

**Comment by ConiKost** [comment]
The option doesn't seem to work for me.

```-DIGC_OPTION__OPENCL_HEADER_PATH=/usr/lib/clang/14.0.6/include``` is set.

```
-- [IGC] : opencl-clang will be taken from system
-- [IGC] Found clang-14 executable: /usr/lib/ccache/bin/clang-14
CMake Error at IGC/cmake/igc_find_opencl_clang.cmake:111 (message):
  [IGC] : Couldn't find opencl-c.h, please provide it.
Call Stack (most recent call first):
  IGC/CMakeLists.txt:1450 (include)
```

But I have a question. Why does the if else block checks twice the same? I seems, that I do land in the else block, while I should be in the first if?

```
if(DEFINED IGC_OPTION__OPENCL_HEADER_PATH)
[..]
else(DEFINED IGC_OPTION__OPENCL_HEADER_PATH)
[..] <-- I do land here?
endif()

**Comment by mnaczk** [comment]
@ConiKost Did the solution I provided solve your problem? If it did, please mark the issue as resolved. 
It's important to note that my implementation requires you to include the path to the "opencl-c.h" file, whereas your workaround requires you to include the path to the directory where the "opencl-c.h" file is located.

**Comment by ConiKost** [comment]
Yes. I tested and can confirm, it works for me :-)

```
-- [IGC] : opencl-clang will be taken from system
-- [IGC] Found clang-14 executable: /usr/lib/llvm/14/bin/clang-14
-- [IGC] : IGC_OPTION__OPENCL_HEADER_PATH is set to /usr/lib/clang/14.0.6/include therefore try to search in user defined path
-- [IGC] Found opencl-c.h: /usr/lib/clang/14.0.6/include

```
