### ISSUE TITLE
Latest release's artifacts unusable with Ubuntu 20.04 (gcc 9.4.0)

### ISSUE THREAD

**Issue by sanchitintel** [intel/intel-graphics-compiler#261]
Hi, the latest release's artifacts on GitHub require more recent versions of libc & libstdc++.
Would any version be built for Ubuntu 20.04 & subsequently be made available via apt, now that Arc 770 has been released, so that folks wouldn't have to update to the latest versions of libc & libstdc++? Or are more recent versions of libc & libstdc++ indispensable? Thanks!

<img width="649" alt="image" src="https://user-images.githubusercontent.com/90872293/196021506-9875feba-20b2-40e0-8f41-ed19b939dabb.png">

**Comment by pszymich** [comment]
Hi @sanchitintel, we are aware of the problem. We switched to 22.04 packages in latest release but overlooked the incompatibility.

Starting with next release we will release 20.04 packages. Thanks for spotting the problem.

**Comment by oleksandr-pavlyk** [comment]
Ping. Please re-release igc usable on Ubunutu 20.04.

**Comment by pszymich** [comment]
Hi, since the next release has been delayed we decided to supplement latest release with Ubuntu 20.04 packages.
