### ISSUE TITLE
missing components required for installation of intel-igc-libs

### ISSUE THREAD

**Issue by Ricky-Tigg** [intel/intel-graphics-compiler#264]
**OS:** Fedora x86-64
**source** of `intel-igc-libs`: a Fedora repository
**installed** | `intel-opencl-clang`

Hello. Present in a Fedora repository:
```
$ dnf -q rq --archlist noarch,x86_64 --qf '%{name} %{version} %{summary}' intel-{opencl{,-clang},igc-libs}
intel-igc-libs 1.0.12037.1 Intel Graphics Compiler Frontend - Library Files
intel-opencl 22.34.24023 OpenCL support implementation for Intel GPUs
intel-opencl-clang 15.0.0 Library to compile OpenCL C kernels to SPIR-V modules
```
Description of problem: missing components required for installation of` intel-igc-libs`

Steps to reproduce:
```
# dnf install intel-igc-libs
Error: 
 Problem: conflicting requests
  - nothing provides libLLVMSPIRVLib.so.14()(64bit) needed by intel-igc-libs-1.0.12037.1-1.fc37.x86_64
  - nothing provides libopencl-clang.so.14()(64bit) needed by intel-igc-libs-1.0.12037.1-1.fc37.x86_64
(try to add '--skip-broken' to skip uninstallable packages).
```
Suggestion to try has no effect. As a consequence `intel-opencl` cannot be installed.

**Comment by frantisekz** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=2129791 and https://github.com/intel/intel-graphics-compiler/issues/263 .

**Comment by Ricky-Tigg** [comment]
THen a duplicate.

**Comment by Ricky-Tigg** [comment]
That means a duplicate.

**Comment by Ricky-Tigg** [comment]
That means a duplicate.
