### ISSUE TITLE
Suspected error in visa_header documentation

### ISSUE THREAD

**Issue by Pennycook** [intel/intel-graphics-compiler#269]
The visa_header documentation shows the following as the text format for address variables ([here](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/visa/4_visa_header.md?#address_info)):

> .decl var_name v_type=A type=<data_type> num_elts=<num_elements>

The `address_info` struct doesn't have a data type field, and trying to use the format above gives a compiler error.  Should it be:

> .decl var_name v_type=A num_elts=<num_elements>

**Comment by Wei-Chen-Intel** [comment]
Yes, address variables must be have Type_UW and the assembly syntax does not support a type specifier. We will fix the specification

**Comment by mnaczk** [comment]
Major vISA documentation update was made by the commit https://github.com/intel/intel-graphics-compiler/commit/535d40a879a078e1bc9703de096f407cd663d897

@Pennycook Please close the issue if this resolves the problem.

**Comment by Pennycook** [comment]
LGTM.  Thanks!
