### ISSUE TITLE
Build error: 

### ISSUE THREAD

**Issue by arihannu** [intel/intel-graphics-compiler#271]
When building the latest master (as of Dec 9 2022) with MinGW64-gcc/g++ (== C:\msys64\mingw64\bin\c++.exe) on Windows, I get this error:

```
../intel-graphics-compiler/visa/iga/IGALibrary/strings.hpp: In function 'size_t iga::stringLength(const char*)':
../intel-graphics-compiler/visa/iga/IGALibrary/strings.hpp:53:12: error: '::strlen_s' has not been declared; did you mean 'strnlen_s'?
   53 |   return ::strlen_s(str, N);
      |            ^~~~~~~~
      |            strnlen_s
```

If I revert back to c5af6780b1633d45965a983fcc58524c7af772bb, it builds fine.

**Comment by mnaczk** [comment]
Thanks for spotting the issue. Fixed in commit https://github.com/intel/intel-graphics-compiler/commit/b7a5e784bf6738c1f3395fcb007c8458863e475c 
Can you please confirm if this commit works for you?

**Comment by eero-t** [comment]
@arihannu Can you confirm whether the indicated commit fixes your issue, and if yes, could you close this ticket?

**Comment by mnaczk** [comment]
Closed as resolved. @arihannu Please reopen if there is still something to fix.
