### ISSUE TITLE
offline compiler for compiling vulkan spir-v

### ISSUE THREAD

**Issue by ramcn** [intel/intel-graphics-compiler#272]
Hello team,

Is there a tool which can be used to compile a vulkan SPIR-V to generate the intel disassembly? Like RGA tool of AMD or MALIOC of ARM.

I tried ocloc, but it crash when i tried compiling the vulkan SPIR-V. Any other tools that can be used.

**Comment by pszymich** [comment]
Hi @ramcn, IGC (and Compute Runtime) supports only OpenCL and so far there are no plans to add support for any render APIs.
For other open-source driver that support Vulkan you can try the Mesa driver ([official homepage](https://www.mesa3d.org/)), however I do know know what tooling they provide.

You can open a new issue with more details like error log and reproduction steps. If the problem happens to be not Vulkan specific we may be able to help.
