### ISSUE TITLE
What is the new process with tags?

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/intel-graphics-compiler#276]
Hi there,

While I’ve been away for some months (w.r.t. ArchLinux packaging), I see that now in addition to releases they are numerous tags being made to the repo. It seems that the current release does not build with LLVM 15, while more recent tags can (when you add some more patches, https://github.com/intel/intel-graphics-compiler/commit/c707d1e2244aec988bdd5d2a7473ef3a32a5bac7, https://github.com/intel/intel-graphics-compiler/commit/d1761dfc3ca6b54bac0ee213389a65f84d2aa9b7 and https://github.com/intel/intel-graphics-compiler/commit/e09e752949e7af0231884d1b11ea907e3e8b1611). Should we package the latest tag?

**Comment by ArchangeGabriel** [comment]
OK, thanks for the explanation. In the case of LLVM15, the current release required way too much backports to build, so I instead went with the 12812 branch. But I’ll definitively switch and try to keep it on official release in the future. ;)

**Comment by eero-t** [comment]
@pszymich IHMO development tags should be named so that they can be easily differentiated from release tags.  They could be e.g. post-fixed with some "-rcX" string.
