### ISSUE TITLE
Make failed...

### ISSUE THREAD

**Issue by EricksonLu** [intel/intel-graphics-compiler#28]
I followed the instruction cloned the release_40 llvm.
```
Example command:
$ git clone -b release_40 https://github.com/llvm-mirror/clang clang_source
$ git clone https://github.com/intel/opencl-clang common_clang
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone -b release_40 https://github.com/llvm-mirror/llvm llvm_source
$ git clone https://github.com/intel/intel-graphics-compiler igc
$ git clone https://github.com/KhronosGroup/OpenCL-Headers opencl_headers

```

But, I got make faied as below. I think the llvm release_40 branch doesn't have 
`class llvm::FastMathFlagsthe `function `isFast`. So, I think you should update your Readme.md file, tell us your master branch used specific llvm branch, otherwise do as the Readme said we cannot build it. 

Thanks...
```
igc/IGC/Compiler/CustomUnsafeOptPass.cpp:105:69: error: ‘class llvm::FastMathFlags’ has no member named ‘isFast’
     if(llvm::isa<llvm::FPMathOperator>(op) && op.getFastMathFlags().isFast())

```

**Comment by EricksonLu** [comment]
And when I git checkout the llvm source to release_60 and use cmake to re-generate the project, the llvm patch file cannot aply 
```
Apply /home/shan/Music/OpenCL_Open_Intel/llvm_patches/releases/4.0.0/patches_external/2_1-enable-aggressive-combining.patch file
patching file lib/Transforms/InstCombine/InstructionCombining.cpp
Hunk #1 FAILED at 1573.
1 out of 1 hunk FAILED -- saving rejects to file lib/Transforms/InstCombine/InstructionCombining.cpp.rej
CMake Error at /home/shan/Music/OpenCL_Open_Intel/llvm_patches/CMakeLists.txt:189 (message):
  error: applying patch
  '/home/shan/Music/OpenCL_Open_Intel/llvm_patches/releases/4.0.0/patches_external/2_1-enable-aggressive-combining.patch'
  failed

```

**Comment by paigeale** [comment]
Hello EricksonLu,

Thanks for reporting this issue. Our compiler team will take a look and see if we can reproduce this issue.

**Comment by iwwu** [comment]
Hi EricksonLu,

Thank you for reporting this. We will take a look and get back to you what we find.

**Comment by iwwu** [comment]
Can you try again using tag 'igc_release_2018-11-15' ? The build went fine for me.

FYI, I was using release_40 llvm

**Comment by EricksonLu** [comment]
Hi iwwu,
I it's done, I think you should update your README.md and mention that.
