### ISSUE TITLE
Running Intel Graphics Assembler (iga) output on GPU

### ISSUE THREAD

**Issue by sahilsihag** [intel/intel-graphics-compiler#281]
I want to run a file assembled using Intel Graphics Assembler (`iga`) on Intel GPUs. To explain further:
- Write GEN assembly in a file. Say `file.asm`
- Assemble file using Intel Graphics Assembler. `$ iga file.asm -p=8 -a -o file.krn`
- How can I run `file.krn` on the GPU?

**Comment by trbauer** [comment]
This is not supported.

**Comment by pszymich** [comment]
Adding to @trbauer, we do not have any plans on extending the functionality to support assembly programming.
