### ISSUE TITLE
intel_sub_group_shuffle

### ISSUE THREAD

**Issue by MaximMilashchenko** [intel/intel-graphics-compiler#286]
I was looking into the implementation of the intel_sub_group_shuffle function and came across the __builtin_IB_simd_shuffle function. I found the function definition in /intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Implementation/IGCBiF_Intrinsics.cl. Where can I find an implementation of the  __builtin_IB_simd_shuffle function?

**Comment by mnaczk** [comment]
Hi, 
`__builtin_IB_simd_shuffle` is 'resolved' to `GenISAIntrinsic::GenISA_WaveShuffleIndex` in https://github.com/intel/intel-graphics-compiler/blob/dcbc878f9f29bcaea4cd70132601c148a333c5e4/IGC/Compiler/Optimizer/OpenCLPasses/SubGroupFuncs/SubGroupFuncsResolution.cpp#L37 and https://github.com/intel/intel-graphics-compiler/blob/dcbc878f9f29bcaea4cd70132601c148a333c5e4/IGC/Compiler/Optimizer/OpenCLPasses/SubGroupFuncs/SubGroupFuncsResolution.cpp#L600

The implementation of  `GenISAIntrinsic::GenISA_WaveShuffleIndex` can be found in EmitVISAPass.cpp https://github.com/intel/intel-graphics-compiler/blob/dcbc878f9f29bcaea4cd70132601c148a333c5e4/IGC/Compiler/CISACodeGen/EmitVISAPass.cpp#L4657

Please close the issue if this is the answer to your question.
