### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [intel/intel-graphics-compiler#288]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by mnaczk** [comment]
Hello,

Thank you for reaching out to us. If you have identified a potential vulnerability and would like to share it with us, we kindly ask that you follow the guidelines outlined in our SECURITY.md file, which can be found at the following URL: https://github.com/intel/intel-graphics-compiler/blob/master/SECURITY.md 

Please let us know if you have any further questions or concerns.
