### ISSUE TITLE
Invalid output while running UNet on Intel ARC

### ISSUE THREAD

**Issue by nithinsubbiah** [intel/intel-graphics-compiler#290]
Hello, I'm trying to run a Stable Diffusion model on Intel ARC using IREE (https://github.com/openxla/iree) which is a MLIR based compiler/runtime for ML workloads. While trying to compile and run a UNet model, which is a part of Stable Diffusion, through the Vulkan backend I got invalid `Nan` values as output.

I'm attaching the issue here (https://github.com/openxla/iree/issues/13009) which has more details. We think that this might be because of ARC driver issue. 

Any help with this will be appreciated, thanks!

**Comment by pszymich** [comment]
Hi @nithinsubbiah, this repository tracks open-source Intel Graphics Compiler development for Linux compute workloads only.
For reporting issues with Windows driver, please have a look here: https://www.intel.com/content/www/us/en/support/articles/000057021/graphics.html
