### ISSUE TITLE
cmake compile error

### ISSUE THREAD

**Issue by YMont** [intel/intel-graphics-compiler#291]
Hi All,

I meet compile error, but I don't know how to fix it.
OS: Ubuntu 22.04 (Linux kernel: 5.19.0-41)
CPU: i3-9100E
`$ cmake ../igc`
![image](https://github.com/intel/intel-graphics-compiler/assets/58437649/7295a962-7999-4929-80d3-fa6f96837000)
Thanks a lot.

**Comment by AGindinson** [comment]
Hi @YMont,

Could you please share the full `cmake` configuration command / LLVM version that you'd like to build against?

**Comment by pszymich** [comment]
Closing stale issue.
