### ISSUE TITLE
Intel graphics compiler fails to build

### ISSUE THREAD

**Issue by ht990332** [intel/intel-graphics-compiler#293]
cmake -B build -S intel-graphics-compiler \
    -G 'Unix Makefiles' \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DIGC_OPTION__ARCHITECTURE_TARGET='Linux64' \
    -DIGC_OPTION__LINK_KHRONOS_SPIRV_TRANSLATOR=ON \
    -DIGC_OPTION__SPIRV_TOOLS_MODE=Prebuilds \
    -DIGC_OPTION__SPIRV_TRANSLATOR_MODE=Prebuilds \
    -DIGC_OPTION__LLVM_MODE=Prebuilds \
    -DIGC_OPTION__USE_PREINSTALLED_SPRIV_HEADERS=ON \
    -DIGC_OPTION__VC_INTRINSICS_MODE=Prebuilds \
    -DIGC_OPTION__LLVM_PREFERRED_VERSION=16.0.6 \
    -DINSTALL_GENX_IR=ON \
    -Wno-dev
[build.log](https://github.com/intel/intel-graphics-compiler/files/11908108/build.log)

**Comment by vmustya** [comment]
IGC doesn't support LLVM-16 yet: https://github.com/intel/intel-graphics-compiler/issues/289. Please build it against LLVM-14.

**Comment by ht990332** [comment]
It depends on other components that are already built using llvm16.
I'll need to wait then.

**Comment by ht990332** [comment]
Are there any instructions on compiling intel-graphics-conpiler without any prebuilts?

**Comment by pszymich** [comment]
Hi @ht990332, yes, see here: https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md#build-from-sources

**Comment by ht990332** [comment]
Hello. No. Not yet. It keeps looking for projectd in unexpected places. However, if you are properly tracking it elsewhere, please close this bug.On 8/18/23, 11:59 Artem Gindinson ***@***.***> wrote:

   
  Hi @ht990332, was the source-based build successful? Can we close this issue, given that LLVM 16 support is being tracked in #289?

**Comment by AGindinson** [comment]
@ht990332, just to clarify, do these errors persist with LLVM 14-based components (as per @vmustya/@pszymich's advice) and CMake options updated to something like below for source-based build?
```
-DIGC_OPTION__SPIRV_TRANSLATOR_MODE=Source
-DIGC_OPTION__LLVM_MODE=Source
-DIGC_OPTION__VC_INTRINSICS_MODE=Source
-DIGC_OPTION__LLVM_PREFERRED_VERSION=14.0.5
```

**Comment by pszymich** [comment]
@ht990332 if you check @AGindinson 's tips and further problems emerge please reopen.
