### ISSUE TITLE
link in README to 01.org is broken

### ISSUE THREAD

**Issue by dneto0** [intel/intel-graphics-compiler#295]
>  Please refer to http://01.org/compute-runtime for additional details regarding Intel's motivation and intentions wrt OpenCL support in the open source.

It looks like Intel has moved all the programmer documentation away from 01.org.
So this link in the  README is broken.

**Comment by lab596** [comment]
Hey, I found the following page on Intel's website: https://www.intel.com/content/www/us/en/developer/articles/guide/sdk-for-opencl-2017-gsg.html

Please let me know if this is a more fitting site for the Intel SDK for OpenCL overview. If given a chance I would like the opportunity to update the readme if this is an approved change. I think linking the existing site as well as the one provided above will provide better context for both open source and OpenCL. Thanks.

**Comment by pszymich** [comment]
Hi, we've considered your suggestions in recent commit: https://github.com/intel/intel-graphics-compiler/commit/f13266aaa66b63df780e0c217f73ec3b670db218
Thanks!
