### ISSUE TITLE
No Ubuntu 22.04 support? 

### ISSUE THREAD

**Issue by pvelesko** [intel/intel-graphics-compiler#308]
The README states that Ubuntu 22.04 is not supported. I was able to install on

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

Linux cupcake 5.17.0-1019-oem #20-Ubuntu SMP PREEMPT Tue Sep 27 13:20:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Is README out of date or are there known issues 22.04?

**Comment by pszymich** [comment]
Hi, we've updated the README to more accurately describe the OSes supported. We currently build and test on 20.04 and 22.04.
