### ISSUE TITLE
Built with llvm-spirv-14 provided by apt results in  IGC: Internal Compiler Error: Abnormal termination

### ISSUE THREAD

**Issue by pvelesko** [intel/intel-graphics-compiler#309]
Originally reported here (more info): https://github.com/CHIP-SPV/chipStar/issues/725 

The crux of the issue seems that the version provided by apt is a bit outdated. I was able to resolve this by compiling and installing LLVM-SPIRV-Translator from scratch. Perhaps a note in the README would be helpful.

**Comment by pszymich** [comment]
Hi, we've considered your suggestions in a recent commit: https://github.com/intel/intel-graphics-compiler/commit/f13266aaa66b63df780e0c217f73ec3b670db218
Thanks!

**Comment by eero-t** [comment]
Regarding the text:
> Also, depending on the Ubuntu release, SPIRV-LLVM-Translator available through apt may be older than required.

(Added to: https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md)

I think build configuration phase should check that versions of the dependencies are new enough.

After that, more important would be to state something like this:
> **LLVM versions and pre-built IGC dependencies**
>
> Ubuntu offers packages for multiple LLVM versions, but packages for IGC dependencies are built only with one version.  Because LLVM ABI changes between versions and linking mismatching versions would cause build, test or run-time errors, using distro packages for dependencies means that IGC must be built with the same LLVM version as what all of its pre-built dependencies used.
> 
> LLVM version used for those dependencies in different Ubuntu versions, and IGC support for those LLVM versions  can affect the resulting compiler stack quality: https://github.com/intel/intel-graphics-compiler/projects/5
