### ISSUE TITLE
Documentation link for Intel Graphics Media Accelerator Developer's Guide is broken

### ISSUE THREAD

**Issue by alexbaden** [intel/intel-graphics-compiler#312]
[1] Intel Graphics Media Accelerator Developer's Guide, http://software.intel.com/en-us/articles/intel-graphics-media-accelerator-developers-guide/.

lands at generic developers landing page, not developer's guide 

The C++ Compiler/Ref Guide link is also broken [3] Intel C++ Compiler User and Reference Guides, http://www.intel.com/cd/software/products/asmo-na/eng/347618.htm.

**Comment by eero-t** [comment]
This is not the correct place for reporting intel.com site content link issues.  Unfortunately I do not have good other suggestions either.  Maybe report it at the intel.com chat / feedback form?

**Comment by DDEle** [comment]
@pszymich It has been more than 8 months since the original raise of the problem. Any update to make the IGC documentation more user friendly?
