### ISSUE TITLE
Does this repo support Arc 770?

### ISSUE THREAD

**Issue by chsasank** [intel/intel-graphics-compiler#321]
I have been trying to compile this repo (see #313) because build.md in Intel/llvm instructed me to do so. I am using Intel Arc 770 GPU but the readme here says only integrated GPUs are supported. I have searched for xe_hpg in the repo and found some hits. Does this Arc 770 is supported as well?

**Comment by pszymich** [comment]
Hi, yes. The readme is out of date. Updating the document is trailing in our backlog with low priority.
IGC supports all platforms from Gen9 to newest products, including DG2 512 (Arc 770) and will continue supporting upcoming launches.
