### ISSUE TITLE
Provide installation support for the IGC

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#33]
Please, remove custom -DIGC_OPTION__OUTPUT_DIR and provide installation support for the IGC targets. On Linux, please, use https://cmake.org/cmake/help/v3.6/module/GNUInstallDirs.html and standard variables provided with this module. You can refer to this for example: https://github.com/intel/media-driver/blob/master/CMakeLists.txt

Essentially, work with the IGC package should look somehow like (assuming you will use cmake):
```
cmake -DCMAKE_INSTALL_PREFIX=/my/custom/prefix -DCMAKE_INSTALL_LIBDIR=/my/custom/libdir /path/to/igc
make -j8
make install
```

**Comment by paigeale** [comment]
Issue should be addressed with cb807eea69dc038e29acf9c7fc3950535b135a11
