### ISSUE TITLE
Need help for using IGC and NEO

### ISSUE THREAD

**Issue by yonghaek** [intel/intel-graphics-compiler#335]
Thanks for the great work.
I am currently trying to use IGC for a research purpose.
What I am hoping to do is to develop a custom LLVM opt pass in the IGC LLVM framework
and apply that pass when compiling OpenCL compute applications.

I was able to build the IGC without an issue but still wondering how to actually use it.
I am sorry if this is not the right place to ask.
I have also checked out the compute-runtime repo (NEO) and successfully built it.
However, I still have no idea how to use these frameworks for my usecase.

Could you please provide any advice on this direction?

**Comment by pszymich** [comment]
Hi @yonghaek, you can use Level0 or OpenCL APIs to build kernels. Installed NEO runtime calls IGC for the compilation task, then dispatches these to the GPU. This is called online or JIT compilation. If you have SPIRV or OpenCL-C input file you can also use the `ocloc` package from NEO to run ahead-of-time offline compilation.
