### ISSUE TITLE
RFE: please update igc for latest LLVM

### ISSUE THREAD

**Issue by kloczek** [intel/intel-graphics-compiler#339]
Currently igc can be compiled only against ancient llvm 14.

Please start update for latest 18 or already branched 19.

**Comment by frantisekz** [comment]
Fedora is shipping igc built against LLVM 15 which works just fine, and relevant discussion is at #289 for updates and progress.

**Comment by kloczek** [comment]
Yes and it i ONLY package which still needs LLVM 15 binaries.

**Comment by pszymich** [comment]
Closing as duplicate of #289. Please follow that issue for updates.
