### ISSUE TITLE
Remove mandatory -DCMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#34]
Please, remove mandatory -DCMAKE_BUILD_TYPE and default it to Release inside your cmake files if it is not defined by the user.

**Comment by iwwu** [comment]
work in progress. I will update when it is available.

**Comment by iwwu** [comment]
Request completed. Please use latest code or tag 'igc_release_2018-12-12'. README is updated as well.

**Comment by dvrogozh** [comment]
@iwwu. I have strong suggestion to you. Please, start add "Fixes: #xxx" to commit messages if you fix github issues. For example, this commit https://github.com/intel/intel-graphics-compiler/commit/03dd5d52a92c4defab206e88209ce9c770373497 should actually have this commit message:
```
Remove CMAKE_BUILD_TYPE & IGC_OPTION__ARCHITECTURE_TARGET from Cmake cmd

Fixes: #32, #34

CMAKE_BUILD_TYPE is set to Release by default
IGC_OPTION__ARCHITECTURE_TARGET is self detected.

Change-Id: I55cc63051f0b36a60b370e1894258a9f2d309160
```

There are the following reasons to that:
1. People will easily see which issues are fixed in the log and be able to go to the discussion
2. GitHub will automatically update the issue that commit appeared referencing it. Thus, people monitoring issues list will see that something has changed/going on.
3. GitHub will automatically close the issue if it will see this line (if issue is not fixed author will reopen - that's his responsibility)

**Comment by dvrogozh** [comment]
@iwwu : Another suggestion is to submit PRs on the GitHub. You should give a chance for people to review/comment/try.

**Comment by dvrogozh** [comment]
works for me. thank you.
