### ISSUE TITLE
Broken Links in the vISA Doc

### ISSUE THREAD

**Issue by DDEle** [intel/intel-graphics-compiler#346]
In [documentation/visa/1_introduction.md](https://github.com/intel/intel-graphics-compiler/blob/59e2807ff3daed14f9a56fecd15f0f0badfc6260/documentation/visa/1_introduction.md#references-and-related-information), both links for _Intel Graphics Media Accelerator Developer's Guide_ and _Intel C++ Compiler User and Reference Guides_ are broken.

**Comment by pszymich** [comment]
Duplicate of https://github.com/intel/intel-graphics-compiler/issues/312
