### ISSUE TITLE
IGC v2.1.12 prebuilt debs not longer support Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by nyanmisaka** [intel/intel-graphics-compiler#350]
IGC [README](https://github.com/intel/intel-graphics-compiler/blob/master/README.md#supported-linux-versions) says that both 22.04 and 24.04 are supported.

But when installing them on Ubuntu 22.04 LTS:
```
The following packages have unmet dependencies:
 intel-igc-core-2 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
 intel-igc-opencl-2 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
```

The packages built on Ubuntu 24.04 require a higher `glibc` version, which makes them not backward compatible with Ubuntu 22.04 LTS. Many users are still using it, please consider restoring support for it.

https://github.com/intel/intel-graphics-compiler/releases/tag/v2.1.12
https://github.com/intel/compute-runtime/releases/tag/24.45.31740.9
https://github.com/intel/compute-runtime/issues/770#issuecomment-2516644038

**Comment by GermanAizek** [comment]
Debian Testing Linux debian 6.12.5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.5-1 (2024-12-15) x86_64 GNU/Linux


```
$ sudo apt install intel-opencl-icd
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 intel-opencl-icd : Depends: libigc1 (< 1.0.17537.20+~) but 1.0.17791.18-1 is to be installed
                    Depends: libigdfcl1 (< 1.0.17537.20+~) but 1.0.17791.18-1 is to be installed
Error: Unable to correct problems, you have held broken packages.
```

**Comment by nyanmisaka** [comment]
Fixed in the latest igc2 releases.
