### ISSUE TITLE
keep a copy of khronos headers

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#37]
Can this program/library do something with the headers?  Keep a copy of the version supported or add them as a git submodule?  This will result on a building experience less complex.

**Comment by iwwu** [comment]
A copy of opencl_headers is required by our BiFModule compilation. We'll evaluate the request and keep you updated.

**Comment by iwwu** [comment]
I will need to make 1 more change to switch the code using the default copy of opencl_headers. Once the change is made, I will update README.

**Comment by iwwu** [comment]
The user is no longer required to download opencl_headers separately. README is updated.
Available in igc_release_2019-01-15
