### ISSUE TITLE
Intel i3-i8300

### ISSUE THREAD

**Issue by jleitch2013** [intel/intel-graphics-compiler#39]
Linux system: i3-8300 cpu

I have compiled and installed the graphics compiler and clinfo gives me:

cl_get_gt_device(): error, unknown device: 3e91
cl_get_gt_device(): error, unknown device: 3e91
Number of platforms                               2
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 18.3.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel
cl_get_gt_device(): error, unknown device: 3e91

Any comments please?

**Comment by paigeale** [comment]
Hello jleitch2013,

I will have someone from the IGC team look into this shortly. In the meantime can you please include some additional details regarding the steps up to this point? Did you see any errors during the build or the install process?

Thanks,
Alex

**Comment by jleitch2013** [comment]
Hello Alex,
Good morning, and  thanks for your reply.
Here is some background to my question:
I am using Python 2.7 and starting to use the Quantum processing features in this language, with the Intel i3 i8300 CGU on my linux system , 64-bit ,( kernel 4.19.8-1-default #1 SMP PREEMPT)

I load the pyopencl library (>>> import pyopencl as  cl,  numpy)
 try and select a context with >>>ctx  = cl.create_some_context()
and I am offered the platform:Choose platform: [1] <pyopencl.Platform 'Intel Gen OCL Driver' at 0x7f7020ea6c60>

The response is: cl_get_gt_device(): error, unknown device: 3e91
Running oscli on the command line confirms this, gives me the response sent previously.
The Intel graphics compiler was downloaded from github, the dependencies also downloaded following the instructions given, and the compilation completed with only a few minor warnings. The installtion was completed without any errors.
However Python apparently does not seem to recognise the hardware!
I was surprised there was not any installation script (python.setup) to be run to tell Python about the CGU, however this may just  be my understanding, and not necessary.
Thanks for your assistance.

Regards
James
Dr. James R. Leitch, CSci, CPhys
 
  

    On Wednesday, 9 January 2019, 01:35:37 GMT, Alex Paige <notifications@github.com> wrote:  
 
 
Hello jleitch2013,

I will have someone from the IGC team look into this shortly. In the meantime can you please include some additional details regarding the steps up to this point? Did you see any errors during the build or the install process?

Thanks,
Alex

**Comment by paigeale** [comment]
Hello James,

After evaluating your issue further it appears that you need to install the new Intel Graphics Compute Runtime for OpenCL located here (https://github.com/intel/compute-runtime). The legacy runtime that you have installed currently (Beignet) is not supported for your machine with the latest igc driver. Please follow the installation steps located on the the compute-runtime ReadMe and let me know if you have any additional question or problems during setup.

Thanks,
Alex

**Comment by ArturHarasimiuk** [comment]
Hi James,

it looks like you python still trying to use Beignet driver. Error message:
```
cl_get_gt_device(): error, unknown device: 3e91
```
comes from Beignet.

can you share output from command: `ls -l /etc/OpenCL/vendors/`?
could you install clinfo in your system and check whether it reports
```
Device Name                                     Intel(R) Gen9 HD Graphics NEO
```

I tried your python code, here is my output:
```
# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl, numpy
>>> a = numpy.random.rand(256**3).astype(numpy.float32)
>>> ctx = cl.create_some_context()
Choose platform:
[0] <pyopencl.Platform 'Intel Gen OCL Driver' at 0x7f92d98da4e0>
[1] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x252eb00>
[2] <pyopencl.Platform 'Portable Computing Language' at 0x7f92d3730020>
Choice [0]:1
Set the environment variable PYOPENCL_CTX='1' to avoid being asked again.
>>>
```
As you can see I have more than one platform installed and it works. but this may be hint: `PYOPENCL_CTX='1'`. do you have this environment variable set?

regards,
Artur

**Comment by paigeale** [comment]
Hello James,

Were you able to resolve your issue with Arutur's help? If so, please close this issue or provide additional information suggested by Artur.

Thanks,
Alex Paige

**Comment by jleitch2013** [comment]
Hello Alex,
No I haven’t been able to resolve it yet.

I have been travelling for the last few weeks, but will try again when I return.

Thanks for your patience

James

**Comment by paigeale** [comment]
Any update James?

**Comment by jleitch2013** [comment]
Hi,
Thanks for following up.

No, I haven’t been able to resolve this so far!
I’ll spend some time in the next two weeks to
Try again

Thanks

**Comment by paigeale** [comment]
Hello James,

I am going to close this issue so we can clear our board of stale items. If this is still an issue please reopen and we will take a look.

Thanks,
Alex
