### ISSUE TITLE
Build failure for GenISA Intrinsics.

### ISSUE THREAD

**Issue by ssarangi** [intel/intel-graphics-compiler#4]
The instructions for building GenISA Intrinsics aren't there and running the cmake and make command in the documentation results in the build failure for GenISA Intrinsics.

recipe for target 'GenISAIntrinsics/CMakefiles/GenISAIntrinsics.dir/all' failed.

**Comment by pguo-igc** [comment]
Thank you Satyagit, it's a cmakefile issue with relative output path, and last commit should fix it.

**Comment by ssarangi** [comment]
This was with the latest commit...

**Comment by pguo-igc** [comment]
Did you clean the build directory before running cmake again?  The fix relates to a cached cmake variable.

**Comment by ssarangi** [comment]
yeah the build directory was clean. It was the tip of tree but still build failed.

**Comment by pguo-igc** [comment]
It's weird, let me do more testing and get back later.

**Comment by pguo-igc** [comment]
Could you try cmake config with an absolute path for IGC_OPTION__OUTPUT_DIR?

**Comment by AnupamaChandrasekhar** [comment]
Can you check now? I7376783521228493f2d894cf807e7124072e4314 should fix it.
