### ISSUE TITLE
cmake errors

### ISSUE THREAD

**Issue by fiorano10** [intel/intel-graphics-compiler#42]
I have the required file structure, running on 8700T, Ubuntu 16.04. Keep getting this error, and llvm7 is no longer available from apt.

`CMake Warning at CMakeLists.txt:1908 (message):
  CMAKE_BUILD_TYPE: Unknown build configuration.  The following
  configurations are available: Debug;ReleaseInternal;Release.

  The "Release" configuration will be used.

  This value has meaning only for single-configuration generators (like
  Make).  It will be ignored for MSVC/XCode.

CMake Warning (dev) at CMakeLists.txt:2050 (set):
  Cannot set "IGC_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:2059 (set):
  Cannot set "FCL_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

 IGC Project
 Build type:  Release (single-configuration generator)
Build tools: OFF
 LLVM dir:    

Output directory:
-  "/home/burro/graphics_compiler/igc/igc-install/Release"
 Install root directory:
 "/usr/local"
Architecture:
 - target: Linux64    (detected: Linux64)
- host:   Linux64    (detected: Linux64)
Cross-compilation needed: NO
Cross-compilation set:    FALSE
-
-Advanced:
- Link BiF resources:              ON
- Building Windows Universal:      

CMake Warning at CMakeLists.txt:2196 (message):
  not defined, defaulting to y: UFO_VK

 [IGC] LLVM targets are not defined. Searching for LLVM.
CMake Warning at CMakeLists.txt:3262 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "7.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-9/cmake/LLVMConfig.cmake, version: 9.0.0
    /usr/lib/llvm-4.0/cmake/LLVMConfig.cmake, version: 4.0.0

-[IGC] LLVM compilation from /home/burro/graphics_compiler/igc/IGC/../../llvm_patches
- LLVM_SOURCE_URL   = /home/burro/graphics_compiler/llvm_patches/../llvm7.0.0_source
-- LLVM_OPTIONS      = -DLLVM_TARGETS_TO_BUILD=;-DLLVM_BUILD_TOOLS=true;-DLLVM_INCLUDE_TOOLS=true;-DLLVM_INSTALL_UTILS=false;-DLLVM_INCLUDE_UTILS=false;-DLLVM_BUILD_EXAMPLES=false;-DLLVM_INCLUDE_EXAMPLES=false;-DLLVM_BUILD_TESTS=false;-DLLVM_INCLUDE_TESTS=false;-DLLVM_APPEND_VC_REV=false;-DLLVM_ENABLE_THREADS=true;-DLLVM_ENABLE_CXX1Y=false;-DLLVM_ENABLE_PIC=true;-DLLVM_ENABLE_WARNINGS=true;-DLLVM_ENABLE_PEDANTIC=true;-DLLVM_ENABLE_WERROR=false;-DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF;-DLLVM_BUILD_RUNTIME=true;-DLLVM_ENABLE_TERMINFO=false;-DLLVM_ENABLE_EH=true;-DLLVM_ENABLE_RTTI=true;-DLLVM_BUILD_32_BITS=false
-- LLVM_BUILD_TYPE   = Release
-- [LLVM] PYTHON_EXECUTABLE = /usr/bin/python2
-- [LLVM] Clearing build system compilation flags
-- Native target X86 is not selected; lli will not JIT code
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- OCaml bindings disabled, need ctypes >=0.4.
-- Found Python module pygments
-- Found Python module pygments.lexers.c_cpp
-- Found Python module yaml
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- [LLVM] Restoring build system compilation flags
-- SPIRV-Tools: nosetests found - python support code will be tested
-- Precompiled common clang bundle /home/burro/graphics_compiler/igc/IGC/../Clang/Prebuilt/linux-ubuntu/Release/64/clang.7z does not exist. Try to compile from sources.
-- Trigger common clang compilation from /home/burro/graphics_compiler/common_clang to /home/burro/graphics_compiler/igc/igc-install/Release/clang/linux-ubuntu64
CMake Error at /home/burro/graphics_compiler/common_clang/CMakeLists.txt:53 (include):
  include could not find load file:

    AddLLVM

CMake Error at /home/burro/graphics_compiler/common_clang/CMakeLists.txt:54 (include):
  include could not find load file:

    TableGen

-- No patches in /home/burro/graphics_compiler/common_clang/patches/clang
-- No patches in /home/burro/graphics_compiler/common_clang/patches/spirv
CMake Error at /home/burro/graphics_compiler/build/llvm/src/cmake/modules/LLVM-Config.cmake:31 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  /home/burro/graphics_compiler/build/llvm/src/cmake/modules/LLVM-Config.cmake:253 (is_llvm_target_library)
  /home/burro/graphics_compiler/build/llvm/src/cmake/modules/AddLLVM.cmake:544 (llvm_map_components_to_libnames)
  /home/burro/graphics_compiler/build/llvm/src/cmake/modules/AddLLVM.cmake:620 (llvm_add_library)
  /home/burro/graphics_compiler/common_clang/CMakeLists.txt:231 (add_llvm_library)

-- Configuring Intel Gen Assembler (IGA) Component
--  - GED_BRANCH:           GED_external
--  - CMAKE_CXX_COMPILER:   /usr/bin/c++
INFOLIT tests not enabled. Missing igc_opt target.
-- Configuring incomplete, errors occurred!`

**Comment by iwwu** [comment]
Please use this for common_clang checkout.
git clone **-b ocl-open-40** https://github.com/intel/opencl-clang common_clang

The change is reflected on the README now

**Comment by fiorano10** [comment]
New errors:
`-- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- [LLVM] Restoring build system compilation flags
-- SPIRV-Tools: nosetests found - python support code will be tested
-- Precompiled common clang bundle /home/burro/catkin_ws/external/workspace/igc/IGC/../Clang/Prebuilt/linux-ubuntu/Release/64/clang.7z does not exist. Try to compile from sources.
-- Trigger common clang compilation from /home/burro/catkin_ws/external/workspace/common_clang to /home/burro/catkin_ws/external/workspace/igc/igc-install/Release/clang/linux-ubuntu64
-- LLVM_SOURCE_URL        = /home/burro/catkin_ws/external/workspace/common_clang/../llvm_source
-- CLANG_SOURCE_URL       = /home/burro/catkin_ws/external/workspace/common_clang/../clang_source
-- CCLANG_LIB_NAME        = cclang
-- CCLANG_SOURCE_URL      = /home/burro/catkin_ws/external/workspace/common_clang/cclang
-- CCLANG_OCL_HEADERS_DIR = /home/burro/catkin_ws/external/workspace/igc/IGC/../third_party/opencl_headers
-- CCLANG_BUILD_TYPE      = Release
-- CCLANG_INSTALL_DIR     = /home/burro/catkin_ws/external/workspace/build/BiFModule/clang_build/install
-- CCLANG_OPTIONS         = -DBUILD_X64:BOOL=ON;-DLLVM_USE_INTEL_JITEVENTS:BOOL=ON;-DLLVM_USE_LINKER:STRING=gold;-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-4.0;-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-4.0;-DLLVM_OPTIMIZED_TABLEGEN=ON;-DLLVM_TARGETS_TO_BUILD='X86';-DCOMMON_CLANG_LIBRARY_NAME:STRING=opencl_clang
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:964 (message):
  error: do not know how to extract
  '/home/burro/catkin_ws/external/workspace/common_clang/../llvm_source' --
  known types are .7z, .tar, .tar.bz2, .tar.gz, .tar.xz, .tbz2, .tgz, .txz
  and .zip
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1909 (_ep_write_extractfile_script)
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  /home/burro/catkin_ws/external/workspace/common_clang/CMakeLists.txt:235 (ExternalProject_Add)


-- Configuring Intel Gen Assembler (IGA) Component
--  - GED_BRANCH:           GED_external
--  - CMAKE_CXX_COMPILER:   /usr/bin/c++
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.0") 
INFOLIT tests not enabled. Missing igc_opt target.
-- Configuring incomplete, errors occurred!
`

**Comment by GBuella** [comment]
> CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:964 (message): error: do not know how to extract
>'/home/burro/catkin_ws/external/workspace/common_clang/../llvm_source'

Are you sure the `/home/burro/catkin_ws/external/workspace/common_clang/../llvm_source` directory exists?

**Comment by iwwu** [comment]
@fiorano10 
Please try this again. Make sure you have both llvm_source and llvm7.1.0_source cloned.

$ git clone -b release_40 https://github.com/llvm-mirror/clang clang_source
$ git clone -b ocl-open-40 https://github.com/intel/opencl-clang common_clang
$ git clone https://github.com/intel/llvm-patches llvm_patches
    [If seeing LLVM7.1.0 issue, please do following]
    In CMakeLists.txt
    Change set(EXPECTED_LLVM_VERSION "7.0.0") to set(EXPECTED_LLVM_VERSION "7.1.0")
$ git clone -b release_40 https://github.com/llvm-mirror/llvm llvm_source
$ git clone -b release_70 https://github.com/llvm-mirror/llvm llvm7.1.0_source
$ git clone https://github.com/intel/intel-graphics-compiler igc

**Comment by iwwu** [comment]
@fiorano10 We updated our README to support clang7. Please give it a try.

**Comment by iwwu** [comment]
@fiorano10 Are you still seeing issue with our latest IGC code and README file?

**Comment by iwwu** [comment]
Did not hear from the user for few weeks. Please open new issue if seeing issue on latest repo and README.
