### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by feijiang1** [intel/intel-graphics-compiler#44]
Tire to build IGC on Ubuntu 16.04, according to the step in build wiki:
$ git clone -b release_40 https://github.com/llvm-mirror/clang clang_source
$ git clone https://github.com/intel/opencl-clang common_clang
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone -b release_40 https://github.com/llvm-mirror/llvm llvm_source
$ git clone -b release_70 https://github.com/llvm-mirror/llvm llvm7.0.0_source
$ git clone -b igc_release_2019-01-05 https://github.com/intel/intel-graphics-compiler igc;\
  git checkout -b igc_release_2019-01-05
$ mkdir build
$ cd build
$ cmake -DIGC_OPTION__OUTPUT_DIR=../igc-install/Release ../igc/IGC

I failed with following error, do you know how to fix such kind of problem?

-- [IGC] LLVM targets are not defined. Searching for LLVM.
-- [IGC] Using system LLVM 7.0.1
-- [IGC] Using static LLVM.
-- SPIRV-Tools: nosetests was not found - python support code will not be tested
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Precompiled common clang bundle /home/share/worksapce/opencl_compiling/igc/IGC/../Clang/Prebuilt/linux-ubuntu/Release/64/clang.7z does not exist. Try to compile from sources.
-- Trigger common clang compilation from /home/share/worksapce/opencl_compiling/common_clang to /home/share/worksapce/opencl_compiling/igc/igc-install/Release/clang/linux-ubuntu64
CMake Error at /home/share/worksapce/opencl_compiling/common_clang/CMakeLists.txt:53 (include):
  include could not find load file:

    AddLLVM

CMake Error at /home/share/worksapce/opencl_compiling/common_clang/CMakeLists.txt:54 (include):
  include could not find load file:

    TableGen

-- Found Git: /usr/bin/git (found version "2.7.4") 
-- /tools/clang:
-- /projects/llvm-spirv:
CMake Error at /home/share/worksapce/opencl_compiling/common_clang/CMakeLists.txt:112 (tablegen):
  Unknown CMake command "tablegen".

-- Configuring incomplete, errors occurred!

**Comment by lwesiers** [comment]
Hello there,

On the common_clang component there was a branch-out and we should use branch "ocl-open-40".
The correction in the README will appear soon.

in your setup correct please:
$ git clone https://github.com/intel/opencl-clang common_clang
to:
$ git clone -b ocl-open-40 https://github.com/intel/opencl-clang common_clang

Please let me know if this resolves your problem.

**Comment by feijiang1** [comment]
Thanks a lot for your info. Your correction can resolve my problem. Please help update the README.
