### ISSUE TITLE
file INSTALL cannot find ".../build_IGC/BiFModule/clang_build/src/docs/ocamldoc/html/.".

### ISSUE THREAD

**Issue by PlutusCN** [intel/intel-graphics-compiler#47]
I have followed the following steps to pull and compile code:

cd \<worksapce\>
git clone -b release_40 https://github.com/llvm-mirror/clang clang_source 
git clone -b ocl-open-40 https://github.com/intel/opencl-clang common_clang 
git clone https://github.com/intel/llvm-patches llvm_patches 
git clone -b release_40 https://github.com/llvm-mirror/llvm llvm_source 
git clone https://github.com/intel/intel-graphics-compiler 

mkdir build && cd build 
cmake -DIGC_OPTION__OUTPUT_DIR=../IGC-install/Release ../intel-graphics-compiler/IGC 
make -j4

Then, I got the error: 
```
         -- Up-to-date: /usr/lib/ocaml/llvm/llvm.mli
         CMake Error at bindings/ocaml/llvm/cmake_install.cmake:44 (file):
           file INSTALL cannot set permissions on "/usr/lib/ocaml/llvm/llvm.mli"
         Call Stack (most recent call first):
           bindings/ocaml/cmake_install.cmake:37 (include)
           cmake_install.cmake:61 (include)
           
         Makefile:126: recipe for target 'install' failed
         make[3]: *** [install] Error 1
         BiFModule/clang_build/CMakeFiles/cclang.dir/build.make:130: recipe for target 'BiFModule/clang_build/src/src/cclang-stamp/cclang-install' failed
         make[2]: *** [BiFModule/clang_build/src/src/cclang-stamp/cclang-install] Error 2
         CMakeFiles/Makefile2:1410: recipe for target 'BiFModule/clang_build/CMakeFiles/cclang.dir/all' failed
         make[1]: *** [BiFModule/clang_build/CMakeFiles/cclang.dir/all] Error 2
         Makefile:138: recipe for target 'all' failed
         make: *** [all] Error 2
```
So, I changed to: sudo make -j4 , but I got the error: 
```
         -- Up-to-date: /media/dengliqiang/DATADRIVE0/Dev/Intel/build_IGC/BiFModule/clang_build/install/bin/verify-uselistorder
         -- Up-to-date: /media/dengliqiang/DATADRIVE0/Dev/Intel/build_IGC/BiFModule/clang_build/install/bin/yaml2obj
         CMake Error at docs/cmake_install.cmake:36 (file):
           file INSTALL cannot find
           "/media/dengliqiang/DATADRIVE0/Dev/Intel/build_IGC/BiFModule/clang_build/src/docs/ocamldoc/html/.".
         Call Stack (most recent call first):
           cmake_install.cmake:68 (include)
           
         Makefile:126: recipe for target 'install' failed
         make[3]: *** [install] Error 1
         BiFModule/clang_build/CMakeFiles/cclang.dir/build.make:130: recipe for target 'BiFModule/clang_build/src/src/cclang-stamp/cclang-install' failed
         make[2]: *** [BiFModule/clang_build/src/src/cclang-stamp/cclang-install] Error 2
         CMakeFiles/Makefile2:1410: recipe for target 'BiFModule/clang_build/CMakeFiles/cclang.dir/all' failed
         make[1]: *** [BiFModule/clang_build/CMakeFiles/cclang.dir/all] Error 2
         Makefile:138: recipe for target 'all' failed
         make: *** [all] Error 2
```
I have already installed OCaml, but I don't know how to fix the error. 
Can anybody help me? Thanks a lot.

**Comment by PlutusCN** [comment]
@paigeale I tried as your advice, but the problem does still exist.

**Comment by PlutusCN** [comment]
I have commented line 68 in ../build_igc/BiFModule/clang_build/src/cmake_install.cmake : 
```
    # include("/media/dengliqiang/DATADRIVE0/Dev/Intel/build_igc/BiFModule/clang_build/src/docs/cmake_install.cmake")
```

Then, the problem is avoided, and I compiled and install them successfully.

**Comment by GBuella** [comment]
I found a similar issue with a little googling:
https://github.com/seahorn/crab-llvm/issues/13
Apparently, if the user has ocaml installed, LLVM's CMake scripts automatically enable the building of OCaml bindings -- which if we don't need, we should just make sure it is disabled.
Hopefully just explicitly adding `-DLLVM_ENABLE_BINDINGS=OFF` to the LLVM cmake invocation should solve it.

**Comment by iwwu** [comment]
@PlutusCN Are you able to workaround the issue with @GBuella suggestion?

**Comment by PlutusCN** [comment]
Actually,  I wanna build NEO that from Intel. I met this error when I compiling IGC which is a dependent component of NEO, so I asked the author of NEO and he who is so nice gave a solution. Please refer to: [Build and install IGC](https://github.com/JacekDanecki/compute-runtime/wiki/How-to-build-Neo-components)

**Comment by RohanDani2** [comment]
Do make ocaml_doc then sudo make install it worked for me
