### ISSUE TITLE
Error occurred while executing cmake in debug mode 

### ISSUE THREAD

**Issue by duttasankha** [intel/intel-graphics-compiler#48]
Hello 
I was install IGC as mentioned in the build instructions. However, I want to build the compiler in the debug. So first I downloaded all the dependencies and I have seen previous solution like [this one](https://github.com/intel/intel-graphics-compiler/issues/44) and so I downloaded _common clang_ using git _clone -b ocl-open-40 https://github.com/intel/opencl-clang common_clang_ . 
After downloading all the dependencies I executed the cmake command in the debug mode. The cmake command I used is  _cmake -DIGC_OPTION__OUTPUT_DIR=../igc-install/Debug -DCMAKE_BUILD_TYPE=Debug -DIGC_OPTION__ARCHITECTURE_TARGET=Linux64 ../igc/IGC_

However I got a LLVM error while doing the cmake. The whole console log after executing the cmake command is provided below:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:2050 (set):
  Cannot set "IGC_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:2059 (set):
  Cannot set "FCL_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

================================ IGC Project ================================
-- Build type:  Debug (single-configuration generator)
-- Build tools: OFF
-- LLVM dir:    
-- 
-- Output directory:
--    "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/igc/igc-install/Debug"
-- Install root directory:
--    "/usr/local"
-- Architecture:
--  - target: Linux64    (detected: Linux64)
--  - host:   Linux64    (detected: Linux64)
-- 
-- Cross-compilation needed: NO
-- Cross-compilation set:    FALSE

-- Advanced:
--  - Link BiF resources:              ON
--  - Building Windows Universal:      
-- =============================================================================
CMake Warning at CMakeLists.txt:2196 (message):
  not defined, defaulting to y: UFO_VK

-- [IGC] LLVM targets are not defined. Searching for LLVM.
CMake Warning at CMakeLists.txt:3271 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "7.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-4.0/cmake/LLVMConfig.cmake, version: 4.0.0

-- [IGC] LLVM compilation from /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/igc/IGC/../../llvm_patches
-- LLVM_SOURCE_URL   = /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/llvm_patches/../llvm7.0.0_source
-- LLVM_OPTIONS      = -DLLVM_TARGETS_TO_BUILD=;-DLLVM_BUILD_TOOLS=true;-DLLVM_INCLUDE_TOOLS=true;-DLLVM_INSTALL_UTILS=false;-DLLVM_INCLUDE_UTILS=false;-DLLVM_BUILD_EXAMPLES=false;-DLLVM_INCLUDE_EXAMPLES=false;-DLLVM_BUILD_TESTS=false;-DLLVM_INCLUDE_TESTS=false;-DLLVM_APPEND_VC_REV=false;-DLLVM_ENABLE_THREADS=true;-DLLVM_ENABLE_CXX1Y=false;-DLLVM_ENABLE_PIC=true;-DLLVM_ENABLE_WARNINGS=true;-DLLVM_ENABLE_PEDANTIC=true;-DLLVM_ENABLE_WERROR=false;-DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF;-DLLVM_BUILD_RUNTIME=true;-DLLVM_ENABLE_TERMINFO=false;-DLLVM_ENABLE_EH=true;-DLLVM_ENABLE_RTTI=true;-DLLVM_BUILD_32_BITS=false
-- Copying stock LLVM sources to /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/build/llvm/build/../src
Apply /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/llvm_patches/releases/7.0.0/patches_external/fix-pointer-for-lifetime-intrinsic.patch file
patching file lib/Transforms/Scalar/SROA.cpp
-- LLVM_BUILD_TYPE   = Debug
-- [LLVM] PYTHON_EXECUTABLE = /usr/bin/python2
-- [LLVM] Clearing build system compilation flags
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for link.h
-- Looking for link.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for malloc/malloc.h
-- Looking for malloc/malloc.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for valgrind/valgrind.h
-- Looking for valgrind/valgrind.h - not found
-- Looking for zlib.h
-- Looking for zlib.h - found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for FE_ALL_EXCEPT
-- Looking for FE_ALL_EXCEPT - found
-- Looking for FE_INEXACT
-- Looking for FE_INEXACT - found
-- Looking for mach/mach.h
-- Looking for mach/mach.h - not found
-- Looking for histedit.h
-- Looking for histedit.h - not found
-- Looking for CrashReporterClient.h
-- Looking for CrashReporterClient.h - not found
-- Looking for linux/magic.h
-- Looking for linux/magic.h - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_getspecific in pthread
-- Looking for pthread_getspecific in pthread - found
-- Looking for pthread_rwlock_init in pthread
-- Looking for pthread_rwlock_init in pthread - found
-- Looking for pthread_mutex_lock in pthread
-- Looking for pthread_mutex_lock in pthread - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for pfm_initialize in pfm
-- Looking for pfm_initialize in pfm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for compress2 in z
-- Looking for compress2 in z - found
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
-- Looking for xar_open in xar
-- Looking for xar_open in xar - not found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for setrlimit
-- Looking for setrlimit - found
-- Looking for isatty
-- Looking for isatty - found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for futimes
-- Looking for futimes - found
-- Looking for posix_fallocate
-- Looking for posix_fallocate - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for lseek64
-- Looking for lseek64 - found
-- Looking for mallctl
-- Looking for mallctl - not found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for malloc_zone_statistics
-- Looking for malloc_zone_statistics - not found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for posix_spawn
-- Looking for posix_spawn - found
-- Looking for pread
-- Looking for pread - found
-- Looking for realpath
-- Looking for realpath - found
-- Looking for sbrk
-- Looking for sbrk - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strerror_s
-- Looking for strerror_s - not found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Looking for sched_getaffinity
-- Looking for sched_getaffinity - found
-- Looking for CPU_COUNT
-- Looking for CPU_COUNT - found
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test LLVM_HAS_ATOMICS
-- Performing Test LLVM_HAS_ATOMICS - Success
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG - Success
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG - Failed
-- Performing Test HAS_MAYBE_UNINITIALIZED
-- Performing Test HAS_MAYBE_UNINITIALIZED - Success
-- Native target X86 is not selected; lli will not JIT code
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Failed
-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Failed
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Success
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- [LLVM] Restoring build system compilation flags
CMake Error at /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/llvm_patches/CMakeLists.txt:210 (message):
  Expected LLVM version 7.0.0 but found 7.1.0.

-- Configuring incomplete, errors occurred!
See also "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/build/CMakeFiles/CMakeOutput.log".
See also "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/IGC_1/build/CMakeFiles/CMakeError.log".

I am using ubuntu 16.04 and I would also like to mention that I have to use a debug or an internal version of the compiler. Also please let me know if you need any further information. Thank you in advance.

**Comment by paigeale** [comment]
Hello duttasankha, 

One error that is sticking out is "**Expected LLVM version 7.0.0 but found 7.1.0**." Could you provide details on how you got this 7.1.0 version? I do not see this version supported on the llvm git page https://github.com/llvm/llvm-project.git. 

Thanks,
Alex

**Comment by duttasankha** [comment]
@paigeale 
Thank you for your comment. I just followed the download dependencies mentioned build instructions [here](https://github.com/intel/intel-graphics-compiler#building). Nothing else than that. After that I kept on following the instructions. But I executed the cmake command with the debug flag.

**Comment by AlexeySachkov** [comment]
@paigeale, take a look at commits in [release_70](https://github.com/llvm-mirror/llvm/commits/release_70) llvm-mirror/llvm GitHub repo

Version was bumped from 7.0.0 to 7.1.0 in https://github.com/llvm-mirror/llvm/commit/2883e0bc28b27e7eec068472557528baf08d0e0c

**Comment by duttasankha** [comment]
Hi
I was wondering if someone could provide me some kind of feedback to get rid of this error. I really need to use the intel igc for my project and I would very much appreciate if someone could provide me some sort of feedback to get rid of this error and install.

**Comment by Gecko222** [comment]
@duttasankha in llvm_patches/CMakeLists.txt ad 133 line you have to change set(EXPECTED_LLVM_VERSION "7.0.0") to set(EXPECTED_LLVM_VERSION "7.1.0")
and llvm should be in folder llvm7.1.0_source

**Comment by GBuella** [comment]
I guess temporarily we could reference specific commit hashes in the README, instead of tags.

**Comment by duttasankha** [comment]
Hi
So the cmake in the debug mode worked fine but the make gave this error which I have pasted [here](https://paste.ofcode.org/9ydN73gYBVsamKhV9bzHAy).

**Comment by iwwu** [comment]
@duttasankha I can't access your log anymore. Can you confirm if the issue is still there with latest IGC code?

**Comment by iwwu** [comment]
Insufficient information on whether there is still an issue on latest code.
