### ISSUE TITLE
Clean up Buiding section in README about llvm patches

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#52]
Can the Building section within README file be simplified?

Please explain which features are provided by using llvm patches.    

IIUC, llvm patches shouldn't be needed on later versions of llvm.  So in this case can README explain what is supported?  i.e. llivm-7.x, llvm-8.x or llvm-9.x (master branch)

Then when user wants to compile against system llvm (i.e. llvm without igc instructed patches) it should compile as the following is enforced

```
#if !defined (SYSTEM_LLVM)
compile stuff as llvm 7.x is patched
# else
do not compile this feature
#endif 
```
This way you're letting the user decide if this feature is necessary or not.

**Comment by dvrogozh** [comment]
This issue remind me about this paragraph I've spotted in another project: https://github.com/KhronosGroup/SPIRV-LLVM-Translator#branching-strategy. It clearly defines and publish strategy as follows:
> Code on the master branch in this repository is intended to be compatible with master/trunk branch of the llvm project. That is, for an OpenCL kernel compiled to llvm bitcode by the latest version(built with the latest git commit or svn revision) of Clang it should be possible to translate it to SPIR-V with the llvm-spirv tool.
>
> All new development should be done on the master branch.
>
> To have versions compatible with released versions of LLVM and Clang, corresponding branches are created in this repository. For example, to build translator with LLVM 7.0 (release_70) one should use llvm_release_70 branch.

Maybe we can consider publishing/adopting something similar or just the same since it looks reasonable?

**Comment by paigeale** [comment]
Closing issue as latest README has been updated and specific llvm versions are explained in detail here ....[https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md#llvmclang-version-specific-caveats](url)
