### ISSUE TITLE
[RFC] Build IGC against system installed dependencies

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#54]
This is an RFC (Request for Comments) to help trigger a discussion on how to simplify IGC build and installation instructions. I hope it will be helpful.

I was able to build IGC in a following way:
1. Build and install LLVM
```sh
git clone https://github.com/llvm/llvm-project.git && cd llvm-project
mkdir build && cd build
cmake -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_INSTALL_PREFIX=/path/to/install.llvm8 ..
make && make install
```

2. Build and install SPIRV tools:
```sh
git https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git && cd SPIRV-LLVM-Translator
mkdir build && cd build
cmake \
  -DLLVM_DIR=/path/to/install.llvm8/lib/cmake/llvm \
  -DCMAKE_INSTALL_PREFIX=/path/to/install.llvm8 \
  -DCMAKE_CXX_FLAGS="-fPIC" \
  ..
make && make install
```

3. Build and install common clang:
```sh
git clone https://github.com/intel/opencl-clang && cd opencl-clang
cmake \
  -DLLVM_DIR=/path/to/install.llvm8/lib/cmake/llvm \
  -DCMAKE_INSTALL_PREFIX=/path/to/install.llvm8 \
  ..
make && make install
```

> 4. **Build and install IGC. Here I did not avoid custom patches. They are here: #55 **
> ```sh
> git clone https://github.com/intel/intel-graphics-compiler.git igc && cd igc
> git fetch origin pull/55/head:pr_55 && git checkout pr_55
> cmake \
>   -DLLVM_DIR=/path/to/install.llvm8/lib/cmake/llvm \
>   -DCMAKE_PREFIX_PATH=/path/to/install.llvm8/lib/cmake/clang \
>   -DCMAKE_INSTALL_PREFIX=/path/to/install.llvm8 \
>   -DIGC_PREFERRED_LLVM_VERSION=8
>   ..
> ```
> 

4. **[UPDATED]** after https://github.com/intel/intel-graphics-compiler/commit/ae4aa3b92ed8f47c9477686fdb0df072d0665257. Build and install IGC:
```sh
git clone https://github.com/intel/intel-graphics-compiler.git igc && cd igc
git fetch origin pull/55/head:pr_55 && git checkout pr_55
export PATH=/path/to/install.llvm8/bin  # to fetch clang-8
cmake \
  -DLLVM_DIR=/path/to/install.llvm8/lib/cmake/llvm \
  -DCMAKE_INSTALL_PREFIX=/path/to/install.llvm8 \
  -DIGC_PREFERRED_LLVM_VERSION=8
  ..
```

The above instruction works for me against LLVM 8.x, i.e.:
* LLVM: git checkout -b 8.x remotes/origin/release/8.x
* SPIRV: git checkout -b llvm_release_80 remotes/origin/llvm_release_80
* CommonClang: git checkout -b ocl-open-80 remotes/origin/ocl-open-80
* IGC: master bracnh

IGC is not yet ready for LLVM 9.x, there are build issues. Some - trivial (fix in #58). Some - beyond my current knowledge of LLVM (see #59).

I did not try the instruction with LLVM 7.x

The above modified IGC build procedure is described in the proposed README update in RFC #65.

**Comment by chivakker** [comment]
IIUC, I think this should be put together in a way that it explains how different llvm versions should work.  I.e.  what would happen if my system has llvm-7.x or I want to use llvm master ToT for development purposes.  It is up to IGC to state which versions are supported, that definition is missing.

**Comment by chivakker** [comment]
I took the task of compiling igc with LLVM-7.0.1.  There's this hard dependency inside BiFModule that forces looking for clang.7z which is tracked on a different issue.  Even if I tried to disable it, it will try to compile an non-existent header

my cmake

`cmake -DCMAKE_INSTALL_PREFIX=/usr/lib64  -DIGC_OPTION__OUTPUT_DIR=<Folder in home>/install/ -DLLVM_DIR=/usr/lib64/cmake/llvm -DCMAKE_PREFIX_PATH=/usr/lib64/cmake/clang -DCMAKE_BUILD_TYPE=Release -DIGC_PREFERRED_LLVM_VERSION=7.0.1 -DCMAKE_CXX_FLAGS="-fPIC" -DIGC_OPTION_BIF_LINK_BC=OFF ../igc/IGC/`

build breaks at

```
*** No rule to make target '<Folder in home>/install/bif/opencl_cth.h', needed by <Folder in home>install/fcl/embedder/opencl_cth_IDR_CTH_H_H_133.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1293: OCLFE/embedder/CMakeFiles/CTHLibFcl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by dvrogozh** [comment]
Please, be aware that https://github.com/intel/intel-graphics-compiler/commit/ae4aa3b92ed8f47c9477686fdb0df072d0665257 landed in master branch which essentially is refactored version of #55 (which I plan to close). 

Thus, the way to build IGC described above in this issue now works with the minor modification that clang is detected via cmake find_program(`clang-${LLVM_VERSION_MAJOR}`). For that to work `clang-X` should be in the `PATH`.

I have created RFC #65 which modifies README describing alternate/better IGC build procedure.

**Comment by paigeale** [comment]
@dvrogozh,

We have finally configured IGC to be build using system installed dependencies with Travis CI. See the .travis.yml file. Does this suffice? Can we close this?

**Comment by dvrogozh** [comment]
Sorry, I missed your ping. Yes, I believe we can close this now.

Here is Debian/Ubuntu packaging for IGC for everyone's reference: https://salsa.debian.org/opencl-team/intel-graphics-compiler
