### ISSUE TITLE
What's IGC_OPTION_OUTPUT_DIR

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#56]
I'm trying to build this with -DIGC_OPTION_OUTPUT_DIR=<LOCAL_FOLDER>

but configure print out shows

Install root directory:
--    "/usr/local"

It only changes when using -DCMAKE_INSTALL_PREFIX=<LOCAL_FOLDER>

**Comment by dvrogozh** [comment]
@chivakker : I may actually drop IGC_OPTION__OUTPUT_DIR - starting from commit https://github.com/intel/intel-graphics-compiler/commit/cb807eea69dc038e29acf9c7fc3950535b135a11 it is not actually needed. And I was trying to fix a readme to drop mentioning of IGC_OPTION__OUTPUT_DIR: that was done in the accepted PR #43, but I don't see my change in the history. @paigeale : did you force-push to master branch?

**Comment by paigeale** [comment]
Closing this issue for I update the README.md file to drop the output dir requirement
