### ISSUE TITLE
remove -g from CXX_FLAGS with build_type is release

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#57]
Set cmake -DCMAKE_BUILD_TYPE=Release

but it returns

CMAKE_CXX_FLAGS:STRING=-g

Please use -g only in debug type.

**Comment by iwwu** [comment]
I'm not seeing the issue. This is what I did

> cmake -DCMAKE_BUILD_TYPE=Release ../igc/IGC
> cmake -LAH | grep CXX_FLAGS
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
