### ISSUE TITLE
SPV_INTEL_subgroups

### ISSUE THREAD

**Issue by jchodor** [intel/intel-graphics-compiler#6]
@oscarbg is asking about our plans for supporting SPV_INTEL_subgroups extension in our OCL driver stack..
(Original issue was filed against compute-runtime : https://github.com/intel/compute-runtime/issues/13)

**Comment by lwesiers** [comment]
This topic was closed, because we answered for this question here:
https://github.com/intel/compute-runtime/issues/13#issuecomment-368180729

**Comment by jchodor** [comment]
I have some good news, support for SPV_INTEL_subgroups was recently added to the compiler : https://github.com/intel/intel-graphics-compiler/commit/dbb9f9f194473f1d33bad3808ee47fc9fa429499#diff-c9f9f38fbdf6b0e38ae7cf69d27db022
