### ISSUE TITLE
Remove non-related warnings

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#60]
Like this, UFO_VK shouldn't be attempted here. 

CMake Warning at CMakeLists.txt:2196 (message):
  not defined, defaulting to y: UFO_VK

**Comment by paigeale** [comment]
Thanks Daniel for reporting this. I have an internal change that will be migrated shortly and remove this flag from the IGC Cmake file.

**Comment by iwwu** [comment]
Change merged.
