### ISSUE TITLE
Remove ubuntu special directives inside CMake

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#61]
I am not sure why this is needed but it looks like it can be improved.

If I am not using Ubuntu, Most of these build requirements will be configured wrong unnecessarily.

This is about everything related to -DLINUX_DISTRO=ubuntu

A good approach would be put everything on a single CMake file where linux, windows and others are separated.

**Comment by paigeale** [comment]
Hello Daniel,

Could you elaborate what you are expecting? We set this define to ubuntu in the case in which it is not defined and can't be figured out.

**Comment by paigeale** [comment]
Hey Daniel,

This piece of code is picking up this define in \IGC\BiFModule\CMakeLists.txt

if(DEFINED "LINUX_DISTRO" AND (NOT (LINUX_DISTRO MATCHES "^$")))
    set(_osDirSuffix "${LINUX_DISTRO}")
  else()
    set(_osDirSuffix "ubuntu")
  endif()

This osDirSuffix is used for grabbing the right prebuilt clang. 

We detect the architecture in cmake using a function called "igc_arch_detect".

**Comment by chivakker** [comment]
it looks to me that igc_arch_detect will just bring linux_64 for example.  While all the ubuntu directives is to build deb packages. What I don't understand is if you need prebuilt clang why it is not picking it up from system installation first, or am I wrong here?

**Comment by lwesiers** [comment]
Hello there,

There was huge refactor of [IGC/BiFModule/CMakeLists.txt](https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/CMakeLists.txt) and in the current code we don't have any special ubuntu directives. As I understand correctly, it was the main problem here. So if it's not present in the code, then I will just close this issue.
