### ISSUE TITLE
[Question] Intel igpu offloading plan regarding openMP support on GCC and LLVM ?

### ISSUE THREAD

**Issue by LifeIsStrange** [intel/intel-graphics-compiler#62]
My question is not directly related to openCL.
But as a consumer I would like to say that I think GPGPU is coming slowly to a new era.
GPGPU has been possible on various accelerators sinces a decade, yet it has gotten quite a niche usage despite being extremely useful.
This is because reasons such as: 
1* The needs to learn a new langage such as openCL/CUDA where most of the market will have a separate cpu code on c++. SYCL help to bridge this gap but still require the needs to systematically adapt existing cpu code.
2* The perceived learning curve, and the real one, and even after mastering them, the inherent productivity loss of having need of kernel boilerplate and to fit to a constrained hardware model.
3* The lack of teaching in universities, or the teaching of Nvidia vendor lockin through proprietary CUDA
4* The lack of heterogeneous computing capabilities that led to yet another api HSA that has currently no suffisant traction in x86 world. the lack of ability to e.g run a loop in multithread, AND on SIMD AND on GPU. As I understund today, SYCL does not allow simultaneous SIMD (AVX) and GPU. I am not aware if it allow simultaneous multithread and GPU offloading on the same loop.

The new era I see is the new thing in town that answer all of thoses real world issues:
openMP 4.5
openMP 4.5 regarding issue 1 and 2*:
One still needs to learn openMP and it has some advanced features that imply a cognitive load.
BUT openMP is made of annotations, that is you can INCREMENTALLY multithread/SIMDIFY/offload parts of codes, WITHOUT changing the code (in most cases) by adding clear explicit annotations.
OpenMP is far higher level, eliminate entire classes of errors, automate things for the developper, is easier and one order of magnitude quicker to learn.

regarding issue 3* openMP is widely used / teached in HPC world, and is extremely vendor, even *langage* agnostic (supported on Fortran by example).

Regarding issue 4* openMP is the only way that i'm aware of to run code simultaneously in SIMD(avx), cores and an accelerator. Enabling unprecedented performance gain. And openMP is according many benchmarks the most optimised multithread AND SIMD implementation.
It is evolving (5.0) and OpenACC is being merged into openMP !

That being said, let's be clear, openMP offloading does NOT replace SYCL as SYCL can allow better performance on fine grained cases. But because of all said reasons it will play a massive role in HPC/GPGPU computing.
Intel does not yet support openMP offloading to intel iGPUs, while Nvidia NVPTX is well supported on Clang and GCC, and AMD GCN offloading is ready for GCC 10. This is making intel far less competitive.
Yet Intel is really making a push for GPU computing, and has the ressources.

This is why I ask Intel to consider OpenMP intel i/D/GPU/FPGA offloading support in llvm and GCC as a priority.
And allowing better openMP/SYCL interoperability, and investing ressources in improving openMP (e.g clang omp declare simd: does not yet enable the vectorizer passe which is big low hanging fruit) instead of reinventing the wheel with yet another competing standard [()](https://xkcd.com/927/) that seems to be intel oneAPI.
https://www.phoronix.com/scan.php?page=news_item&px=Intel-oneAPI-Announcement
Another big improvment that could be brought by openMP would be to allow it run easily on clusters in a standardised way.
currently HPC users mixes openMP and MPI but this is suboptimal, intel already has developped cluster openMP https://software.intel.com/sites/default/files/1b/1f/6330 but integrated in the standard for openMP next and adding support for it in other compilers than ICC would be a nice improvment !
I wonder if there could also be a map reduce extension.
Edit: There's one! But not well tested: https://ompcloud.github.io/

**Comment by michaelxtian** [comment]
The short answer is  1) Intel will release a C/C++/Fortran OpenMP offloading compiler for iGPU. The C/C++ OpenMP offloading compiler for GPU is available for Intel Internal users;  2) Intel will open source C/C++ OpenMP offloading compiler for CPU and GPU; 3) DPC++ is a complimentary to OpenMP, not replacing to OpenMP.

**Comment by LifeIsStrange** [comment]
@michaelxtian awesome answer, but yet another compiler ? Users are on LLVM or GCC so I hope the backend will eventually be ported to them.
Anyway, thanks !

**Comment by llvm-vpo** [comment]
Yes, we will open source our LLVM-based OpenMP offloading compilers.

**Comment by illuhad** [comment]
> As I understund today, SYCL does not allow simultaneous SIMD (AVX) and GPU. I am not aware if it allow simultaneous multithread and GPU offloading on the same loop.

Not sure if I understand correctly what you want to accomplish, but you can have the same SYCL kernel (which I assume you mean by 'loop') run on both CPU and GPU. You can even decide at runtime where to execute your code. You can also use both CPU and GPU simultaneously. The SYCL spec is designed with this use case in mind and it is supported both in ComputeCpp and (I believe) Intel SYCL. In hipSYCL this is currently being worked on. Not sure about triSYCL.
