### ISSUE TITLE
Unable to compile OpenCL kernels after installing IGC

### ISSUE THREAD

**Issue by duttasankha** [intel/intel-graphics-compiler#63]
Hello Everyone

My installed OpenCL kernels were working fine for a long time. However, I was required to install IGC in debug/internal mode. So I installed IGC in the internal mode by following the instructions provided in the readme. It got installed without any issues. But now I am getting a weird by the JIT compiler in my program. The error is as follows: 
_error: unknown argument: '-emit-spirv'_

I am not sure what went wrong and how can I resolve this issue. I couldn't get much details regarding resolving the error over the internet as well. I didn't change anything other than installing the compiler. Also I tried to use the offline compiler ioc64 and I am getting the same error. I was wondering if someone could help me regarding this error and how can I remove it. Please let me know if I need to provide further information. I would greatly appreciate if someone could help me to error.

**Comment by PlutusCN** [comment]
@duttasankha 

I met the same compilation error with you, and do not know how to fix it.

**Comment by iwwu** [comment]
@PlutusCN Can you confirm if you are still seeing error after https://github.com/intel/compute-runtime/issues/123?

**Comment by PlutusCN** [comment]
@iwwu Now, I have no time to do this, I will study the error this weekend.

**Comment by iwwu** [comment]
@PlutusCN Thank you for the information.

I will close this issue. Please re-open or submit new issue if needed.
