### ISSUE TITLE
IGC build failure in "Build target GetClang" on "igc_release_2019-02-07"

### ISSUE THREAD

**Issue by Oriolehuang** [intel/intel-graphics-compiler#64]
Hi, all
I met issue when building IGC with “igc_release_2019-02-07 “  and latest version in master. The error message shows in Built target GetClang as below:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
In file included from <built-in>:2:
/home/hl/Linux_Build/packageGenerator/generateFromGithub/Linux_C_for_Media_Development_Package_20190220.cache/igc_build_207/Release/bif/./opencl_cth.h:6917:1: error: unknown type name 'intel_sub_group_avc_mce_payload_t'
intel_sub_group_avc_mce_payload_t __attribute__((overloadable))
^
/home/hl/Linux_Build/packageGenerator/generateFromGithub/Linux_C_for_Media_Development_Package_20190220.cache/igc_build_207/Release/bif/./opencl_cth.h:6917:35: error: expected identifier or '('
intel_sub_group_avc_mce_payload_t __attribute__((overloadable))
                                  ^
/home/hl/Linux_Build/packageGenerator/generateFromGithub/Linux_C_for_Media_Development_Package_20190220.cache/igc_build_207/Release/bif/./opencl_cth.h:6943:1: error: unknown type name 'intel_sub_group_avc_mce_payload_t'
intel_sub_group_avc_mce_payload_t __attribute__((overloadable))

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

I did cmd as the readme:
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
git clone -b release_70 https://github.com/llvm-mirror/llvm llvm_source
$ git clone -b release_70 https://github.com/llvm-mirror/clang llvm_source/tools/clang
$ git clone -b ocl-open-70 https://github.com/intel/opencl-clang llvm_source/projects/opencl-clang
$ git clone -b llvm_release_70 https://github.com/KhronosGroup/SPIRV-LLVM-Translator llvm_source/projects/llvm-spirv
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone https://github.com/intel/intel-graphics-compiler igc
  [If using specific release]
$ cd igc && git checkout -b tag igc_release_2019-02-07

$mkdir build
$ cd build
$ cmake ../igc/IGC
$ make -j`nproc`
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Could you please help to check? Thanks!
[igc_build_log.txt](https://github.com/intel/intel-graphics-compiler/files/2888041/igc_build_log.txt)

**Comment by PlutusCN** [comment]
I also met this error, and do not know how to fix.

**Comment by iwwu** [comment]
@PlutusCN Is it correct that you were able to resolve this issue with https://github.com/intel/compute-runtime/issues/123 instructions?

@Oriolehuang Can you confirm if that fixes your issue too?

**Comment by PlutusCN** [comment]
@iwwu At least, this issue can be avoided. Please refer to https://github.com/intel/compute-runtime/issues/123#issuecomment-466965933

**Comment by iwwu** [comment]
I will close this issue. Please re-open or submit new issue if needed.
