### ISSUE TITLE
don't explicitly add -fvisibility=hidden to compiler flags

### ISSUE THREAD

**Issue by tripzero** [intel/intel-graphics-compiler#67]
IGC/CMakeLists.txt has several places where it explicitly adds visibility hidden.  This will cause all libraries to pick it up whether they want to or not.  You should use cmake's CXX_VISIBILITY_PRESET variable per-target like this:

set_target_properties(MyTarget PROPERTIES CXX_VISIBILITY_PRESET hidden)

This will do the "right thing" on win32 and linux for compilers that support the feature.

**Comment by paigeale** [comment]
Intended to be used this way
