### ISSUE TITLE
question: will it make sense to link against common_clang rather than load it?

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#71]
https://github.com/intel/intel-graphics-compiler/blob/4be564fa181ace300379a045db1fa6ea972e356e/IGC/OCLFE/igd_fcl_mcl/source/clang_tb.cpp#L603

Here libigdfcl.so will dlopen("libcommon_clang.so"). Will it make sense to link against it instead?

That's probably can be reformulated as: does usage scenario exists when libigdfcl.so don't need libcommon_clang.so to work? If such case don't exist, this can vote towards linking against this library on Linux since:
1. This will make dependency explicit and simplify diagnostic in case of missing dependency
2. This will simplify the code since we will avoid the code to load/unload library, fetch symbols, check for non-null handle

**Comment by tripzero** [comment]
+1 for linking

**Comment by dvrogozh** [comment]
Done by https://github.com/intel/intel-graphics-compiler/commit/77e34129305f80af10fae7435c508ce746f494b1
