### ISSUE TITLE
Why is igc installing own copy of libopencl_clang.so?

### ISSUE THREAD

**Issue by tripzero** [intel/intel-graphics-compiler#76]
in make install output, I see libopencl_clang.so.  I am using system opencl_clang.so, so it is strange to see this library installed again.

**Comment by dvrogozh** [comment]
Maybe IGC built its own copy? How sources of IGC and common_clang were relatively located on your system? How folders were named?

**Comment by tripzero** [comment]
IGC did not have any access to the sources.  I built in a chroot with only the opencl_clang rpm installed.

**Comment by tjaalton** [comment]
yes, there's a symlink created regardless if a system opencl-clang is used or not
