### ISSUE TITLE
drop DATE from iga_version_string

### ISSUE THREAD

**Issue by tjaalton** [intel/intel-graphics-compiler#79]
Having the date there makes the build fail with the default distro build options:

/home/tjaalton/src/pkg-opencl/intel-graphics-compiler.git/visa/iga/IGALibrary/api/iga.cpp:620:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
     return IGA_VERSION_STRING "-" IGA_EXTERNAL_INTERNAL " (" __DATE__ ")";
                                                              ^~~~~~~~

**Comment by paigeale** [comment]
Fix for this will be merged today

**Comment by paigeale** [comment]
Closing for issue is addressed with 670b9026a552346380383b26b91a0cc271bd14dc
