### ISSUE TITLE
libcommon_clang.so won't exist in runtime package

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#81]
https://github.com/intel/intel-graphics-compiler/blob/4be564fa181ace300379a045db1fa6ea972e356e/IGC/OCLFE/igd_fcl_mcl/source/clang_tb.cpp#L603

@paigeale, @iwwu : I just realized that IGC loads "libcommon_clang.so" exactly as I wrote it. The problem is that this is _linker_ name and it will be packaged into _development_ package, i.e. in something called like igc-devel.rpm while libcommon_clang.so.8 (if you build against LLVM-8) will be packaged into _runtime_ package igc.rpm. So, we might face the situation when user will install some application which requires igc, hence it will install igc.rpm as a dependency, but he will miss igc-devel.rpm, hence he will miss libcommon_clang.so entirely.

Thus, I think we need to implement one of the following solutions:
1. Either load libcommon_clang.so.${LLVM_MAJOR_VERSION}
2. Or simply _link_ against common_clang as suggested in #71

**Comment by tripzero** [comment]
I agree with 1 as a short term goal.  Long term there's no reason not to link against opencl-clang.  Reducing code complexity (that comes with using dlopen, dlsym, etc) is always better.

**Comment by dvrogozh** [comment]
Fixed by https://github.com/intel/intel-graphics-compiler/commit/77e34129305f80af10fae7435c508ce746f494b1
