### ISSUE TITLE
Regression configuring IGC: INSTALL TARGETS given no LIBRARY DESTINATION

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#82]
I am configuring IGC as follows:
`cmake -DLLVM_DIR=/home/dvrogozh/git/github/install.llvm8/lib/cmake/llvm -DCMAKE_INSTALL_PREFIX=/home/dvrogozh/git/github/install.llvm8 -DIGC_PREFERRED_LLVM_VERSION=8 ../igc/IGC`

And get this error:
```
CMake Error at /home/dvrogozh/git/github/tmp/igc/visa/iga/IGALibrary/CMakeLists.txt:336 (INSTALL):
  INSTALL TARGETS given no LIBRARY DESTINATION for shared library target
  "IGA_DLL".
```

This is a regression:
* 2d11db1d9baccfc1a4fb289c1b754721e0bfcdc5 - bad
* 48c12f5c375574198be188d814dae9c9a25a6f26 - good

I did not bisect yet.

**Comment by dvrogozh** [comment]
@tripzero, @tjaalton : FYI

**Comment by paigeale** [comment]
Hey Dmitry,

Yes I saw this yesterday. This regression is caused by adding the GNUInstallDirs change (0770a37ee5fe0d4bdcef38520969a557499ba9b8) I reverted the change internally and will be porting the change here today.

**Comment by dvrogozh** [comment]
I think 0770a37 might have 2 issues:
1. Some paths likely miss `include(GnuInstallDirs)` as a result these variables are simply not initialized by default. I would suggest to have single GnuInstallDirs include on the uppermost level if possible.
2. When you specify installation paths via GnuInstallDirs variables, you need to write this:
`LIBRARY DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}`
instead of:
`LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}`
since the later one might be relative to CMAKE_INSTALL_PREFIX

**Comment by tripzero** [comment]
reverting patch may be a good temporary workaround, but are you working on debugging the issue for a real fix?  One way to check if GnuInstallDirs is working is to do a message("muh libdir: ${CMAKE_INSTALL_LIBDIR}") right before the line with the error and make sure the variable is set when running cmake.

**Comment by dvrogozh** [comment]
Yes, work is in progress.

**Comment by tripzero** [comment]
I also noticed that most of the headers are not being installed with this patch.  They appear to be installed with my version though but last time I tried mine, it was a slightly older commit.  Did something change where headers are no longer being installed?

**Comment by dvrogozh** [comment]
There was  cleanup of header installation targets per #35 request. This was done in 630d16b. In #35 I list the variants of install headers which we had before and after fix. That's the only thing I am aware of regarding headers.

**Comment by dvrogozh** [comment]
The bug in a title got fixed via revert (see https://github.com/intel/intel-graphics-compiler/commit/87d61ef4e4ffcc7d900d67243d3b4b94f2d5cacb). Let's close this one and reopen #74.
