### ISSUE TITLE
IntrinsicGenISA.gen not being generaeted 

### ISSUE THREAD

**Issue by mark-clayton** [intel/intel-graphics-compiler#85]
[ 81%] Built target CTHLibFcl
[ 81%] Building CXX object ElfPackager/CMakeFiles/elf_packager.dir/main.cpp.o
In file included from /home/tnl/neo/code/igc/IGC/ElfPackager/main.cpp:50:0:
/home/tnl/neo/code/igc/IGC/ElfPackager/../GenISAIntrinsics/GenIntrinsics.h:41:10: fatal error: IntrinsicGenISA.gen: No such file or directory
 #include "IntrinsicGenISA.gen"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ElfPackager/CMakeFiles/elf_packager.dir/build.make:62: recipe for target 'ElfPackager/CMakeFiles/elf_packager.dir/main.cpp.o' failed
make[2]: *** [ElfPackager/CMakeFiles/elf_packager.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:24826: recipe for target 'ElfPackager/CMakeFiles/elf_packager.dir/all' failed
make[1]: *** [ElfPackager/CMakeFiles/elf_packager.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mark-clayton** [comment]
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by paigeale** [comment]
Hello mark-clayton,

Could you please provide your build steps and your Linux environment so I can try to reproduce this error.

Thanks,
Alex

**Comment by mark-clayton** [comment]
Alex,
1- 
$ git clone -b release_70 https://github.com/llvm-mirror/llvm llvm_source
$ git clone -b release_70 https://github.com/llvm-mirror/clang llvm_source/tools/clang
$ git clone -b ocl-open-70 https://github.com/intel/opencl-clang llvm_source/projects/opencl-clang
$ git clone -b llvm_release_70 https://github.com/KhronosGroup/SPIRV-LLVM-Translator llvm_source/projects/llvm-spirv
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone https://github.com/intel/intel-graphics-compiler igc

Pulled the code above
2-
mkdir build
cd build
cmake ../igc/IGC

make -j`nproc`

Then at about 81% done I get the error for missing IntrisicGenISA.gen .. 
Any ideas how to invoke the file creation by hand?

**Comment by mark-clayton** [comment]
Alex,
I am using an Intel NUC8i7heb1 with ubuntu 18.04.
Forgot that part.
Thanks,

**Comment by mark-clayton** [comment]
thanks alex found the problem.

found the problem do make -j'nproc' instead of make ..

**Comment by paigeale** [comment]
Glad you resolved the issue. Closing issue.
