### ISSUE TITLE
build fail "[visa/LocalScheduler/CMakeFiles/LocalScheduler.dir/LocalScheduler_G4IR.cpp.o] Error 1"

### ISSUE THREAD

**Issue by happylearneroy** [intel/intel-graphics-compiler#86]
SYSTEM used: CentOS Linux release 7.6.1810 
Target device: NUC with core i7 8890G
Running step:

$ cd <workspace>
$ git clone -b release_70 https://github.com/llvm-mirror/llvm llvm_source
$ git clone -b release_70 https://github.com/llvm-mirror/clang llvm_source/tools/clang
$ git clone -b ocl-open-70 https://github.com/intel/opencl-clang llvm_source/projects/opencl-clang
$ git clone -b llvm_release_70 https://github.com/KhronosGroup/SPIRV-LLVM-Translator llvm_source/projects/llvm-spirv
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone https://github.com/intel/intel-graphics-compiler igc
  [If using specific release]
$ cd igc && git checkout -b tag igc_release_2019-01-15

Under workspace create a build folder. For example:
$ cd <workspace>
$ mkdir build

Build IGC using commands:
$ cd build
$ cmake ../igc/IGC
$ make -j`nproc`

Build fail after make command, with building LocalScheduler_G4IR.cpp.o.
Is it CentOS supported for intel graphics compiler?
Please kindly suggest how to resolve this issue?

Error log:
[ 79%] Built target LLVMWindowsManifest
[ 80%] Built target LLVMSPIRVLib
[ 80%] Built target CClangCompileOptions
[ 80%] Built target opencl.headers.target
[ 80%] Built target linux_resource_linker
[ 80%] Built target cl_headers
[ 80%] Built target opencl_clang
[ 80%] Built target copy_cclang_files
[ 80%] Built target GetClang
[ 80%] Built target llvm-link
[ 81%] Built target BiFModuleOcl
[ 81%] Built target CTHLibFcl
[ 81%] Built target elf_packager
[ 81%] Built target fcl_dll
[ 81%] Built target check_headers
[ 81%] Building CXX object visa/LocalScheduler/CMakeFiles/LocalScheduler.dir/LocalScheduler_G4IR.cpp.o
In file included from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.h:34:0,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.cpp:30:
/home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h: In member function ‘INST_LIST_ITER vISA::G4_BB::insert(std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator, vISA::G4_INST*)’:
/home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h:314:42: error: no matching function for call to ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::insert(std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator&, vISA::G4_INST*&)’
         return instList.insert(iter, inst);
                                          ^
/home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h:314:42: note: candidates are:
In file included from /usr/include/c++/4.8.2/list:64:0,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/../Gen4_IR.hpp:32,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h:41,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.h:34,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.cpp:30:
/usr/include/c++/4.8.2/bits/list.tcc:98:5: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::insert(std::list<_Tp, _Alloc>::iterator, const value_type&) [with _Tp = vISA::G4_INST*; _Alloc = vISA::std_arena_based_allocator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::value_type = vISA::G4_INST*]
     list<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8.2/bits/list.tcc:98:5: note:   no known conversion for argument 1 from ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator {aka std::_List_const_iterator<vISA::G4_INST*>}’ to ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::iterator {aka std::_List_iterator<vISA::G4_INST*>}’
In file included from /usr/include/c++/4.8.2/list:63:0,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/../Gen4_IR.hpp:32,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h:41,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.h:34,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.cpp:30:
/usr/include/c++/4.8.2/bits/stl_list.h:1089:7: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::insert(std::list<_Tp, _Alloc>::iterator, std::list<_Tp, _Alloc>::value_type&&) [with _Tp = vISA::G4_INST*; _Alloc = vISA::std_arena_based_allocator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::value_type = vISA::G4_INST*]
       insert(iterator __position, value_type&& __x)
       ^
/usr/include/c++/4.8.2/bits/stl_list.h:1089:7: note:   no known conversion for argument 1 from ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator {aka std::_List_const_iterator<vISA::G4_INST*>}’ to ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::iterator {aka std::_List_iterator<vISA::G4_INST*>}’
/usr/include/c++/4.8.2/bits/stl_list.h:1106:7: note: void std::list<_Tp, _Alloc>::insert(std::list<_Tp, _Alloc>::iterator, std::initializer_list<_Tp>) [with _Tp = vISA::G4_INST*; _Alloc = vISA::std_arena_based_allocator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<vISA::G4_INST*>]
       insert(iterator __p, initializer_list<value_type> __l)
       ^
/usr/include/c++/4.8.2/bits/stl_list.h:1106:7: note:   no known conversion for argument 1 from ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator {aka std::_List_const_iterator<vISA::G4_INST*>}’ to ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::iterator {aka std::_List_iterator<vISA::G4_INST*>}’
/usr/include/c++/4.8.2/bits/stl_list.h:1123:7: note: void std::list<_Tp, _Alloc>::insert(std::list<_Tp, _Alloc>::iterator, std::list<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = vISA::G4_INST*; _Alloc = vISA::std_arena_based_allocator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<vISA::G4_INST*>; std::list<_Tp, _Alloc>::size_type = long unsigned int; std::list<_Tp, _Alloc>::value_type = vISA::G4_INST*]
       insert(iterator __position, size_type __n, const value_type& __x)
       ^
/usr/include/c++/4.8.2/bits/stl_list.h:1123:7: note:   candidate expects 3 arguments, 2 provided
/usr/include/c++/4.8.2/bits/stl_list.h:1149:9: note: template<class _InputIterator, class> void std::list<_Tp, _Alloc>::insert(std::list<_Tp, _Alloc>::iterator, _InputIterator, _InputIterator) [with _InputIterator = _InputIterator; <template-parameter-2-2> = <template-parameter-1-2>; _Tp = vISA::G4_INST*; _Alloc = vISA::std_arena_based_allocator<vISA::G4_INST*>]
         insert(iterator __position, _InputIterator __first,
         ^
/usr/include/c++/4.8.2/bits/stl_list.h:1149:9: note:   template argument deduction/substitution failed:
In file included from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.h:34:0,
                 from /home/demo/Intel_GPU/igc/visa/LocalScheduler/LocalScheduler_G4IR.cpp:30:
/home/demo/Intel_GPU/igc/visa/LocalScheduler/../FlowGraph.h:314:42: note:   cannot convert ‘iter’ (type ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator {aka std::_List_const_iterator<vISA::G4_INST*>}’) to type ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::iterator {aka std::_List_iterator<vISA::G4_INST*>}’
         return instList.insert(iter, inst);
    ^
/usr/include/c++/4.8.2/bits/stl_list.h:1332:7: note:   no known conversion for argument 1 from ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::const_iterator {aka std::_List_const_iterator<vISA::G4_INST*>}’ to ‘std::list<vISA::G4_INST*, vISA::std_arena_based_allocator<vISA::G4_INST*> >::iterator {aka std::_List_iterator<vISA::G4_INST*>}’
make[2]: *** [visa/LocalScheduler/CMakeFiles/LocalScheduler.dir/LocalScheduler_G4IR.cpp.o] Error 1
make[1]: *** [visa/LocalScheduler/CMakeFiles/LocalScheduler.dir/all] Error 2
make: *** [all] Error 2

**Comment by happylearneroy** [comment]
Correct one thing, in order to fix previous issue during build, the check out version was changed to 2019-03-12.

$ cd igc && git checkout -b tag igc_release_2019-03-12

**Comment by paigeale** [comment]
Hello happylearneroy,

Is you build issue then resolved with using the new tag?

**Comment by happylearneroy** [comment]
No, the issue is not resolved with new tag, the issue is with tag igc_release_2019-03-12

**Comment by paigeale** [comment]
Hello happylearneroy,

I believe the issue is you are using the default gcc on the system which is 4.8. Could you please use at least gcc 6 or higher? Also I recommend if you are using CentOS that you use devtoolset-7.

Thanks,
Alex

**Comment by dvrogozh** [comment]
I am building IGC on CentOS-7 and I always build with later compiler from scl. Since project uses C++11 it is actually imply >=gcc-6 since that's the first version where C++11 is officially supported. On earlier versions you might step into big problems.

You can look here for guidance to install scl: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/. Basically, you should be able to do this to install devtoolset-7 (I did something like that very long ago, so I am not 100% remember what exactly I did):
```
# 1. Install a package with repository for your system:
# On CentOS, install package centos-release-scl available in CentOS repository:
$ sudo yum install centos-release-scl

# On RHEL, enable RHSCL repository for you system:
$ sudo yum-config-manager --enable rhel-server-rhscl-7-rpms

# 2. Install the collection:
$ sudo yum install devtoolset-7
```

And now configure and build IGC:
```
scl enable devtoolset-7 -- cmake <your params>
make -j8
...
```

**Comment by paigeale** [comment]
@happylearneroy, 

Is this build issue still occurring after updating your gcc version? If not please close.

Thanks,
Alex

**Comment by happylearneroy** [comment]
No problem now, close the issue
