### ISSUE TITLE
igc make errors

### ISSUE THREAD

**Issue by duttasankha** [intel/intel-graphics-compiler#87]
My goal is to build the IGC in the internal or in the debug form. However, I having huge number of errors while executing the make command. I would like to mention that the errors I am facing is also occurring the the release (i.e. not passing --DCMAKE_BUILD_TYPE=Internal/Debug  during cmake). I followed the build instructions exactly mentioned your [here ](https://github.com/intel/intel-graphics-compiler#building).  The output of the cmake is provided in [here](https://pastebin.com/mBTKVLYN). The cmake completed without any error but with some warnings as shown. Output of the make error is provide in [here](https://pastebin.com/VyRc3PyV) and [here](https://pastebin.com/46vMDnkg). I needed to divide over two posts as the errors are too large in numbers. The errors occurred after 97% of the build is done as shown below:
```
 97%] Building CXX object Compiler/CMakeFiles/Compiler.dir/VerificationPass.cpp.o
[ 97%] Linking CXX static library ../Release/libCompiler.a
[ 97%] Built target Compiler
[ 97%] Built target opencl-clang
[ 97%] Built target clang
[ 97%] Built target copy_cclang_files
[ 97%] Built target GetClang
[ 97%] BiF: "IBiF_PreRelease_int.bc": Compiling OpenCL source: "IBIF_PreRelease_Impl.cl"
[ 97%] BiF: "IBiF_Impl_int.bc": Compiling OpenCL source: "IBiF_Impl.cl"
[ 97%] BiF: "IBiF_spirv_size_t_64.bc": Compiling OpenCL source: "pointersize.cl"
[ 97%] BiF: "IBiF_Impl_int_spirv.bc": Compiling OpenCL source: "IBiF_Impl.cl"
[ 97%] BiF: "IGCsize_t_32_int.bc": Compiling OpenCL source: "IBiF_size_t.cl"
[ 97%] BiF: "IBiF_spirv_size_t_32.bc": Compiling OpenCL source: "pointersize.cl"
[ 97%] BiF: "IGCsize_t_64_int.bc": Compiling OpenCL source: "IBiF_size_t.cl"
In file included from <built-in>:2:
/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/Release/bif/./opencl_cth.h:6908:1: error: unknown type name 'intel_sub_group_avc_mce_payload_t'
intel_sub_group_avc_mce_payload_t __attribute__((overloadable))
```
It would be really helpful if someone could help me to resolve the issue. I just want to mention that though I didn't specify build type and use the default release, but I do need to build it using internal or in debug format. Thank you.

**Comment by duttasankha** [comment]
I used the [commit id](https://github.com/intel/opencl-clang/commit/d29e1fa373f942165465f1d8b9708baf5a02e5e2) as you have mentioned in the referred link. However I am getting error while executing cmake. The cmake output is provided below.

cmake -DCMAKE_BUILD_TYPE=Internal ../igc/IGC
CMake Warning at CMakeLists.txt:1910 (message):
  CMAKE_BUILD_TYPE: Unknown build configuration.  The following
  configurations are available: Debug;Release.

  The "Release" configuration will be used.

  This value has meaning only for single-configuration generators (like
  Make).  It will be ignored for MSVC/XCode.


CMake Warning (dev) at CMakeLists.txt:2052 (set):
  Cannot set "IGC_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:2061 (set):
  Cannot set "FCL_LIBRARY_NAME": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- ================================ IGC Project ================================
-- Build type:  Release (single-configuration generator)
-- Build tools: OFF
-- LLVM dir:    
-- 
-- Output directory:
--    "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/Release"
-- Install root directory:
--    "/usr/local"
-- Architecture:
--  - target: Linux64    (detected: Linux64)
--  - host:   Linux64    (detected: Linux64)
-- 
-- Cross-compilation needed: NO
-- Cross-compilation set:    FALSE
-- 
-- Advanced:
--  - Link BiF resources:              ON
--  - Building Windows Universal:      
-- =============================================================================
-- [IGC] LLVM targets are not defined. Searching for LLVM.
-- [IGC] IGC will build LLVM from sources, because /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/igc/IGC/../../llvm_patches was found. Use IGC_OPTION__FORCE_SYSTEM_LLVM=1 to use system LLVM.
-- [IGC] LLVM compilation from /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/igc/IGC/../../llvm_patches
-- [LLVM_PATCHER] : Manual read LLVM version from llvm_source/CMakeLists.txt file
-- [LLVM_PATCHER] : In folder /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/llvm_patches/../llvm_source found LLVM version : 7.1.0
-- [LLVM_PATCHER] : LLVM_SOURCE_URL   = /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/llvm_patches/../llvm_source
-- [LLVM_PATCHER] : LLVM_OPTIONS      = -DLLVM_TARGETS_TO_BUILD=X86;-DLLVM_BUILD_TOOLS=true;-DLLVM_INCLUDE_TOOLS=true;-DLLVM_INSTALL_UTILS=false;-DLLVM_INCLUDE_UTILS=false;-DLLVM_BUILD_EXAMPLES=false;-DLLVM_INCLUDE_EXAMPLES=false;-DLLVM_BUILD_TESTS=false;-DLLVM_INCLUDE_TESTS=false;-DLLVM_APPEND_VC_REV=false;-DLLVM_ENABLE_THREADS=true;-DLLVM_ENABLE_CXX1Y=false;-DLLVM_ENABLE_PIC=true;-DLLVM_ENABLE_WARNINGS=true;-DLLVM_ENABLE_PEDANTIC=true;-DLLVM_ENABLE_WERROR=false;-DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF;-DLLVM_BUILD_RUNTIME=true;-DLLVM_ENABLE_TERMINFO=false;-DLLVM_ENABLE_EH=true;-DLLVM_ENABLE_RTTI=true;-DLLVM_BUILD_32_BITS=false
-- [LLVM_PATCHER] : LLVM_BUILD_TYPE   = Release
-- [LLVM] PYTHON_EXECUTABLE = /usr/bin/python2
-- [LLVM] Clearing build system compilation flags
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- Found Python module pygments
-- Found Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- Targeting X86
-- Linker detection: GNU ld
-- /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/llvm/src/tools/clang:
Already on 'ocl-open-70'
T	test/Driver/Inputs/CUDA-symlinks/usr/bin/ptxas
T	test/Driver/Inputs/basic_cross_linux_tree/usr/bin/i386-unknown-linux-gnu-ld
T	test/Driver/Inputs/basic_cross_linux_tree/usr/bin/x86_64-unknown-linux-gnu-ld
T	test/Driver/Inputs/basic_cross_linux_tree/usr/i386-unknown-linux-gnu/bin/ld
T	test/Driver/Inputs/basic_cross_linux_tree/usr/x86_64-unknown-linux-gnu/bin/ld
T	test/Driver/Inputs/multilib_32bit_linux_tree/usr/bin/as
T	test/Driver/Inputs/multilib_32bit_linux_tree/usr/bin/ld
T	test/Driver/Inputs/multilib_32bit_linux_tree/usr/i386-unknown-linux/bin/as
T	test/Driver/Inputs/multilib_32bit_linux_tree/usr/i386-unknown-linux/bin/ld
T	test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/as
T	test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/ld
T	test/Driver/Inputs/multilib_64bit_linux_tree/usr/x86_64-unknown-linux/bin/as
T	test/Driver/Inputs/multilib_64bit_linux_tree/usr/x86_64-unknown-linux/bin/ld
-- /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/llvm/src/projects/llvm-spirv:
Already on 'ocl-open-70'
-- Clang version: 7.1.0
-- [LLVM] Restoring build system compilation flags
-- [IGC] Link against LLVM static or shared component libs
-- Precompiled common clang bundle /home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/igc/IGC/../Clang/Prebuilt/linux-ubuntu/Release/64/clang.7z does not exist. Try to compile from sources or use system common clang.
Common clang build-in-tree
CMake Error at BiFModule/CMakeLists.txt:167 (add_library):
  add_library cannot create ALIAS target "common_clang_dll" because target
  "opencl-clang" does not already exist.


-- Configuring Intel Gen Assembler (IGA) Component
--  - GED_BRANCH:           GED_external
--  - CMAKE_CXX_COMPILER:   /usr/bin/c++
[check-igc] LIT tests disabled. Missing igc_opt target.
-- Configuring incomplete, errors occurred!
See also "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/CMakeFiles/CMakeOutput.log".
See also "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/build/CMakeFiles/CMakeError.log".

**Comment by paigeale** [comment]
Hello duttasankha, 

It appears from this log that cmake cannot find common_clang. Could you double check that your directory for common clang "opencl-clang" looks like "INTEL_GRAPHICS_COMPILER/llvm_source/projects/opencl-clang". 

Also you can install opencl-clang on the system as well to make sure CMake can find it by going into the opencl-clang directory and creating a build directory then calling cmake .. && make -j`nproc` && make install -j`nproc`

**Comment by duttasankha** [comment]
Hello Paigeale

Thank you for your reply. I have followed the build instructions as mentioned and so I have the opencl-clang in the INTEL_GRAPHICS_COMPILER/llvm_source/projects/opencl-clang.
I followed the instruction of creating a build directory and started executing cmake .. inside /opencl-clang/build .However I guess the llvm config file path is missing and the build process stopped. So the error is provided below:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for LLVM version 7.0.0
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LLVM", but
  CMake did not find one.

  Could not find a package configuration file provided by "LLVM" (requested
  version 7.0.0) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/duttasankha/Desktop/SANKHA_ALL/INTEL_GRAPHICS_COMPILER/llvm_source/projects/opencl-clang/build/CMakeFiles/CMakeOutput.log".

**Comment by duttasankha** [comment]
So I just reverted back to one of the earlier version of IGC to t igc_release_2018-11-15 as it was getting extremely difficult to work with the current release. So I was able to build the compiler in the Debug mode. The installation steps I followed is given below:
1. Install prerequisites

Building IGC need flxe, bision, clang 4.0, cmake version later than 3.4.3 and libz.  You can install required packages on ubuntu 16.04 like below:

$ sudo apt-get install flex bison clang-4.0 libz-dev cmake

2. Download all dependencies and create workspace folder as below:

workspace
      |- clang_source           https://github.com/llvm-mirror/clang
      |- common_clang           https://github.com/intel/opencl-clang
      |- llvm_patches           https://github.com/intel/llvm-patches
      |- llvm_source            https://github.com/llvm-mirror/llvm
      |- igc                    https://github.com/intel/intel-graphics-compiler
      |- opencl_headers         https://github.com/KhronosGroup/OpenCL-Headers

Example command:
$ git clone -b release_40 https://github.com/llvm-mirror/clang clang_source
$ git clone https://github.com/intel/opencl-clang common_clang
$ git clone https://github.com/intel/llvm-patches llvm_patches
$ git clone -b release_40 https://github.com/llvm-mirror/llvm llvm_source
$ git clone https://github.com/intel/intel-graphics-compiler igc
$ git clone https://github.com/KhronosGroup/OpenCL-Headers opencl_headers

3. Under workspace create a build folder.  For example:
$ mkdir build

4. Build IGC using commands:
$ cd build
$ cmake -DIGC_OPTION__OUTPUT_DIR=../igc-install/Release \
    -DCMAKE_BUILD_TYPE=Release -DIGC_OPTION__ARCHITECTURE_TARGET=Linux64 \
    ../igc/IGC
$ make -j`nproc`

However, I am not sure how to use the compiler. It would be really really helpful if someone could guide me as to how to use the compiler to generate binary of the opencl kernels offline. Thank you.

**Comment by paigeale** [comment]
Hello duttasankha, 

I am glad you were able to successfully build on a earlier release. I would be happy to work with you to get the newer release building if that is a priority. It appears you are satisfied with an earlier release though. 

In order to invoke the Intel Graphics Compiler please use the ocloc tool that is provided by intel compute runtime here https://github.com/intel/compute-runtime/releases. The ocloc tool takes in a .spirv or opencl (.cl) input and calls into IGC which produces a gen binary output. 

Another option (easiest in my opinion) is to update to Ubuntu 19.04 (latest Ubuntu release) and run "sudo apt-get install intel-opencl-icd" . This package has everything you need. Let me know if you have any questions, I can gladly walk you through any issues you are having.

Thanks,
Alex

**Comment by duttasankha** [comment]
Hello Paigeale

Thank you for your reply. I was able to built it but I am not sure if I have what I need. I built the compiler in the debug mode as I would like to access some features like [sliceID](https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Languages/OpenCL/IBiF_Impl.cl#L788), [timestamp register](https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Languages/OpenCL/IBiF_Impl.cl#L720) and other details as mentioned in [here](https://software.intel.com/en-us/forums/opencl/topic/800903). So I was wondering if you could let me know that the information would be available in the version I am using. 

About the usage, it would be difficult for me to update to 19.04, but I would start with the first suggestion of using ocloc. I was wondering if you could also provide me some details about the ocloc tool and how I can use it. Thank you again.

**Comment by duttasankha** [comment]
Hello Paigeale
I downloaded the ocloc and tried to install the deb package in this [website](https://github.com/intel/compute-runtime/releases) and tried to install it. But I saw that it depends on the other packages like gmmlib, intel igc core, intel-igc-opencl and intel-opencl. So I downloaded and installed all of the dependent packages and after that I was able to install the ocloc. However, still I am not sure how can I use the IGC with ocloc to compile the opencl kernel. You have mentioned that ocloc calls IGC automatically. But I am confused that how ocloc use the IGC that I built. As I mentioned before, that I want to build the IGC in the debug/internal format so that I can use the overloaded function to query internal registers like [sliceID](https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Languages/OpenCL/IBiF_Impl.cl#L788). So how can I make sure that the ocloc is using the debug form of IGC (that I built) and able to incorporate the overloadable functions in the binary. 
Also I was wondering if there is any tool through which I would be able to see the [gen assembly output ](https://software.intel.com/en-us/articles/introduction-to-gen-assembly) of the generated binary from ocloc. It is mentioned in [here](https://github.com/intel/opencl-intercept-layer/blob/master/docs/kernel_isa_gpu.md#building-an-intel-gpu-isa-disassembler) through which one can use iga64 to dissassemble and view the binary. I have tried to use it with the binary output from ocloc but I was not able to see gen assembly and also the output had lot of errors. 
So my goal is to use the overloadable functions in the kernel and then compile it to generate the binary. But I would also like to make sure that the functions and the register reading is incorporated in the binary which can be done by observing their corresponding gen file.

**Comment by duttasankha** [comment]
This discussion is getting continued in [intel opencl forum post](https://software.intel.com/en-us/forums/opencl/topic/800903#comment-1938372). However, as the issue is not solved yet, I would request not to close this issue. I apologize for causing this inconvenience. I would close this issue once it is solved. Thank you.

**Comment by paigeale** [comment]
Hello Sankha,

The following instructions should unblock you and only requires a "release" driver to compile your kernel above.

1) Search for the following line of code in <workspace>/igc/IGC/Compiler/Optimizer/OCLBIUtils.cpp (line 1612)

#if defined(_DEBUG) || defined(_INTERNAL)
    //Internal Debug Built-Ins
    m_CommandMap["__builtin_IB_read_cycle_counter"]  = CSimpleIntrinMapping::create(GenISAIntrinsic::GenISA_cycleCounter, false);

2) Move this line "m_CommandMap["__builtin_IB_read_cycle_counter..............." 3 lines up bringing it outside of the preprocessor directives "#if defined(_DEBUG) || defined(_INTERNAL)"

3) Wipe out your build folder and rebuild igc and the compute runtime from scratch.

4) Run your command line ocloc -file sample.cl -device kbl -output sampleOut -64 -llvm_text

**Comment by duttasankha** [comment]
Hello @paigeale  thanks for your reply, I have replied in the [forum](https://software.intel.com/en-us/forums/opencl/topic/800903#comment-1938593). It would be helpful if you could refer to the post. Thank you.

**Comment by duttasankha** [comment]
@paigeale 
Hi ..I followed your instructions but ocloc now doesn't produce any output. The details are posted in the forum. It would be really helpful if you could provide me some sort of feedback. Thank you.
