### ISSUE TITLE
Unable to build on CentOS 7

### ISSUE THREAD

**Issue by maretodoric** [intel/intel-graphics-compiler#88]
I have an issue building igc on CentOS 7. I can see that it's supported on Ubuntu and I'm trying to build it on CentOS 7 but i need it as a dependency for Intel compute-runtime.

Is there any chance that i can build this thing somehow so i can use it ?

I followed build instructions exactly from here:
This is build log (it fails on 16%, after 'Built target LLVMSupport' and 'Built target obj.llvm-tblgen' while running "make")

Log during cmake and make is on this link:

https://pastebin.com/xiYGJpNX

**Comment by paigeale** [comment]
Hello maretodoric,

I looked at your log file and noticed this error....
c++: error: unrecognized command line option ‘-std=c++14’ 

Please update your system's gcc version to 6 or above and try again.

Thanks,
Alex Palge

**Comment by paigeale** [comment]
@maretodoric ,

Do you still see the build issue after updating your gcc version? If not please close. 

Thanks,
Alex

**Comment by paigeale** [comment]
Closing issue due to no response from user. @maretodoric please reopen or file a new issue if problem still exists.
