### ISSUE TITLE
Running make in parallel always results in build failure

### ISSUE THREAD

**Issue by Brainiarc7** [intel/intel-graphics-compiler#89]
Hello there,

The build always fails when running make in parallel.
Please investigate.

An example, building from a workspace:

```sh
cd ~/intel-compute-runtime/workspace/build_igc
cmake ../igc/IGC
time make -j$(nproc) VERBOSE=1
```

This will fail. However, substituting the make process with `-j` explicitly set to 1 will result in a successful build.

**Comment by iwwu** [comment]
@Brainiarc7 Can you provide more information? What did you do before cmake and make?

I did 2 experiments on latest IGC code yesterday. Both "make -j4" and "time make -j4" built igc_dll successfully.

**Comment by iwwu** [comment]
I did the build on latest IGC yesterday, then realized my nproc is 1. I will find another system to try again.

**Comment by Brainiarc7** [comment]
Sure, please do.

**Comment by iwwu** [comment]
@Brainiarc7 Can you provide the failing message? Does "make -j$(nproc)" work for you?

**Comment by Brainiarc7** [comment]
On my system, no.
nproc returns 12 (as I have an i7 8750H).
I'll provide the log when the system is up and running.

**Comment by iwwu** [comment]
@Brainiarc7 Are you running on ubuntu 18 LTS? Please provide your system information. Thanks.

**Comment by Brainiarc7** [comment]
Yes, I’m on Ubuntu 18.04 LTS

**Comment by Brainiarc7** [comment]
See this:

Kernel:

```
uname -r 
5.1.0

```

OS:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

Processor count:

```
nproc
12
```

GCC:

```
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Clang:

```
clang-4.0 --version
clang version 4.0.1-10 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by paigeale** [comment]
Hello Brainiarc7,

Could you try the tip of igc? With running the following commands 

cd build
cmake -DVME_TYPES_DEFINED=FALSE ../igc/IGC
make -j12 

I ran the following commands with 16 processors and was able to build IGC. If you still get an error please add a snippet of your error message.

Thanks,
Alex

**Comment by Brainiarc7** [comment]
Will do shortly, thanks.

**Comment by Brainiarc7** [comment]
Hey there @paigeale ,

Doing so results in a build failure, using the current git tip:

'''sh
/usr/bin/ranlib ../Release/libCompiler.a
make[2]: Leaving directory '/home/brainiarc7/intel-compute-runtime/workspace/build_igc'
[ 96%] Built target Compiler
make[1]: Leaving directory '/home/brainiarc7/intel-compute-runtime/workspace/build_igc'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

real	16m54.833s
user	190m28.350s
sys	8m31.129s
```

**Comment by paigeale** [comment]
Hey @Brainiarc7 ,

So the -DVME_TYPES_DEFINED=FALSE didn't work for you (you can remove that). I thought you may be missing some vme libraries but you are not. Could you attach the failing log prior to making the CMake change?

**Comment by Brainiarc7** [comment]
Yes, indeed it broke the build.
Omitting that option on the current git tip resulted in a working build.
The log posted prior is identical to the one I received before. A commit
must have fixed my issue shortly afterwards.
I'll now mark this as closed.

**Comment by paigeale** [comment]
Great to hear it is now working as expected. Please email me (email in profile) and let me know if you have any feedback on what would make this process easier in the future.

**Comment by Brainiarc7** [comment]
@paigeale thanks, I've followed up on the same via email.
