### ISSUE TITLE
Debug builds are not wroking correctly

### ISSUE THREAD

**Issue by MichalMrozek** [intel/intel-graphics-compiler#9]
Hello,
@ruiling  reports problem with debug build configuration:
https://github.com/intel/compute-runtime/issues/26

Looks like problems while building IGC.
"EnableDxbcDump not defined but used in IGC/AdaptorCommon/customApi.cpp
an invalid product family was passed in to IGC::SetWorkaroundTable() which triggers an assert there.
please help to fix them."

**Comment by AnupamaChandrasekhar** [comment]
Hi, Thanks for bring this to our attention. We have fixed this in our internal code and it will be mirrored after passing validation. Thank you.
