### ISSUE TITLE
1.0.4 compile failure: o matching function for call to 'CIF::InterfacesList<SupportedInterfaces>::forwardToOne<CIF::IsInterfaceIdFwdToOne, bool, bool>(CIF::InterfaceId_t&, bool)'

### ISSUE THREAD

**Issue by fenrus75** [intel/intel-graphics-compiler#92]
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/IGC/AdaptorOCL/cif/cif/../cif/common/cif.h: In static member function 'static bool CIF::InterfacesList<SupportedInterfaces>::ContainsInterface(CIF::InterfaceId_t)':
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/IGC/AdaptorOCL/cif/cif/../cif/common/cif.h:331:71: error: no matching function for call to 'CIF::InterfacesList<SupportedInterfaces>::forwardToOne<CIF::IsInterfaceIdFwdToOne, bool, bool>(CIF::InterfaceId_t&, bool)'
  331 |       return forwardToOne<IsInterfaceIdFwdToOne, bool, bool>(id, false);
      |                                                                       ^
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/IGC/AdaptorOCL/cif/cif/../cif/common/cif.h:308:18: note: candidate: 'template<template<long unsigned int <anonymous> > class ... SupportedInterfaces> template<class Callable, class RetType, class DefaultValueT, class ... Args> static RetType CIF::InterfacesList<SupportedInterfaces>::forwardToOne(CIF::InterfaceId_t, DefaultValueT&&, Args&& ...)'
  308 |   static RetType forwardToOne(InterfaceId_t requestedInterfaceId, DefaultValueT &&defaultValue, Args &&... args) {
      |                  ^~~~~~~~~~~~
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/IGC/AdaptorOCL/cif/cif/../cif/common/cif.h:308:18: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/IGC/AdaptorOCL/cif/cif/../cif/common/cif.h:331:71: note:   mismatched types 'DefaultValueT' and 'bool'
  331 |       return forwardToOne<IsInterfaceIdFwdToOne, bool, bool>(id, false);

**Comment by lwesiers** [comment]
Please provide full build logs (including cmake and make logs).

**Comment by chivakker** [comment]
[build.log](https://github.com/intel/intel-graphics-compiler/files/3200132/build.log)

Attaching the log file.

Tried also to build 1.0.1 and same error happened.

**Comment by chivakker** [comment]
when building with clang-8

cd /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.4/clr-build/IGC/visa/iga/IGAExe && /usr/bin/cmake -E cmake_link_script CMakeFiles/IGA_EXE.dir/link.txt --verbose=1 
/usr/lib64/ccache/bin/clang++  -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -flto -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -ffat-lto-objects -flto -O2 -fmessage-length=0 -march=corei7 -mstackrealign -fms-extensions -Wno-unused-parameter -Wno-missing-field-initializers -Wwrite-strings -Wno-long-long -Wswitch -Wno-sign-compare -Wno-unused-result -Wno-enum-compare -Wno-type-limits -Wno-ignored-qualifiers -Wno-extra -Wno-write-strings -finline -fno-strict-aliasing -msse -msse2 -msse3 -mssse3 -msse4 -msse4.1 -msse4.2 -Wno-unknown-pragmas -fPIC -D_FORTIFY_SOURCE=2 -finline-functions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -std=c++14 -DNDEBUG  -Wl,--gc-sections -rdynamic CMakeFiles/IGA_EXE.dir/assemble.cpp.o CMakeFiles/IGA_EXE.dir/disassemble.cpp.o CMakeFiles/IGA_EXE.dir/decode_fields.cpp.o CMakeFiles/IGA_EXE.dir/iga_main.cpp.o CMakeFiles/IGA_EXE.dir/list_ops.cpp.o CMakeFiles/IGA_EXE.dir/main.cpp.o  -o ../../../Release/iga64 ../../../Release/libiga_s64.a -lrt  
/usr/bin/ld: ../../../Release/libiga_s64.a: error adding symbols: archive has no index; run ranlib to add one

**Comment by paigeale** [comment]
@ArturHarasimiuk,

Does this commit 1ea3c7f80429940179c9744ec8fc8f40d3d13752 fix this issue reported by Arjan?

**Comment by chivakker** [comment]
@paigeale I think that patch won't fix the compilation issue with gcc-9.  Is that something you guys can fix?  As you can see above we were passing -flto with clang-8 but even without that it is not compiling as there are some llvm dependencies missing.  

Please let us know if you guys will actively debug it
